SET(SOURCES ui_ScreenMain.c
    ui_ScreenPrintStatus.c
    ui_ScreenJog.c
    ui_ScreenTMC.c
    ui_ScreenFilament.c
    ui_ScreenFiles.c
    ui_ScreenSettings.c
    ui_ScreenAbout.c
    ui_ScreenTemperature.c
    ui.c
    ui_comp_hook.c
    ui_helpers.c
    ui_events.c
    ui_img_247885993.c
    ui_img_1465085387.c
    ui_img_1237989568.c
    ui_img_1439640658.c
    ui_img_377306522.c
    ui_img_1312856521.c
    ui_img_564518316.c
    ui_img_1988419691.c
    ui_img_2072515320.c
    ui_img_653996564.c
    ui_img_1038364564.c
    ui_img_722526726.c
    ui_img_398448242.c
    ui_img_1983858668.c
    ui_img_931356233.c
    ui_img_2098359223.c
    ui_img_1302380444.c
    ui_img_858268281.c
    ui_img_1272866020.c
    ui_img_565287032.c
    ui_img_681280759.c
    ui_img_461506120.c
    ui_img_1099881434.c
    ui_img_355628395.c
    ui_img_426815153.c)

add_library(ui ${SOURCES})
