// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#include "ui.h"

lv_obj_t * ui_HomeX;
lv_obj_t * ui_HomeY;
lv_obj_t * ui_HomeZ;
lv_obj_t * ui_BtnHomeZ;
lv_obj_t * ui_BtnHomeY;
lv_obj_t * ui_BtnHomeX;
lv_obj_t * ui_BtnSaveMesh;
lv_obj_t * ui_Load_Mesh;
lv_obj_t * ui_BtnLoadMesh;
lv_obj_t * ui_BtnAutoBedLevel;
lv_obj_t * ui_BtnAutoZAlign;
lv_obj_t * ui_LabelPosZ;
lv_obj_t * ui_LabelPosY;
lv_obj_t * ui_LabelPosX;
lv_obj_t * ui_SliderBabyZ;
lv_obj_t * ui_LabelBabyZ;
lv_obj_t * ui_DropdownStep;
lv_obj_t * ui_HOME_ALL;
lv_obj_t * ui_BtnHomeAll;
lv_obj_t * ui_Image16;
lv_obj_t * ui_ZMinus;
lv_obj_t * ui_BtnZMinus;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Image6;
lv_obj_t * ui_ZPlus;
lv_obj_t * ui_BtnZPlus;
lv_obj_t * ui_XPus;
lv_obj_t * ui_BtnXPlus;
lv_obj_t * ui_XMinus;
lv_obj_t * ui_BtnXMinus;
lv_obj_t * ui_YMinus;
lv_obj_t * ui_BtnYMinus;
lv_obj_t * ui_YPlus;
lv_obj_t * ui_BtnYPlus;
lv_obj_t * ui_LabelBack1;
lv_obj_t * ui_BtnBack1;
lv_obj_t * ui_LabelScreenTitle;
lv_obj_t * ui_uiPanelTopNav;
lv_obj_t * ui_ScreenJog;
lv_obj_t * ui_ScreenJog = NULL;
lv_obj_t * ui_PanelTopNav3 = NULL;
lv_obj_t * ui_LabelScreenTitle = NULL;
lv_obj_t * ui_BtnBack1 = NULL;
lv_obj_t * ui_LabelBack1 = NULL;
lv_obj_t * ui_BtnYPlus = NULL;
lv_obj_t * ui_YPlus = NULL;
lv_obj_t * ui_BtnYMinus = NULL;
lv_obj_t * ui_YMinus = NULL;
lv_obj_t * ui_BtnXMinus = NULL;
lv_obj_t * ui_XMinus = NULL;
lv_obj_t * ui_BtnXPlus = NULL;
lv_obj_t * ui_XPus = NULL;
lv_obj_t * ui_BtnZPlus = NULL;
lv_obj_t * ui_ZPlus = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_BtnZMinus = NULL;
lv_obj_t * ui_ZMinus = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_BtnHomeAll = NULL;
lv_obj_t * ui_HOME_ALL = NULL;
lv_obj_t * ui_DropdownStep = NULL;
lv_obj_t * ui_LabelBabyZ = NULL;
lv_obj_t * ui_SliderBabyZ = NULL;
lv_obj_t * ui_LabelPosX = NULL;
lv_obj_t * ui_LabelPosY = NULL;
lv_obj_t * ui_LabelPosZ = NULL;
lv_obj_t * ui_BtnAutoZAlign = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_BtnAutoBedLevel = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_BtnLoadMesh = NULL;
lv_obj_t * ui_Load_Mesh = NULL;
lv_obj_t * ui_BtnSaveMesh = NULL;
lv_obj_t * ui_Save_Mesh = NULL;
lv_obj_t * ui_BtnHomeX = NULL;
lv_obj_t * ui_BtnHomeY = NULL;
lv_obj_t * ui_BtnHomeZ = NULL;
lv_obj_t * ui_HomeZ = NULL;
lv_obj_t * ui_HomeY = NULL;
lv_obj_t * ui_HomeX = NULL;
// event funtions
void ui_event_BtnBack1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
    }
}

// build funtions

void ui_ScreenJog_screen_init(void)
{
    ui_ScreenJog = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenJog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_ScreenJog, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenJog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ScreenJog, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTopNav3 = lv_obj_create(ui_ScreenJog);
    lv_obj_set_width(ui_PanelTopNav3, 800);
    lv_obj_set_height(ui_PanelTopNav3, 60);
    lv_obj_clear_flag(ui_PanelTopNav3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTopNav3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTopNav3, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTopNav3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScreenTitle = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelScreenTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScreenTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelScreenTitle, 20);
    lv_obj_set_y(ui_LabelScreenTitle, 15);
    lv_label_set_text(ui_LabelScreenTitle, "JOG & LEVELING");
    lv_obj_set_style_text_color(ui_LabelScreenTitle, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScreenTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelScreenTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelScreenTitle, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBack1 = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnBack1, 100);
    lv_obj_set_height(ui_BtnBack1, 40);
    lv_obj_set_x(ui_BtnBack1, 680);
    lv_obj_set_y(ui_BtnBack1, 10);
    lv_obj_add_flag(ui_BtnBack1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBack1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBack1 = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelBack1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBack1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBack1, 331);
    lv_obj_set_y(ui_LabelBack1, -211);
    lv_obj_set_align(ui_LabelBack1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBack1, "Back");
    lv_obj_set_style_text_color(ui_LabelBack1, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBack1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBack1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBack1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnYPlus = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnYPlus, 100);
    lv_obj_set_height(ui_BtnYPlus, 80);
    lv_obj_set_x(ui_BtnYPlus, 180);
    lv_obj_set_y(ui_BtnYPlus, 150);
    lv_obj_add_flag(ui_BtnYPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnYPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnYPlus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnYPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnYPlus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnYPlus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YPlus = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_YPlus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_YPlus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_YPlus, 208);
    lv_obj_set_y(ui_YPlus, 150);
    lv_label_set_text(ui_YPlus, "Y+");
    lv_obj_set_style_text_color(ui_YPlus, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_YPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_YPlus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_YPlus, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnYMinus = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnYMinus, 100);
    lv_obj_set_height(ui_BtnYMinus, 80);
    lv_obj_set_x(ui_BtnYMinus, 180);
    lv_obj_set_y(ui_BtnYMinus, 350);
    lv_obj_add_flag(ui_BtnYMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnYMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnYMinus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnYMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnYMinus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnYMinus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YMinus = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_YMinus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_YMinus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_YMinus, 215);
    lv_obj_set_y(ui_YMinus, 385);
    lv_label_set_text(ui_YMinus, "Y-");
    lv_obj_set_style_text_color(ui_YMinus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_YMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_YMinus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_YMinus, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnXMinus = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnXMinus, 100);
    lv_obj_set_height(ui_BtnXMinus, 80);
    lv_obj_set_x(ui_BtnXMinus, 50);
    lv_obj_set_y(ui_BtnXMinus, 250);
    lv_obj_add_flag(ui_BtnXMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnXMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnXMinus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnXMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnXMinus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnXMinus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_XMinus = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_XMinus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_XMinus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_XMinus, 63);
    lv_obj_set_y(ui_XMinus, 265);
    lv_label_set_text(ui_XMinus, "X-");
    lv_obj_set_style_text_color(ui_XMinus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_XMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_XMinus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_XMinus, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnXPlus = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnXPlus, 100);
    lv_obj_set_height(ui_BtnXPlus, 80);
    lv_obj_set_x(ui_BtnXPlus, 310);
    lv_obj_set_y(ui_BtnXPlus, 250);
    lv_obj_add_flag(ui_BtnXPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnXPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnXPlus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnXPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnXPlus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnXPlus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_XPus = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_XPus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_XPus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_XPus, 356);
    lv_obj_set_y(ui_XPus, 268);
    lv_label_set_text(ui_XPus, "X+");
    lv_obj_set_style_text_color(ui_XPus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_XPus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_XPus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_XPus, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnZPlus = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnZPlus, 100);
    lv_obj_set_height(ui_BtnZPlus, 80);
    lv_obj_set_x(ui_BtnZPlus, 483);
    lv_obj_set_y(ui_BtnZPlus, 81);
    lv_obj_add_flag(ui_BtnZPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnZPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnZPlus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnZPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnZPlus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnZPlus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnZPlus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ZPlus = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_ZPlus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ZPlus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ZPlus, 119);
    lv_obj_set_y(ui_ZPlus, -119);
    lv_obj_set_align(ui_ZPlus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ZPlus, "Z+");
    lv_obj_set_style_text_color(ui_ZPlus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ZPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ZPlus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ZPlus, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_ScreenJog);
    lv_img_set_src(ui_Image6, &ui_img_2098359223);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image6, 165);
    lv_obj_set_y(ui_Image6, -115);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_ScreenJog);
    lv_img_set_src(ui_Image7, &ui_img_2098359223);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image7, -169);
    lv_obj_set_y(ui_Image7, -33);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_ScreenJog);
    lv_img_set_src(ui_Image8, &ui_img_1302380444);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image8, -170);
    lv_obj_set_y(ui_Image8, 131);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_ScreenJog);
    lv_img_set_src(ui_Image11, &ui_img_858268281);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image11, -273);
    lv_obj_set_y(ui_Image11, 50);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_img_create(ui_ScreenJog);
    lv_img_set_src(ui_Image12, &ui_img_1272866020);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image12, -69);
    lv_obj_set_y(ui_Image12, 50);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnZMinus = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnZMinus, 100);
    lv_obj_set_height(ui_BtnZMinus, 80);
    lv_obj_set_x(ui_BtnZMinus, 341);
    lv_obj_set_y(ui_BtnZMinus, 81);
    lv_obj_add_flag(ui_BtnZMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnZMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnZMinus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnZMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnZMinus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnZMinus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ZMinus = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_ZMinus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ZMinus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ZMinus, -27);
    lv_obj_set_y(ui_ZMinus, -117);
    lv_obj_set_align(ui_ZMinus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ZMinus, "Z-");
    lv_obj_set_style_text_color(ui_ZMinus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ZMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ZMinus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ZMinus, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image16 = lv_img_create(ui_ScreenJog);
    lv_img_set_src(ui_Image16, &ui_img_1302380444);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image16, 19);
    lv_obj_set_y(ui_Image16, -115);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnHomeAll = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnHomeAll, 120);
    lv_obj_set_height(ui_BtnHomeAll, 90);
    lv_obj_set_x(ui_BtnHomeAll, 169);
    lv_obj_set_y(ui_BtnHomeAll, 242);
    lv_obj_add_flag(ui_BtnHomeAll, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnHomeAll, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnHomeAll, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnHomeAll, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HOME_ALL = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_HOME_ALL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HOME_ALL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HOME_ALL, -173);
    lv_obj_set_y(ui_HOME_ALL, 48);
    lv_obj_set_align(ui_HOME_ALL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HOME_ALL, "HOME ALL");
    lv_obj_set_style_text_color(ui_HOME_ALL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HOME_ALL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HOME_ALL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HOME_ALL, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownStep = lv_dropdown_create(ui_ScreenJog);
    lv_dropdown_set_options(ui_DropdownStep, "0.1 mm\n1 mm\n5 mm\n10 mm\n50 mm\n100 mm");
    lv_dropdown_set_text(ui_DropdownStep, "Step Size ");
    lv_obj_set_width(ui_DropdownStep, 140);
    lv_obj_set_height(ui_DropdownStep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownStep, 436);
    lv_obj_set_y(ui_DropdownStep, 279);
    lv_obj_add_flag(ui_DropdownStep, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_DropdownStep, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DropdownStep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DropdownStep, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DropdownStep, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBabyZ = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelBabyZ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBabyZ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBabyZ, 441);
    lv_obj_set_y(ui_LabelBabyZ, 236);
    lv_label_set_text(ui_LabelBabyZ, "Baby Z: 0.00");
    lv_obj_set_style_text_color(ui_LabelBabyZ, lv_color_hex(0xFCFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBabyZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBabyZ, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBabyZ, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderBabyZ = lv_slider_create(ui_ScreenJog);
    lv_slider_set_range(ui_SliderBabyZ, -200, 200);
    lv_slider_set_value(ui_SliderBabyZ, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBabyZ) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBabyZ, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBabyZ, 200);
    lv_obj_set_height(ui_SliderBabyZ, 25);
    lv_obj_set_x(ui_SliderBabyZ, 390);
    lv_obj_set_y(ui_SliderBabyZ, 189);
    lv_obj_set_style_shadow_color(ui_SliderBabyZ, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SliderBabyZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SliderBabyZ, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SliderBabyZ, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPosX = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelPosX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPosX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPosX, 50);
    lv_obj_set_y(ui_LabelPosX, 80);
    lv_label_set_text(ui_LabelPosX, "X: 123.45");
    lv_obj_set_style_text_color(ui_LabelPosX, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPosX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPosX, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPosX, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPosY = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelPosY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPosY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPosY, 50);
    lv_obj_set_y(ui_LabelPosY, 120);
    lv_label_set_text(ui_LabelPosY, "Y: 234.56");
    lv_obj_set_style_text_color(ui_LabelPosY, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPosY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPosY, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPosY, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPosZ = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelPosZ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPosZ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPosZ, 50);
    lv_obj_set_y(ui_LabelPosZ, 160);
    lv_label_set_text(ui_LabelPosZ, "Z: 12.34");
    lv_obj_set_style_text_color(ui_LabelPosZ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPosZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPosZ, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPosZ, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnAutoZAlign = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnAutoZAlign, 160);
    lv_obj_set_height(ui_BtnAutoZAlign, 60);
    lv_obj_set_x(ui_BtnAutoZAlign, 620);
    lv_obj_set_y(ui_BtnAutoZAlign, 105);
    lv_obj_add_flag(ui_BtnAutoZAlign, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnAutoZAlign, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 632);
    lv_obj_set_y(ui_Label18, 122);
    lv_label_set_text(ui_Label18, "Auto Z Align\n");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFCFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label18, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnAutoBedLevel = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnAutoBedLevel, 160);
    lv_obj_set_height(ui_BtnAutoBedLevel, 60);
    lv_obj_set_x(ui_BtnAutoBedLevel, 620);
    lv_obj_set_y(ui_BtnAutoBedLevel, 190);
    lv_obj_add_flag(ui_BtnAutoBedLevel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnAutoBedLevel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 624);
    lv_obj_set_y(ui_Label19, 206);
    lv_label_set_text(ui_Label19, "Auto Bed Level");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label19, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnLoadMesh = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnLoadMesh, 160);
    lv_obj_set_height(ui_BtnLoadMesh, 60);
    lv_obj_set_x(ui_BtnLoadMesh, 620);
    lv_obj_set_y(ui_BtnLoadMesh, 275);
    lv_obj_add_flag(ui_BtnLoadMesh, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnLoadMesh, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_BtnLoadMesh, lv_color_hex(0xFDF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnLoadMesh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnLoadMesh, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Load_Mesh = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_Load_Mesh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Load_Mesh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Load_Mesh, 300);
    lv_obj_set_y(ui_Load_Mesh, 63);
    lv_obj_set_align(ui_Load_Mesh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Load_Mesh, "Load Mesh");
    lv_obj_set_style_text_color(ui_Load_Mesh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Load_Mesh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Load_Mesh, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Load_Mesh, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSaveMesh = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnSaveMesh, 160);
    lv_obj_set_height(ui_BtnSaveMesh, 60);
    lv_obj_set_x(ui_BtnSaveMesh, 620);
    lv_obj_set_y(ui_BtnSaveMesh, 360);
    lv_obj_add_flag(ui_BtnSaveMesh, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSaveMesh, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Save_Mesh = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_Save_Mesh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Save_Mesh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Save_Mesh, 298);
    lv_obj_set_y(ui_Save_Mesh, 147);
    lv_obj_set_align(ui_Save_Mesh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Save_Mesh, "Save Mesh");
    lv_obj_set_style_text_color(ui_Save_Mesh, lv_color_hex(0xFBFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Save_Mesh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Save_Mesh, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Save_Mesh, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnHomeX = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnHomeX, 100);
    lv_obj_set_height(ui_BtnHomeX, 50);
    lv_obj_set_x(ui_BtnHomeX, -308);
    lv_obj_set_y(ui_BtnHomeX, 150);
    lv_obj_set_align(ui_BtnHomeX, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnHomeX, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnHomeX, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnHomeX, lv_color_hex(0x29A141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnHomeX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnHomeY = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnHomeY, 100);
    lv_obj_set_height(ui_BtnHomeY, 50);
    lv_obj_set_x(ui_BtnHomeY, -41);
    lv_obj_set_y(ui_BtnHomeY, 150);
    lv_obj_set_align(ui_BtnHomeY, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnHomeY, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnHomeY, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnHomeY, lv_color_hex(0x29A141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnHomeY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnHomeZ = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnHomeZ, 100);
    lv_obj_set_height(ui_BtnHomeZ, 50);
    lv_obj_set_x(ui_BtnHomeZ, -167);
    lv_obj_set_y(ui_BtnHomeZ, -146);
    lv_obj_set_align(ui_BtnHomeZ, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnHomeZ, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnHomeZ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnHomeZ, lv_color_hex(0x29A141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnHomeZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeZ = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_HomeZ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeZ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeZ, -168);
    lv_obj_set_y(ui_HomeZ, -147);
    lv_obj_set_align(ui_HomeZ, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeZ, "Home Z");
    lv_obj_set_style_text_color(ui_HomeZ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeZ, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeZ, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeY = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_HomeY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeY, -42);
    lv_obj_set_y(ui_HomeY, 159);
    lv_obj_set_align(ui_HomeY, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeY, "Home Y\n");
    lv_obj_set_style_text_color(ui_HomeY, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeY, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeY, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeX = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_HomeX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HomeX, -308);
    lv_obj_set_y(ui_HomeX, 159);
    lv_obj_set_align(ui_HomeX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeX, "Home X\n");
    lv_obj_set_style_text_color(ui_HomeX, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeX, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeX, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnBack1, ui_event_BtnBack1, LV_EVENT_ALL, NULL);
    ui_ScreenJog = ui_ScreenJog;
    ui_uiPanelTopNav = ui_PanelTopNav3;
    ui_LabelScreenTitle = ui_LabelScreenTitle;
    ui_BtnBack1 = ui_BtnBack1;
    ui_LabelBack1 = ui_LabelBack1;
    ui_BtnYPlus = ui_BtnYPlus;
    ui_YPlus = ui_YPlus;
    ui_BtnYMinus = ui_BtnYMinus;
    ui_YMinus = ui_YMinus;
    ui_BtnXMinus = ui_BtnXMinus;
    ui_XMinus = ui_XMinus;
    ui_BtnXPlus = ui_BtnXPlus;
    ui_XPus = ui_XPus;
    ui_BtnZPlus = ui_BtnZPlus;
    ui_ZPlus = ui_ZPlus;
    ui_Image6 = ui_Image6;
    ui_Image7 = ui_Image7;
    ui_Image8 = ui_Image8;
    ui_Image11 = ui_Image11;
    ui_Image12 = ui_Image12;
    ui_BtnZMinus = ui_BtnZMinus;
    ui_ZMinus = ui_ZMinus;
    ui_Image16 = ui_Image16;
    ui_BtnHomeAll = ui_BtnHomeAll;
    ui_HOME_ALL = ui_HOME_ALL;
    ui_DropdownStep = ui_DropdownStep;
    ui_LabelBabyZ = ui_LabelBabyZ;
    ui_SliderBabyZ = ui_SliderBabyZ;
    ui_LabelPosX = ui_LabelPosX;
    ui_LabelPosY = ui_LabelPosY;
    ui_LabelPosZ = ui_LabelPosZ;
    ui_BtnAutoZAlign = ui_BtnAutoZAlign;
    ui_BtnAutoBedLevel = ui_BtnAutoBedLevel;
    ui_BtnLoadMesh = ui_BtnLoadMesh;
    ui_Load_Mesh = ui_Load_Mesh;
    ui_BtnSaveMesh = ui_BtnSaveMesh;
    ui_BtnHomeX = ui_BtnHomeX;
    ui_BtnHomeY = ui_BtnHomeY;
    ui_BtnHomeZ = ui_BtnHomeZ;
    ui_HomeZ = ui_HomeZ;
    ui_HomeY = ui_HomeY;
    ui_HomeX = ui_HomeX;

}

void ui_ScreenJog_screen_destroy(void)
{
    if(ui_ScreenJog) lv_obj_del(ui_ScreenJog);

    // NULL screen variables
    ui_ScreenJog = NULL;
    ui_ScreenJog = NULL;
    ui_uiPanelTopNav = NULL;
    ui_PanelTopNav3 = NULL;
    ui_LabelScreenTitle = NULL;
    ui_LabelScreenTitle = NULL;
    ui_BtnBack1 = NULL;
    ui_BtnBack1 = NULL;
    ui_LabelBack1 = NULL;
    ui_LabelBack1 = NULL;
    ui_BtnYPlus = NULL;
    ui_BtnYPlus = NULL;
    ui_YPlus = NULL;
    ui_YPlus = NULL;
    ui_BtnYMinus = NULL;
    ui_BtnYMinus = NULL;
    ui_YMinus = NULL;
    ui_YMinus = NULL;
    ui_BtnXMinus = NULL;
    ui_BtnXMinus = NULL;
    ui_XMinus = NULL;
    ui_XMinus = NULL;
    ui_BtnXPlus = NULL;
    ui_BtnXPlus = NULL;
    ui_XPus = NULL;
    ui_XPus = NULL;
    ui_BtnZPlus = NULL;
    ui_BtnZPlus = NULL;
    ui_ZPlus = NULL;
    ui_ZPlus = NULL;
    ui_Image6 = NULL;
    ui_Image6 = NULL;
    ui_Image7 = NULL;
    ui_Image7 = NULL;
    ui_Image8 = NULL;
    ui_Image8 = NULL;
    ui_Image11 = NULL;
    ui_Image11 = NULL;
    ui_Image12 = NULL;
    ui_Image12 = NULL;
    ui_BtnZMinus = NULL;
    ui_BtnZMinus = NULL;
    ui_ZMinus = NULL;
    ui_ZMinus = NULL;
    ui_Image16 = NULL;
    ui_Image16 = NULL;
    ui_BtnHomeAll = NULL;
    ui_BtnHomeAll = NULL;
    ui_HOME_ALL = NULL;
    ui_HOME_ALL = NULL;
    ui_DropdownStep = NULL;
    ui_DropdownStep = NULL;
    ui_LabelBabyZ = NULL;
    ui_LabelBabyZ = NULL;
    ui_SliderBabyZ = NULL;
    ui_SliderBabyZ = NULL;
    ui_LabelPosX = NULL;
    ui_LabelPosX = NULL;
    ui_LabelPosY = NULL;
    ui_LabelPosY = NULL;
    ui_LabelPosZ = NULL;
    ui_LabelPosZ = NULL;
    ui_BtnAutoZAlign = NULL;
    ui_BtnAutoZAlign = NULL;
    ui_Label18 = NULL;
    ui_BtnAutoBedLevel = NULL;
    ui_BtnAutoBedLevel = NULL;
    ui_Label19 = NULL;
    ui_BtnLoadMesh = NULL;
    ui_BtnLoadMesh = NULL;
    ui_Load_Mesh = NULL;
    ui_Load_Mesh = NULL;
    ui_BtnSaveMesh = NULL;
    ui_BtnSaveMesh = NULL;
    ui_Save_Mesh = NULL;
    ui_BtnHomeX = NULL;
    ui_BtnHomeX = NULL;
    ui_BtnHomeY = NULL;
    ui_BtnHomeY = NULL;
    ui_BtnHomeZ = NULL;
    ui_BtnHomeZ = NULL;
    ui_HomeZ = NULL;
    ui_HomeZ = NULL;
    ui_HomeY = NULL;
    ui_HomeY = NULL;
    ui_HomeX = NULL;
    ui_HomeX = NULL;

}
