// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#ifndef UI_SCREENSETTINGS_H
#define UI_SCREENSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSettings
extern void ui_ScreenSettings_screen_init(void);
extern void ui_ScreenSettings_screen_destroy(void);
extern lv_obj_t * ui_ScreenSettings;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_LabelTitleSettings;
extern void ui_event_BtnAbout(lv_event_t * e);
extern lv_obj_t * ui_BtnAbout;
extern lv_obj_t * ui_LabelAbout;
extern void ui_event_BtnBack5(lv_event_t * e);
extern lv_obj_t * ui_BtnBack5;
extern lv_obj_t * ui_LabelBack5;
extern lv_obj_t * ui_PanelSteps;
extern lv_obj_t * ui_LabelStepsTitle;
extern void ui_event_TxtXSteps(lv_event_t * e);
extern lv_obj_t * ui_TxtXSteps;
extern void ui_event_TextYArea(lv_event_t * e);
extern lv_obj_t * ui_TextYArea;
extern void ui_event_TxtZSteps(lv_event_t * e);
extern lv_obj_t * ui_TxtZSteps;
extern void ui_event_TxtE0Steps(lv_event_t * e);
extern lv_obj_t * ui_TxtE0Steps;
extern lv_obj_t * ui_LabelXSteps;
extern lv_obj_t * ui_LabelYSteps;
extern lv_obj_t * ui_LabelZSteps;
extern lv_obj_t * ui_LabelE0Steps;
extern void ui_event_BtnApplySteps(lv_event_t * e);
extern lv_obj_t * ui_BtnApplySteps;
extern lv_obj_t * ui_LabelApplySteps;
extern lv_obj_t * ui_PanelFilament;
extern lv_obj_t * ui_LabelFilDia;
extern lv_obj_t * ui_LabelFlow;
extern void ui_event_TxtFilDia(lv_event_t * e);
extern lv_obj_t * ui_TxtFilDia;
extern void ui_event_SliderFlow(lv_event_t * e);
extern lv_obj_t * ui_SliderFlow;
extern lv_obj_t * ui_LabelFlowValue;
extern lv_obj_t * ui_PanelDisplay;
extern void ui_event_SliderBrightness(lv_event_t * e);
extern lv_obj_t * ui_SliderBrightness;
extern lv_obj_t * ui_LabelBrightnessValue;
extern lv_obj_t * ui_LabelBrightness;
extern lv_obj_t * ui_SwitchSound;
extern lv_obj_t * ui_SwitchScreenTimeout;
extern lv_obj_t * ui_LabelSwitchSound;
extern lv_obj_t * ui_LabelScreenTimeout;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_PanelNetwork;
extern lv_obj_t * ui_SwitchWiFi;
extern lv_obj_t * ui_LabelSwitchWiFi;
extern lv_obj_t * ui_TxtSSID;
extern lv_obj_t * ui_TxtPassword;
extern lv_obj_t * ui_PanelSystem;
extern void ui_event_BtnSaveAll(lv_event_t * e);
extern lv_obj_t * ui_BtnSaveAll;
extern lv_obj_t * ui_Label33;
extern void ui_event_BtnFactoryReset(lv_event_t * e);
extern lv_obj_t * ui_BtnFactoryReset;
extern lv_obj_t * ui_LabelFactoryReset;
extern lv_obj_t * ui_BtnReboot;
extern lv_obj_t * ui_LabelReboot;
extern lv_obj_t * ui_PanelNumPad;
extern lv_obj_t * ui_LabelNumPadTitle;
extern lv_obj_t * ui_TxtNumPadInput;
extern void ui_event_BtnNum7(lv_event_t * e);
extern lv_obj_t * ui_BtnNum7;
extern lv_obj_t * ui_LabelNum7;
extern void ui_event_BtnNum8(lv_event_t * e);
extern lv_obj_t * ui_BtnNum8;
extern lv_obj_t * ui_LabelNum8;
extern void ui_event_BtnNum9(lv_event_t * e);
extern lv_obj_t * ui_BtnNum9;
extern lv_obj_t * ui_LabelNum9;
extern void ui_event_BtnNum4(lv_event_t * e);
extern lv_obj_t * ui_BtnNum4;
extern lv_obj_t * ui_LabelNum4;
extern void ui_event_BtnNum5(lv_event_t * e);
extern lv_obj_t * ui_BtnNum5;
extern lv_obj_t * ui_LabelNum5;
extern void ui_event_BtnNum6(lv_event_t * e);
extern lv_obj_t * ui_BtnNum6;
extern lv_obj_t * ui_LabelNum6;
extern void ui_event_BtnNum1(lv_event_t * e);
extern lv_obj_t * ui_BtnNum1;
extern lv_obj_t * ui_LabelNum1;
extern void ui_event_BtnNum2(lv_event_t * e);
extern lv_obj_t * ui_BtnNum2;
extern lv_obj_t * ui_LabelNum2;
extern void ui_event_BtnNum3(lv_event_t * e);
extern lv_obj_t * ui_BtnNum3;
extern lv_obj_t * ui_LabelNum3;
extern void ui_event_BtnNum0(lv_event_t * e);
extern lv_obj_t * ui_BtnNum0;
extern lv_obj_t * ui_LabelNum0;
extern void ui_event_BtnNumDecimal(lv_event_t * e);
extern lv_obj_t * ui_BtnNumDecimal;
extern lv_obj_t * ui_LabelNumDecimal;
extern void ui_event_BtnNumENTER(lv_event_t * e);
extern lv_obj_t * ui_BtnNumENTER;
extern lv_obj_t * ui_LabelNumEnter;
extern void ui_event_BtnNumBackspace(lv_event_t * e);
extern lv_obj_t * ui_BtnNumBackspace;
extern lv_obj_t * ui_LabelNumBackspace;
extern void ui_event_BtnNumClear(lv_event_t * e);
extern lv_obj_t * ui_BtnNumClear;
extern lv_obj_t * ui_LabelNumClear;
extern void ui_event_BtnNumCancel(lv_event_t * e);
extern lv_obj_t * ui_BtnNumCancel;
extern lv_obj_t * ui_LabelNumCancel;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ScreenSettings;
extern lv_obj_t * ui_LabelTitleSettings;
extern lv_obj_t * ui_BtnAbout;
extern lv_obj_t * ui_LabelAbout;
extern lv_obj_t * ui_BtnBack5;
extern lv_obj_t * ui_LabelBack5;
extern lv_obj_t * ui_PanelSteps;
extern lv_obj_t * ui_LabelStepsTitle;
extern lv_obj_t * ui_TxtXSteps;
extern lv_obj_t * ui_TextYArea;
extern lv_obj_t * ui_TxtZSteps;
extern lv_obj_t * ui_TxtE0Steps;
extern lv_obj_t * ui_LabelXSteps;
extern lv_obj_t * ui_LabelYSteps;
extern lv_obj_t * ui_LabelZSteps;
extern lv_obj_t * ui_LabelE0Steps;
extern lv_obj_t * ui_BtnApplySteps;
extern lv_obj_t * ui_LabelApplySteps;
extern lv_obj_t * ui_PanelFilament;
extern lv_obj_t * ui_LabelFilDia;
extern lv_obj_t * ui_TxtFilDia;
extern lv_obj_t * ui_SliderFlow;
extern lv_obj_t * ui_LabelFlowValue;
extern lv_obj_t * ui_PanelDisplay;
extern lv_obj_t * ui_SliderBrightness;
extern lv_obj_t * ui_LabelBrightnessValue;
extern lv_obj_t * ui_LabelBrightness;
extern lv_obj_t * ui_SwitchSound;
extern lv_obj_t * ui_SwitchScreenTimeout;
extern lv_obj_t * ui_LabelSwitchSound;
extern lv_obj_t * ui_LabelScreenTimeout;
extern lv_obj_t * ui_PanelNetwork;
extern lv_obj_t * ui_SwitchWiFi;
extern lv_obj_t * ui_LabelSwitchWiFi;
extern lv_obj_t * ui_TxtSSID;
extern lv_obj_t * ui_TxtPassword;
extern lv_obj_t * ui_PanelSystem;
extern lv_obj_t * ui_BtnSaveAll;
extern lv_obj_t * ui_LabelFactoryReset;
extern lv_obj_t * ui_BtnReboot;
extern lv_obj_t * ui_LabelReboot;
extern lv_obj_t * ui_PanelNumPad;
extern lv_obj_t * ui_LabelNumPadTitle;
extern lv_obj_t * ui_TxtNumPadInput;
extern lv_obj_t * ui_BtnNum7;
extern lv_obj_t * ui_LabelNum7;
extern lv_obj_t * ui_BtnNum8;
extern lv_obj_t * ui_BtnNum9;
extern lv_obj_t * ui_BtnNum4;
extern lv_obj_t * ui_LabelNum4;
extern lv_obj_t * ui_BtnNum5;
extern lv_obj_t * ui_LabelNum5;
extern lv_obj_t * ui_BtnNum6;
extern lv_obj_t * ui_LabelNum6;
extern lv_obj_t * ui_BtnNum1;
extern lv_obj_t * ui_LabelNum1;
extern lv_obj_t * ui_BtnNum2;
extern lv_obj_t * ui_LabelNum2;
extern lv_obj_t * ui_BtnNum3;
extern lv_obj_t * ui_LabelNum3;
extern lv_obj_t * ui_BtnNum0;
extern lv_obj_t * ui_BtnNumDecimal;
extern lv_obj_t * ui_LabelNumDecimal;
extern lv_obj_t * ui_BtnNumENTER;
extern lv_obj_t * ui_LabelNumEnter;
extern lv_obj_t * ui_BtnNumBackspace;
extern lv_obj_t * ui_LabelNumBackspace;
extern lv_obj_t * ui_BtnNumClear;
extern lv_obj_t * ui_LabelNumClear;
extern lv_obj_t * ui_BtnNumCancel;
extern lv_obj_t * ui_LabelNumCancel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

