// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#include "ui.h"

lv_obj_t * ui_LabelCustom;
lv_obj_t * ui_BtnCustom;
lv_obj_t * ui_LabelABS;
lv_obj_t * ui_BtnABS;
lv_obj_t * ui_LabelPETG;
lv_obj_t * ui_BtnPETG;
lv_obj_t * ui_LabelPLA;
lv_obj_t * ui_BtnPLA;
lv_obj_t * ui_LabelBedValue;
lv_obj_t * ui_ArcBed;
lv_obj_t * ui_ArcHotend;
lv_obj_t * ui_LabelHotendValue;
lv_obj_t * ui_LabelBack7;
lv_obj_t * ui_BtnBack7;
lv_obj_t * ui_ScreenTemperature;
lv_obj_t * ui_ScreenTemperature = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_BtnBack7 = NULL;
lv_obj_t * ui_LabelBack7 = NULL;
lv_obj_t * ui_LabelTitle3 = NULL;
lv_obj_t * ui_LabelHotendTitle1 = NULL;
lv_obj_t * ui_LabelHotendValue = NULL;
lv_obj_t * ui_ArcHotend = NULL;
lv_obj_t * ui_Image23 = NULL;
lv_obj_t * ui_LabelBedTitle1 = NULL;
lv_obj_t * ui_ArcBed = NULL;
lv_obj_t * ui_LabelBedValue = NULL;
lv_obj_t * ui_Image27 = NULL;
lv_obj_t * ui_BtnPLA = NULL;
lv_obj_t * ui_LabelPLA = NULL;
lv_obj_t * ui_BtnPETG = NULL;
lv_obj_t * ui_LabelPETG = NULL;
lv_obj_t * ui_BtnABS = NULL;
lv_obj_t * ui_LabelABS = NULL;
lv_obj_t * ui_BtnCustom = NULL;
lv_obj_t * ui_LabelCustom = NULL;
// event funtions
void ui_event_BtnBack7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
    }
}

void ui_event_ArcHotend(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventArcHotend(e);
    }
}

void ui_event_ArcBed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventArcBed(e);
    }
}

void ui_event_LabelBedValue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventLabelBedValue(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelHotendValue, target, "", "");
    }
}

void ui_event_BtnPLA(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnPLA(e);
    }
}

void ui_event_BtnPETG(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnPETG(e);
    }
}

void ui_event_BtnABS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnABS(e);
    }
}

void ui_event_BtnCustom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnPLA(e);
    }
}

void ui_event_LabelCustom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnCustom(e);
    }
}

// build funtions

void ui_ScreenTemperature_screen_init(void)
{
    ui_ScreenTemperature = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenTemperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenTemperature, lv_color_hex(0x02374D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_Panel8, 800);
    lv_obj_set_height(ui_Panel8, 60);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBack7 = lv_btn_create(ui_Panel8);
    lv_obj_set_width(ui_BtnBack7, 100);
    lv_obj_set_height(ui_BtnBack7, 40);
    lv_obj_set_x(ui_BtnBack7, 649);
    lv_obj_set_y(ui_BtnBack7, -11);
    lv_obj_add_flag(ui_BtnBack7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBack7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBack7 = lv_label_create(ui_BtnBack7);
    lv_obj_set_width(ui_LabelBack7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBack7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBack7, 0);
    lv_obj_set_y(ui_LabelBack7, 11);
    lv_obj_set_align(ui_LabelBack7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBack7, "Back\n");
    lv_obj_set_style_text_color(ui_LabelBack7, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBack7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBack7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBack7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitle3 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_LabelTitle3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle3, 7);
    lv_obj_set_y(ui_LabelTitle3, -6);
    lv_label_set_text(ui_LabelTitle3, "Temperature Control");
    lv_obj_set_style_text_color(ui_LabelTitle3, lv_color_hex(0xFBF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitle3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTitle3, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTitle3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHotendTitle1 = lv_label_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_LabelHotendTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHotendTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHotendTitle1, 122);
    lv_obj_set_y(ui_LabelHotendTitle1, 65);
    lv_label_set_text(ui_LabelHotendTitle1, "Hotend\n");
    lv_obj_set_style_text_color(ui_LabelHotendTitle1, lv_color_hex(0xFF8800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHotendTitle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHotendTitle1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHotendValue = lv_label_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_LabelHotendValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHotendValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHotendValue, 97);
    lv_obj_set_y(ui_LabelHotendValue, 121);
    lv_label_set_text(ui_LabelHotendValue, "205 / 210°C");
    lv_obj_set_style_text_color(ui_LabelHotendValue, lv_color_hex(0xFD0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHotendValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHotendValue, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHotendValue, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcHotend = lv_arc_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_ArcHotend, 220);
    lv_obj_set_height(ui_ArcHotend, 220);
    lv_obj_set_x(ui_ArcHotend, 78);
    lv_obj_set_y(ui_ArcHotend, 179);
    lv_arc_set_range(ui_ArcHotend, 0, 300);
    lv_arc_set_value(ui_ArcHotend, 50);
    lv_obj_set_style_arc_color(ui_ArcHotend, lv_color_hex(0xE38008), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHotend, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image23 = lv_img_create(ui_ScreenTemperature);
    lv_img_set_src(ui_Image23, &ui_img_355628395);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image23, -215);
    lv_obj_set_y(ui_Image23, 40);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBedTitle1 = lv_label_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_LabelBedTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBedTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBedTitle1, 569);
    lv_obj_set_y(ui_LabelBedTitle1, 71);
    lv_label_set_text(ui_LabelBedTitle1, "Bed");
    lv_obj_set_style_text_color(ui_LabelBedTitle1, lv_color_hex(0x4488FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBedTitle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBedTitle1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBedTitle1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBed = lv_arc_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_ArcBed, 220);
    lv_obj_set_height(ui_ArcBed, 220);
    lv_obj_set_x(ui_ArcBed, 492);
    lv_obj_set_y(ui_ArcBed, 178);
    lv_arc_set_value(ui_ArcBed, 50);
    lv_obj_set_style_arc_color(ui_ArcBed, lv_color_hex(0x1405FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcBed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBedValue = lv_label_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_LabelBedValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBedValue, 521);
    lv_obj_set_y(ui_LabelBedValue, 115);
    lv_label_set_text(ui_LabelBedValue, "60 / 60°C");
    lv_obj_set_style_text_color(ui_LabelBedValue, lv_color_hex(0xFD0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBedValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBedValue, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBedValue, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image27 = lv_img_create(ui_ScreenTemperature);
    lv_img_set_src(ui_Image27, &ui_img_426815153);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image27, 208);
    lv_obj_set_y(ui_Image27, 48);
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnPLA = lv_btn_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_BtnPLA, 140);
    lv_obj_set_height(ui_BtnPLA, 70);
    lv_obj_set_x(ui_BtnPLA, 80);
    lv_obj_set_y(ui_BtnPLA, 400);
    lv_obj_add_flag(ui_BtnPLA, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPLA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPLA = lv_label_create(ui_BtnPLA);
    lv_obj_set_width(ui_LabelPLA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPLA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPLA, -6);
    lv_obj_set_y(ui_LabelPLA, 2);
    lv_obj_set_align(ui_LabelPLA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPLA, "PLA");
    lv_obj_set_style_text_color(ui_LabelPLA, lv_color_hex(0xFD8B03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPLA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPLA, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPETG = lv_btn_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_BtnPETG, 140);
    lv_obj_set_height(ui_BtnPETG, 70);
    lv_obj_set_x(ui_BtnPETG, 240);
    lv_obj_set_y(ui_BtnPETG, 400);
    lv_obj_add_flag(ui_BtnPETG, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPETG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPETG = lv_label_create(ui_BtnPETG);
    lv_obj_set_width(ui_LabelPETG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPETG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPETG, -6);
    lv_obj_set_y(ui_LabelPETG, 2);
    lv_obj_set_align(ui_LabelPETG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPETG, "PETG");
    lv_obj_set_style_text_color(ui_LabelPETG, lv_color_hex(0xFDFA03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPETG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPETG, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnABS = lv_btn_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_BtnABS, 140);
    lv_obj_set_height(ui_BtnABS, 70);
    lv_obj_set_x(ui_BtnABS, 400);
    lv_obj_set_y(ui_BtnABS, 400);
    lv_obj_add_flag(ui_BtnABS, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnABS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelABS = lv_label_create(ui_BtnABS);
    lv_obj_set_width(ui_LabelABS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelABS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelABS, -6);
    lv_obj_set_y(ui_LabelABS, 2);
    lv_obj_set_align(ui_LabelABS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelABS, "ABS");
    lv_obj_set_style_text_color(ui_LabelABS, lv_color_hex(0xFD0318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelABS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelABS, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCustom = lv_btn_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_BtnCustom, 140);
    lv_obj_set_height(ui_BtnCustom, 70);
    lv_obj_set_x(ui_BtnCustom, 560);
    lv_obj_set_y(ui_BtnCustom, 400);
    lv_obj_add_flag(ui_BtnCustom, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCustom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCustom = lv_label_create(ui_BtnCustom);
    lv_obj_set_width(ui_LabelCustom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCustom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCustom, -1);
    lv_obj_set_y(ui_LabelCustom, 18);
    lv_obj_set_align(ui_LabelCustom, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCustom, "CUSTOM\n");
    lv_obj_set_style_text_color(ui_LabelCustom, lv_color_hex(0xFD8B03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCustom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCustom, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnBack7, ui_event_BtnBack7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcHotend, ui_event_ArcHotend, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcBed, ui_event_ArcBed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelBedValue, ui_event_LabelBedValue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPLA, ui_event_BtnPLA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPETG, ui_event_BtnPETG, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnABS, ui_event_BtnABS, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelCustom, ui_event_LabelCustom, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnCustom, ui_event_BtnCustom, LV_EVENT_ALL, NULL);
    ui_ScreenTemperature = ui_ScreenTemperature;
    ui_BtnBack7 = ui_BtnBack7;
    ui_LabelBack7 = ui_LabelBack7;
    ui_LabelHotendValue = ui_LabelHotendValue;
    ui_ArcHotend = ui_ArcHotend;
    ui_ArcBed = ui_ArcBed;
    ui_LabelBedValue = ui_LabelBedValue;
    ui_BtnPLA = ui_BtnPLA;
    ui_LabelPLA = ui_LabelPLA;
    ui_BtnPETG = ui_BtnPETG;
    ui_LabelPETG = ui_LabelPETG;
    ui_BtnABS = ui_BtnABS;
    ui_LabelABS = ui_LabelABS;
    ui_BtnCustom = ui_BtnCustom;
    ui_LabelCustom = ui_LabelCustom;

}

void ui_ScreenTemperature_screen_destroy(void)
{
    if(ui_ScreenTemperature) lv_obj_del(ui_ScreenTemperature);

    // NULL screen variables
    ui_ScreenTemperature = NULL;
    ui_ScreenTemperature = NULL;
    ui_Panel8 = NULL;
    ui_BtnBack7 = NULL;
    ui_BtnBack7 = NULL;
    ui_LabelBack7 = NULL;
    ui_LabelBack7 = NULL;
    ui_LabelTitle3 = NULL;
    ui_LabelHotendTitle1 = NULL;
    ui_LabelHotendValue = NULL;
    ui_LabelHotendValue = NULL;
    ui_ArcHotend = NULL;
    ui_ArcHotend = NULL;
    ui_Image23 = NULL;
    ui_LabelBedTitle1 = NULL;
    ui_ArcBed = NULL;
    ui_ArcBed = NULL;
    ui_LabelBedValue = NULL;
    ui_LabelBedValue = NULL;
    ui_Image27 = NULL;
    ui_BtnPLA = NULL;
    ui_BtnPLA = NULL;
    ui_LabelPLA = NULL;
    ui_LabelPLA = NULL;
    ui_BtnPETG = NULL;
    ui_BtnPETG = NULL;
    ui_LabelPETG = NULL;
    ui_LabelPETG = NULL;
    ui_BtnABS = NULL;
    ui_BtnABS = NULL;
    ui_LabelABS = NULL;
    ui_LabelABS = NULL;
    ui_BtnCustom = NULL;
    ui_BtnCustom = NULL;
    ui_LabelCustom = NULL;
    ui_LabelCustom = NULL;

}
