// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#ifndef UI_SCREENTEMPERATURE_H
#define UI_SCREENTEMPERATURE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenTemperature
extern void ui_ScreenTemperature_screen_init(void);
extern void ui_ScreenTemperature_screen_destroy(void);
extern lv_obj_t * ui_ScreenTemperature;
extern lv_obj_t * ui_Panel8;
extern void ui_event_BtnBack7(lv_event_t * e);
extern lv_obj_t * ui_BtnBack7;
extern lv_obj_t * ui_LabelBack7;
extern lv_obj_t * ui_LabelTitle3;
extern lv_obj_t * ui_LabelHotendTitle1;
extern lv_obj_t * ui_LabelHotendValue;
extern void ui_event_ArcHotend(lv_event_t * e);
extern lv_obj_t * ui_ArcHotend;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_LabelBedTitle1;
extern void ui_event_ArcBed(lv_event_t * e);
extern lv_obj_t * ui_ArcBed;
extern void ui_event_LabelBedValue(lv_event_t * e);
extern lv_obj_t * ui_LabelBedValue;
extern lv_obj_t * ui_Image27;
extern void ui_event_BtnPLA(lv_event_t * e);
extern lv_obj_t * ui_BtnPLA;
extern lv_obj_t * ui_LabelPLA;
extern void ui_event_BtnPETG(lv_event_t * e);
extern lv_obj_t * ui_BtnPETG;
extern lv_obj_t * ui_LabelPETG;
extern void ui_event_BtnABS(lv_event_t * e);
extern lv_obj_t * ui_BtnABS;
extern lv_obj_t * ui_LabelABS;
extern void ui_event_BtnCustom(lv_event_t * e);
extern lv_obj_t * ui_BtnCustom;
extern void ui_event_LabelCustom(lv_event_t * e);
extern lv_obj_t * ui_LabelCustom;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ScreenTemperature;
extern lv_obj_t * ui_BtnBack7;
extern lv_obj_t * ui_LabelBack7;
extern lv_obj_t * ui_LabelHotendValue;
extern lv_obj_t * ui_ArcHotend;
extern lv_obj_t * ui_ArcBed;
extern lv_obj_t * ui_LabelBedValue;
extern lv_obj_t * ui_BtnPLA;
extern lv_obj_t * ui_LabelPLA;
extern lv_obj_t * ui_BtnPETG;
extern lv_obj_t * ui_LabelPETG;
extern lv_obj_t * ui_BtnABS;
extern lv_obj_t * ui_LabelABS;
extern lv_obj_t * ui_BtnCustom;
extern lv_obj_t * ui_LabelCustom;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

