// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#ifndef _CROWPANEL_MARLIN_HMI_UI_H
#define _CROWPANEL_MARLIN_HMI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_ScreenMain.h"
#include "ui_ScreenPrintStatus.h"
#include "ui_ScreenJog.h"
#include "ui_ScreenTMC.h"
#include "ui_ScreenFilament.h"
#include "ui_ScreenFiles.h"
#include "ui_ScreenSettings.h"
#include "ui_ScreenAbout.h"
#include "ui_ScreenTemperature.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_247885993);    // assets/icons8-direction-50.png
LV_IMG_DECLARE(ui_img_1465085387);    // assets/bed, plate, bed plate, heated icon.png
LV_IMG_DECLARE(ui_img_1237989568);    // assets/nozzle diameter, nozzle size, layer, thickness, layer thickness icon.png
LV_IMG_DECLARE(ui_img_1439640658);    // assets/stl-format-file-format-file-format-stl-icon.png
LV_IMG_DECLARE(ui_img_377306522);    // assets/auto, automatic levelling, leveling, auto level, bed icon.png
LV_IMG_DECLARE(ui_img_1312856521);    // assets/icons8-resize-vertical-50.png
LV_IMG_DECLARE(ui_img_564518316);    // assets/icons8-3d-printer-100.png
LV_IMG_DECLARE(ui_img_1988419691);    // assets/warning-hot-bed-icon-small.png
LV_IMG_DECLARE(
    ui_img_2072515320);    // assets/nozzle-diameter-nozzle-size-layer-thickness-layer-thickness-icon-small.png
LV_IMG_DECLARE(ui_img_653996564);    // assets/stepper-motor-icon.png
LV_IMG_DECLARE(ui_img_1038364564);    // assets/material, plastics materials, abs, pla, print icon.png
LV_IMG_DECLARE(ui_img_722526726);    // assets/machine-cog-radio-settings-gear-office-setting-settings-icon.png
LV_IMG_DECLARE(ui_img_398448242);    // assets/plug-in-2-icon.png
LV_IMG_DECLARE(ui_img_1983858668);    // assets/pause-icon (2).png
LV_IMG_DECLARE(
    ui_img_931356233);    // assets/transportation-stop-sign-octagon-sign-travel-traffic-sign-stop-pause-traffic-end-transport-player-halt-audio-play-icon (1).png
LV_IMG_DECLARE(ui_img_2098359223);    // assets/ascending-arrow-up-up-rise-arrow-upload-increase-ascend-icon.png
LV_IMG_DECLARE(ui_img_1302380444);    // assets/ascending-arrow-down.png
LV_IMG_DECLARE(ui_img_858268281);    // assets/ascending-arrow-left.png
LV_IMG_DECLARE(ui_img_1272866020);    // assets/ascending-arrow-right.png
LV_IMG_DECLARE(
    ui_img_565287032);    // assets/summer-bright-daytime-warm-weather-source-sun-hot-light-source-idea-brightness-morning-sunny-daylight-light-day-icon.png
LV_IMG_DECLARE(ui_img_681280759);    // assets/speaker-2-icon.png
LV_IMG_DECLARE(ui_img_461506120);    // assets/timer-icon.png
LV_IMG_DECLARE(ui_img_1099881434);    // assets/fdm-printer-ffm-delta-fused-filament-printer-icon (1).png
LV_IMG_DECLARE(
    ui_img_355628395);    // assets/nozzle temperature, nozzle, print temperature, print, extruder temperature, temp icon.png
LV_IMG_DECLARE(ui_img_426815153);    // assets/warning-hot-bed-icon-small2.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
