// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_eventBtnShutDown(lv_event_t * e);
void ui_eventArcOverall(lv_event_t * e);
void ui_eventBarHotend(lv_event_t * e);
void ui_eventBarBed(lv_event_t * e);
void ui_eventBtnPauseResume(lv_event_t * e);
void ui_eventBtnStop(lv_event_t * e);
void ui_eventSliderSpeed(lv_event_t * e);
void ui_eventBtnYPlus(lv_event_t * e);
void ui_eventBtnYMinus(lv_event_t * e);
void ui_eventBtnXMinus(lv_event_t * e);
void ui_eventBtnXPlus(lv_event_t * e);
void ui_eventBtnZPlus(lv_event_t * e);
void ui_eventBtnZMinus(lv_event_t * e);
void ui_eventBtnHomeAll(lv_event_t * e);
void ui_eventDropdownStep(lv_event_t * e);
void ui_eventSliderBabyZ(lv_event_t * e);
void ui_eventBtnAutoZAlign(lv_event_t * e);
void ui_eventBtnAutoBedLevel(lv_event_t * e);
void ui_eventBtnLoadMesh(lv_event_t * e);
void ui_eventBtnSaveMesh(lv_event_t * e);
void ui_eventBtnXHome(lv_event_t * e);
void ui_eventBtnYHome(lv_event_t * e);
void ui_eventBtnZHome(lv_event_t * e);
void ui_eventSliderXCurrent(lv_event_t * e);
void ui_eventDropdownXMicrosteps(lv_event_t * e);
void ui_eventSliderXHybrid(lv_event_t * e);
void ui_eventSliderXSGT(lv_event_t * e);
void ui_eventDropdownXMode(lv_event_t * e);
void ui_eventBtnApplyAllTMC(lv_event_t * e);
void ui_eventBtnXSaveEEPROM(lv_event_t * e);
void ui_eventBtnXRefresh(lv_event_t * e);
void ui_eventBtnM122Debug(lv_event_t * e);
void ui_eventSliderYCurrent(lv_event_t * e);
void ui_eventDropdownYMicrosteps(lv_event_t * e);
void ui_eventSliderYHybrid(lv_event_t * e);
void ui_eventSliderYSGT(lv_event_t * e);
void ui_eventSliderYSGTValue(lv_event_t * e);
void ui_eventDropdownYMode(lv_event_t * e);
void ui_eventBtnApplyAllY(lv_event_t * e);
void ui_eventBtnSaveEEPROMY(lv_event_t * e);
void ui_eventBtnRefreshY(lv_event_t * e);
void ui_eventBtnM122DebugY(lv_event_t * e);
void ui_eventSliderZ1Current(lv_event_t * e);
void ui_eventDropdownZ1Microsteps(lv_event_t * e);
void ui_eventSliderZ1Hybrid(lv_event_t * e);
void ui_eventSliderZ1SGT(lv_event_t * e);
void ui_eventDropdownZ1Mode(lv_event_t * e);
void ui_eventBtnApplyAllZ1(lv_event_t * e);
void ui_eventBtnSaveEEPROMZ1(lv_event_t * e);
void ui_eventBtnRefreshZ1(lv_event_t * e);
void ui_eventBtnM122DebugZ1(lv_event_t * e);
void ui_eventSliderZ2Current(lv_event_t * e);
void ui_event(lv_event_t * e);
void ui_eventSliderZ2Hybrid(lv_event_t * e);
void ui_eventSliderZ2SGT(lv_event_t * e);
void ui_eventDropdownZ2Mode(lv_event_t * e);
void ui_eventBtnApplyAllTMC_Z2(lv_event_t * e);
void ui_eventBtnSaveEEPROMZ2(lv_event_t * e);
void ui_eventBtnRefreshZ2(lv_event_t * e);
void ui_eventBtnM122DebugZ2(lv_event_t * e);
void ui_eventSliderZ3Current(lv_event_t * e);
void ui_eventDropdownZ3Microsteps(lv_event_t * e);
void ui_eventSliderZ3Hybrid(lv_event_t * e);
void ui_eventSliderZ3SGT(lv_event_t * e);
void ui_eventDropdownZ3Mode(lv_event_t * e);
void ui_eventBtnApplyAllZ3(lv_event_t * e);
void ui_eventBtnSaveEEPROMZ3(lv_event_t * e);
void ui_eventBtnRefreshZ3(lv_event_t * e);
void ui_eventBtnM122DebugZ3(lv_event_t * e);
void ui_eventSliderE0Current(lv_event_t * e);
void ui_eventDropdownE0Microsteps(lv_event_t * e);
void ui_eventSliderE0Hybrid(lv_event_t * e);
void ui_eventSliderE0SGT(lv_event_t * e);
void ui_eventDropdownE0Mode(lv_event_t * e);
void ui_eventBtnApplyAllE0(lv_event_t * e);
void eu_eventBtnSaveEEPROME0(lv_event_t * e);
void ui_eventBtnRefreshE0(lv_event_t * e);
void ui_eventBtnM122DebugE0(lv_event_t * e);
void ui_eventSwitchRunout(lv_event_t * e);
void ui_eventBtnRunoutTest(lv_event_t * e);
void ui_eventSwitchJam(lv_event_t * e);
void ui_eventBtnJamTest(lv_event_t * e);
void ui_eventSliderJamSensitivity(lv_event_t * e);
void ui_eventBtnApplySensors(lv_event_t * e);
void ui_eventBtnSaveSensors(lv_event_t * e);
void ui_eventBtnRefreshSensors(lv_event_t * e);
void ui_eventBtnRefresh(lv_event_t * e);
void ui_eventFileItemClicked(lv_event_t * e);
void ui_eventBtnPrintSelected(lv_event_t * e);
void ui_eventBtnDeleteFile(lv_event_t * e);
void ui_eventBtnUpFolderUP(lv_event_t * e);
void ui_eventBtnSort(lv_event_t * e);
void ui_eventBtnUpFolderDown(lv_event_t * e);
void ui_eventTxtXStepsClicked(lv_event_t * e);
void ui_eventTxtYStepsClicked(lv_event_t * e);
void ui_eventTxtZStepsClicked(lv_event_t * e);
void ui_eventTxtE0StepsClicked(lv_event_t * e);
void ui_eventBtnApplySteps(lv_event_t * e);
void ui_eventTxtFilDiaClicked(lv_event_t * e);
void ui_eventSliderFlow(lv_event_t * e);
void ui_eventSliderBrightness(lv_event_t * e);
void ui_eventSwitchSound(lv_event_t * e);
void ui_eventSwitchScreenTimeout(lv_event_t * e);
void ui_eventSwitchWiFi(lv_event_t * e);
void ui_eventTxtSSIDClicked(lv_event_t * e);
void ui_eventTxtPasswordClicked(lv_event_t * e);
void ui_eventBtnSaveAll(lv_event_t * e);
void ui_eventBtnReboot(lv_event_t * e);
void ui_eventNumPadDigit(lv_event_t * e);
void ui_eventNumPadEnter(lv_event_t * e);
void ui_eventNumPadBackspace(lv_event_t * e);
void ui_eventNumPadClear(lv_event_t * e);
void ui_eventNumPadCancel(lv_event_t * e);
void ui_eventBtnCheckUpdate(lv_event_t * e);
void ui_eventBtnShowLogs(lv_event_t * e);
void ui_eventBtnFactoryReset(lv_event_t * e);
void ui_eventArcHotend(lv_event_t * e);
void ui_eventArcBed(lv_event_t * e);
void ui_eventBtnPLA(lv_event_t * e);
void ui_eventBtnPETG(lv_event_t * e);
void ui_eventBtnABS(lv_event_t * e);
void ui_eventBtnCustom(lv_event_t * e);
void ui_eventBtnPIDHotend(lv_event_t * e);
void ui_eventBtnSavePID(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
