// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#ifndef UI_SCREENFILES_H
#define UI_SCREENFILES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenFiles
extern void ui_ScreenFiles_screen_init(void);
extern void ui_ScreenFiles_screen_destroy(void);
extern lv_obj_t * ui_ScreenFiles;
extern lv_obj_t * ui_Panel4;
extern void ui_event_BtnBack4(lv_event_t * e);
extern lv_obj_t * ui_BtnBack4;
extern lv_obj_t * ui_LabelBack4;
extern lv_obj_t * ui_LabelTitle1;
extern void ui_event_BtnRefresh(lv_event_t * e);
extern lv_obj_t * ui_BtnRefresh;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_LabelFreeSpace;
extern lv_obj_t * ui_PanelFileList;
extern void ui_event_BtnFileItem(lv_event_t * e);
extern lv_obj_t * ui_BtnFileItem;
extern lv_obj_t * ui_LabelFileItem;
extern lv_obj_t * ui_LabelSelectedFile;
extern lv_obj_t * ui_LabelFileSize;
extern lv_obj_t * ui_LabelLayerCount;
extern void ui_event_BtnPrintSelected(lv_event_t * e);
extern lv_obj_t * ui_BtnPrintSelected;
extern lv_obj_t * ui_LabelPrintSelected;
extern void ui_event_BtnDeleteFile(lv_event_t * e);
extern lv_obj_t * ui_BtnDeleteFile;
extern lv_obj_t * ui_LabelDelete;
extern void ui_event_BtnUpFolderUP(lv_event_t * e);
extern lv_obj_t * ui_BtnUpFolderUP;
extern void ui_event_BtnSort(lv_event_t * e);
extern lv_obj_t * ui_BtnSort;
extern lv_obj_t * ui_LabelUP;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_LabelSort;
extern void ui_event_BtnUpFolderDown(lv_event_t * e);
extern lv_obj_t * ui_BtnUpFolderDown;
extern lv_obj_t * ui_LabelDown;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_LabelCurrevtFolder;
extern lv_obj_t * ui_Label20;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ScreenFiles;
extern lv_obj_t * ui_BtnBack4;
extern lv_obj_t * ui_LabelBack4;
extern lv_obj_t * ui_LabelTitle1;
extern lv_obj_t * ui_BtnRefresh;
extern lv_obj_t * ui_LabelFreeSpace;
extern lv_obj_t * ui_PanelFileList;
extern lv_obj_t * ui_BtnFileItem;
extern lv_obj_t * ui_LabelFileItem;
extern lv_obj_t * ui_LabelSelectedFile;
extern lv_obj_t * ui_LabelFileSize;
extern lv_obj_t * ui_LabelLayerCount;
extern lv_obj_t * ui_BtnPrintSelected;
extern lv_obj_t * ui_LabelPrintSelected;
extern lv_obj_t * ui_BtnDeleteFile;
extern lv_obj_t * ui_LabelDelete;
extern lv_obj_t * ui_BtnUpFolderUP;
extern lv_obj_t * ui_BtnSort;
extern lv_obj_t * ui_LabelUP;
extern lv_obj_t * ui_LabelSort;
extern lv_obj_t * ui_BtnUpFolderDown;
extern lv_obj_t * ui_LabelDown;
extern lv_obj_t * ui_LabelCurrevtFolder;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

