// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#ifndef UI_SCREENJOG_H
#define UI_SCREENJOG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenJog
extern void ui_ScreenJog_screen_init(void);
extern void ui_ScreenJog_screen_destroy(void);
extern lv_obj_t * ui_ScreenJog;
extern lv_obj_t * ui_PanelTopNav3;
extern lv_obj_t * ui_LabelScreenTitle;
extern void ui_event_BtnBack1(lv_event_t * e);
extern lv_obj_t * ui_BtnBack1;
extern lv_obj_t * ui_LabelBack1;
extern void ui_event_BtnYPlus(lv_event_t * e);
extern lv_obj_t * ui_BtnYPlus;
extern lv_obj_t * ui_LabelYPlus;
extern void ui_event_BtnYMinus(lv_event_t * e);
extern lv_obj_t * ui_BtnYMinus;
extern lv_obj_t * ui_LabelYMinus;
extern void ui_event_BtnXMinus(lv_event_t * e);
extern lv_obj_t * ui_BtnXMinus;
extern lv_obj_t * ui_LabelXMinus;
extern void ui_event_BtnXPlus(lv_event_t * e);
extern lv_obj_t * ui_BtnXPlus;
extern lv_obj_t * ui_LabelXPus;
extern void ui_event_BtnZPlus(lv_event_t * e);
extern lv_obj_t * ui_BtnZPlus;
extern lv_obj_t * ui_LabelZPlus;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern void ui_event_BtnZMinus(lv_event_t * e);
extern lv_obj_t * ui_BtnZMinus;
extern lv_obj_t * ui_LabelZMinus;
extern lv_obj_t * ui_Image16;
extern void ui_event_BtnHomeAll(lv_event_t * e);
extern lv_obj_t * ui_BtnHomeAll;
extern lv_obj_t * ui_LabelHOMEALL;
extern void ui_event_DropdownStep(lv_event_t * e);
extern lv_obj_t * ui_DropdownStep;
extern lv_obj_t * ui_LabelBabyZ;
extern void ui_event_SliderBabyZ(lv_event_t * e);
extern lv_obj_t * ui_SliderBabyZ;
extern lv_obj_t * ui_LabelPosX;
extern lv_obj_t * ui_LabelPosY;
extern lv_obj_t * ui_LabelPosZ;
extern void ui_event_BtnAutoZAlign(lv_event_t * e);
extern lv_obj_t * ui_BtnAutoZAlign;
extern lv_obj_t * ui_LabelAutoZAlign;
extern void ui_event_BtnAutoBedLevel(lv_event_t * e);
extern lv_obj_t * ui_BtnAutoBedLevel;
extern lv_obj_t * ui_LabelAutoBedLevel;
extern void ui_event_BtnLoadMesh(lv_event_t * e);
extern lv_obj_t * ui_BtnLoadMesh;
extern lv_obj_t * ui_LabelLoadMesh;
extern void ui_event_BtnSaveMesh(lv_event_t * e);
extern lv_obj_t * ui_BtnSaveMesh;
extern lv_obj_t * ui_LabelSaveMesh;
extern void ui_event_BtnXHome(lv_event_t * e);
extern lv_obj_t * ui_BtnXHome;
extern void ui_event_BtnYHome(lv_event_t * e);
extern lv_obj_t * ui_BtnYHome;
extern void ui_event_BtnZHome(lv_event_t * e);
extern lv_obj_t * ui_BtnZHome;
extern lv_obj_t * ui_LabelHomeZ;
extern lv_obj_t * ui_LabeelHomeY;
extern lv_obj_t * ui_LabelHomeX;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ScreenJog;
extern lv_obj_t * ui_uiPanelTopNav;
extern lv_obj_t * ui_LabelScreenTitle;
extern lv_obj_t * ui_BtnBack1;
extern lv_obj_t * ui_LabelBack1;
extern lv_obj_t * ui_BtnYPlus;
extern lv_obj_t * ui_YPlus;
extern lv_obj_t * ui_BtnYMinus;
extern lv_obj_t * ui_LabelYMinus;
extern lv_obj_t * ui_BtnXMinus;
extern lv_obj_t * ui_LabelXMinus;
extern lv_obj_t * ui_BtnXPlus;
extern lv_obj_t * ui_XPus;
extern lv_obj_t * ui_BtnZPlus;
extern lv_obj_t * ui_LabelZPlus;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_BtnZMinus;
extern lv_obj_t * ui_LabelZMinus;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_BtnHomeAll;
extern lv_obj_t * ui_LabelHOMEALL;
extern lv_obj_t * ui_DropdownStep;
extern lv_obj_t * ui_LabelBabyZ;
extern lv_obj_t * ui_SliderBabyZ;
extern lv_obj_t * ui_LabelPosX;
extern lv_obj_t * ui_LabelPosY;
extern lv_obj_t * ui_LabelPosZ;
extern lv_obj_t * ui_BtnAutoZAlign;
extern lv_obj_t * ui_LabelAutoZAlign;
extern lv_obj_t * ui_BtnAutoBedLevel;
extern lv_obj_t * ui_LabelAutoBedLevel;
extern lv_obj_t * ui_BtnLoadMesh;
extern lv_obj_t * ui_LabelLoadMesh;
extern lv_obj_t * ui_BtnSaveMesh;
extern lv_obj_t * ui_LabelSaveMesh;
extern lv_obj_t * ui_BtnXHome;
extern lv_obj_t * ui_BtnYHome;
extern lv_obj_t * ui_BtnZHome;
extern lv_obj_t * ui_LabelHomeZ;
extern lv_obj_t * ui_LabeelHomeY;
extern lv_obj_t * ui_LabelHomeX;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

