// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#include "ui.h"

lv_obj_t * ui_LabelShutDown;
lv_obj_t * ui_BtnShutDown;
lv_obj_t * ui_LabelSettings;
lv_obj_t * ui_LabelFilament;
lv_obj_t * ui_LabelTMCDrivers;
lv_obj_t * ui_BtnSettings;
lv_obj_t * ui_BtnFilament;
lv_obj_t * ui_BtnTMC;
lv_obj_t * ui_LabelTemperature;
lv_obj_t * ui_BtnTemperature;
lv_obj_t * ui_LabelFiles;
lv_obj_t * ui_BtnFiles;
lv_obj_t * ui_LabelJogLevel;
lv_obj_t * ui_BtnJog;
lv_obj_t * ui_LabelPrintStatus;
lv_obj_t * ui_BtnPrintStatus;
lv_obj_t * ui_LabelFilamentMain;
lv_obj_t * ui_LabelBedSmall;
lv_obj_t * ui_LabelHotendSmall;
lv_obj_t * ui_LabelPrinterName;
lv_obj_t * ui_uiPanelTopBar;
lv_obj_t * ui_ScreenMain;
lv_obj_t * ui_ScreenMain = NULL;
lv_obj_t * ui_PanelTopNav = NULL;
lv_obj_t * ui_LabelPrinterName = NULL;
lv_obj_t * ui_LabelHotendSmall = NULL;
lv_obj_t * ui_LabelBedSmall = NULL;
lv_obj_t * ui_LabelFilamentMain = NULL;
lv_obj_t * ui_BtnPrintStatus = NULL;
lv_obj_t * ui_LabelPrintStatus = NULL;
lv_obj_t * ui_BtnJog = NULL;
lv_obj_t * ui_LabelJogLevel = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_BtnFiles = NULL;
lv_obj_t * ui_LabelFiles = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_BtnTemperature = NULL;
lv_obj_t * ui_LabelTemperature = NULL;
lv_obj_t * ui_Image22 = NULL;
lv_obj_t * ui_Image24 = NULL;
lv_obj_t * ui_BtnTMC = NULL;
lv_obj_t * ui_BtnFilament = NULL;
lv_obj_t * ui_BtnSettings = NULL;
lv_obj_t * ui_LabelTMCDrivers = NULL;
lv_obj_t * ui_Image25 = NULL;
lv_obj_t * ui_LabelFilament = NULL;
lv_obj_t * ui_Image26 = NULL;
lv_obj_t * ui_LabelSettings = NULL;
lv_obj_t * ui_Image28 = NULL;
lv_obj_t * ui_BtnShutDown = NULL;
lv_obj_t * ui_LabelShutDown = NULL;
lv_obj_t * ui_Image18 = NULL;
// event funtions
void ui_event_BtnPrintStatus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenPrintStatus, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenPrintStatus_screen_init);
    }
}

void ui_event_BtnJog(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenJog, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenJog_screen_init);
    }
}

void ui_event_BtnFiles(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenFiles, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenFiles_screen_init);
    }
}

void ui_event_BtnTemperature(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenTemperature, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenTemperature_screen_init);
    }
}

void ui_event_BtnTMC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenTMC, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenTMC_screen_init);
    }
}

void ui_event_BtnFilament(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenFilament, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenFilament_screen_init);
    }
}

void ui_event_BtnSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenSettings_screen_init);
    }
}

void ui_event_BtnShutDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnShutDown(e);
    }
}

// build funtions

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMain, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ScreenMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ScreenMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScreenMain, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScreenMain, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ScreenMain, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenMain, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTopNav = lv_obj_create(ui_ScreenMain);
    lv_obj_set_width(ui_PanelTopNav, 800);
    lv_obj_set_height(ui_PanelTopNav, 70);
    lv_obj_clear_flag(ui_PanelTopNav, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTopNav, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTopNav, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTopNav, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPrinterName = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelPrinterName, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_LabelPrinterName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPrinterName, 25);
    lv_obj_set_y(ui_LabelPrinterName, 24);
    lv_label_set_text(ui_LabelPrinterName, "Mega 3D Printer");
    lv_obj_set_style_text_color(ui_LabelPrinterName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPrinterName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPrinterName, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPrinterName, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHotendSmall = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelHotendSmall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHotendSmall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHotendSmall, 380);
    lv_obj_set_y(ui_LabelHotendSmall, 18);
    lv_label_set_text(ui_LabelHotendSmall, "205°C\n");
    lv_obj_set_style_text_color(ui_LabelHotendSmall, lv_color_hex(0xFF8800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHotendSmall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHotendSmall, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBedSmall = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelBedSmall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBedSmall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBedSmall, 520);
    lv_obj_set_y(ui_LabelBedSmall, 18);
    lv_label_set_text(ui_LabelBedSmall, "60°C");
    lv_obj_set_style_text_color(ui_LabelBedSmall, lv_color_hex(0x4488FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBedSmall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBedSmall, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFilamentMain = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelFilamentMain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFilamentMain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFilamentMain, 650);
    lv_obj_set_y(ui_LabelFilamentMain, 20);
    lv_label_set_text(ui_LabelFilamentMain, "Filament: OK\n");
    lv_obj_set_style_text_color(ui_LabelFilamentMain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFilamentMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelFilamentMain, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFilamentMain, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPrintStatus = lv_btn_create(ui_ScreenMain);
    lv_obj_set_width(ui_BtnPrintStatus, 220);
    lv_obj_set_height(ui_BtnPrintStatus, 140);
    lv_obj_set_x(ui_BtnPrintStatus, 40);
    lv_obj_set_y(ui_BtnPrintStatus, 100);
    lv_obj_add_flag(ui_BtnPrintStatus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPrintStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnPrintStatus, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnPrintStatus, lv_color_hex(0x00AAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPrintStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnPrintStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnPrintStatus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnPrintStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnPrintStatus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnPrintStatus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BtnPrintStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnPrintStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnPrintStatus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnPrintStatus, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPrintStatus = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelPrintStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPrintStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPrintStatus, -249);
    lv_obj_set_y(ui_LabelPrintStatus, -128);
    lv_obj_set_align(ui_LabelPrintStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPrintStatus, "Print Status");
    lv_obj_set_style_text_font(ui_LabelPrintStatus, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnJog = lv_btn_create(ui_ScreenMain);
    lv_obj_set_width(ui_BtnJog, 220);
    lv_obj_set_height(ui_BtnJog, 140);
    lv_obj_set_x(ui_BtnJog, 290);
    lv_obj_set_y(ui_BtnJog, 100);
    lv_obj_add_flag(ui_BtnJog, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnJog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnJog, lv_color_hex(0x00FFAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnJog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnJog, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnJog, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BtnJog, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnJog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelJogLevel = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelJogLevel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelJogLevel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelJogLevel, -3);
    lv_obj_set_y(ui_LabelJogLevel, -126);
    lv_obj_set_align(ui_LabelJogLevel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelJogLevel, "Jog & Level");
    lv_obj_set_style_text_font(ui_LabelJogLevel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image3, &ui_img_247885993);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image3, -55);
    lv_obj_set_y(ui_Image3, -56);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnFiles = lv_btn_create(ui_ScreenMain);
    lv_obj_set_width(ui_BtnFiles, 220);
    lv_obj_set_height(ui_BtnFiles, 140);
    lv_obj_set_x(ui_BtnFiles, 540);
    lv_obj_set_y(ui_BtnFiles, 100);
    lv_obj_add_flag(ui_BtnFiles, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnFiles, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnFiles, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnFiles, lv_color_hex(0xFFAA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnFiles, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnFiles, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnFiles, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnFiles, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnFiles, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnFiles, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BtnFiles, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnFiles, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFiles = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelFiles, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFiles, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFiles, 249);
    lv_obj_set_y(ui_LabelFiles, -112);
    lv_obj_set_align(ui_LabelFiles, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFiles, "Files\n");
    lv_obj_set_style_text_font(ui_LabelFiles, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image9, &ui_img_1465085387);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image9, 86);
    lv_obj_set_y(ui_Image9, -214);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image10, &ui_img_1237989568);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image10, -62);
    lv_obj_set_y(ui_Image10, -211);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image13, &ui_img_1439640658);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image13, 248);
    lv_obj_set_y(ui_Image13, -53);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image14, &ui_img_377306522);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image14, 53);
    lv_obj_set_y(ui_Image14, -59);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image15, &ui_img_1312856521);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image15, -1);
    lv_obj_set_y(ui_Image15, -56);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image20, &ui_img_564518316);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image20, -247);
    lv_obj_set_y(ui_Image20, -57);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnTemperature = lv_btn_create(ui_ScreenMain);
    lv_obj_set_width(ui_BtnTemperature, 220);
    lv_obj_set_height(ui_BtnTemperature, 100);
    lv_obj_set_x(ui_BtnTemperature, 40);
    lv_obj_set_y(ui_BtnTemperature, 260);
    lv_obj_add_flag(ui_BtnTemperature, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnTemperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnTemperature, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnTemperature, lv_color_hex(0xCE2727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnTemperature, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnTemperature, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnTemperature, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BtnTemperature, lv_color_hex(0xFCFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemperature = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelTemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemperature, -260);
    lv_obj_set_y(ui_LabelTemperature, 38);
    lv_obj_set_align(ui_LabelTemperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemperature, "Temperature");

    ui_Image22 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image22, &ui_img_1988419691);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image22, -200);
    lv_obj_set_y(ui_Image22, 81);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image24 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image24, &ui_img_2072515320);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image24, -305);
    lv_obj_set_y(ui_Image24, 82);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnTMC = lv_btn_create(ui_ScreenMain);
    lv_obj_set_width(ui_BtnTMC, 220);
    lv_obj_set_height(ui_BtnTMC, 100);
    lv_obj_set_x(ui_BtnTMC, 290);
    lv_obj_set_y(ui_BtnTMC, 260);
    lv_obj_add_flag(ui_BtnTMC, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnTMC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnTMC, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnTMC, lv_color_hex(0x514F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnTMC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnTMC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnTMC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnTMC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnTMC, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnTMC, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnFilament = lv_btn_create(ui_ScreenMain);
    lv_obj_set_width(ui_BtnFilament, 220);
    lv_obj_set_height(ui_BtnFilament, 100);
    lv_obj_set_x(ui_BtnFilament, 540);
    lv_obj_set_y(ui_BtnFilament, 260);
    lv_obj_add_flag(ui_BtnFilament, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnFilament, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnFilament, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnFilament, lv_color_hex(0xD1DC1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnFilament, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnFilament, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnFilament, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnFilament, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnFilament, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BtnFilament, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnFilament, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSettings = lv_btn_create(ui_ScreenMain);
    lv_obj_set_width(ui_BtnSettings, 220);
    lv_obj_set_height(ui_BtnSettings, 80);
    lv_obj_set_x(ui_BtnSettings, 40);
    lv_obj_set_y(ui_BtnSettings, 385);
    lv_obj_add_flag(ui_BtnSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnSettings, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnSettings, lv_color_hex(0x07DBED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnSettings, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnSettings, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BtnSettings, lv_color_hex(0xFEFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTMCDrivers = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelTMCDrivers, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTMCDrivers, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTMCDrivers, -1);
    lv_obj_set_y(ui_LabelTMCDrivers, 38);
    lv_obj_set_align(ui_LabelTMCDrivers, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTMCDrivers, "TMC Drivers");
    lv_obj_set_style_text_font(ui_LabelTMCDrivers, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image25 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image25, &ui_img_653996564);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image25, -8);
    lv_obj_set_y(ui_Image25, 81);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelFilament = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelFilament, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFilament, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFilament, 246);
    lv_obj_set_y(ui_LabelFilament, 35);
    lv_obj_set_align(ui_LabelFilament, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFilament, "Filament");
    lv_obj_set_style_text_font(ui_LabelFilament, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image26 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image26, &ui_img_1038364564);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image26, 244);
    lv_obj_set_y(ui_Image26, 82);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSettings = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSettings, 108);
    lv_obj_set_y(ui_LabelSettings, 391);
    lv_label_set_text(ui_LabelSettings, "Settings\n");
    lv_obj_set_style_text_font(ui_LabelSettings, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image28 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image28, &ui_img_722526726);
    lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);   /// 57
    lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_Image28, -252);
    lv_obj_set_y(ui_Image28, 197);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnShutDown = lv_btn_create(ui_ScreenMain);
    lv_obj_set_width(ui_BtnShutDown, 220);
    lv_obj_set_height(ui_BtnShutDown, 80);
    lv_obj_set_x(ui_BtnShutDown, 540);
    lv_obj_set_y(ui_BtnShutDown, 385);
    lv_obj_add_flag(ui_BtnShutDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnShutDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnShutDown, lv_color_hex(0xCD2420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnShutDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnShutDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnShutDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnShutDown, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnShutDown, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelShutDown = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelShutDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelShutDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelShutDown, 248);
    lv_obj_set_y(ui_LabelShutDown, 159);
    lv_obj_set_align(ui_LabelShutDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelShutDown, "Shut Down");
    lv_obj_set_style_text_color(ui_LabelShutDown, lv_color_hex(0xFCFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelShutDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelShutDown, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelShutDown, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image18 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image18, &ui_img_398448242);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image18, 240);
    lv_obj_set_y(ui_Image18, 196);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BtnPrintStatus, ui_event_BtnPrintStatus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnJog, ui_event_BtnJog, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnFiles, ui_event_BtnFiles, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnTemperature, ui_event_BtnTemperature, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnTMC, ui_event_BtnTMC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnFilament, ui_event_BtnFilament, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSettings, ui_event_BtnSettings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnShutDown, ui_event_BtnShutDown, LV_EVENT_ALL, NULL);
    ui_ScreenMain = ui_ScreenMain;
    ui_uiPanelTopBar = ui_PanelTopNav;
    ui_LabelPrinterName = ui_LabelPrinterName;
    ui_LabelHotendSmall = ui_LabelHotendSmall;
    ui_LabelBedSmall = ui_LabelBedSmall;
    ui_LabelFilamentMain = ui_LabelFilamentMain;
    ui_BtnPrintStatus = ui_BtnPrintStatus;
    ui_LabelPrintStatus = ui_LabelPrintStatus;
    ui_BtnJog = ui_BtnJog;
    ui_LabelJogLevel = ui_LabelJogLevel;
    ui_BtnFiles = ui_BtnFiles;
    ui_LabelFiles = ui_LabelFiles;
    ui_BtnTemperature = ui_BtnTemperature;
    ui_LabelTemperature = ui_LabelTemperature;
    ui_BtnTMC = ui_BtnTMC;
    ui_BtnFilament = ui_BtnFilament;
    ui_BtnSettings = ui_BtnSettings;
    ui_LabelTMCDrivers = ui_LabelTMCDrivers;
    ui_LabelFilament = ui_LabelFilament;
    ui_LabelSettings = ui_LabelSettings;
    ui_BtnShutDown = ui_BtnShutDown;
    ui_LabelShutDown = ui_LabelShutDown;

}

void ui_ScreenMain_screen_destroy(void)
{
    if(ui_ScreenMain) lv_obj_del(ui_ScreenMain);

    // NULL screen variables
    ui_ScreenMain = NULL;
    ui_ScreenMain = NULL;
    ui_uiPanelTopBar = NULL;
    ui_PanelTopNav = NULL;
    ui_LabelPrinterName = NULL;
    ui_LabelPrinterName = NULL;
    ui_LabelHotendSmall = NULL;
    ui_LabelHotendSmall = NULL;
    ui_LabelBedSmall = NULL;
    ui_LabelBedSmall = NULL;
    ui_LabelFilamentMain = NULL;
    ui_LabelFilamentMain = NULL;
    ui_BtnPrintStatus = NULL;
    ui_BtnPrintStatus = NULL;
    ui_LabelPrintStatus = NULL;
    ui_LabelPrintStatus = NULL;
    ui_BtnJog = NULL;
    ui_BtnJog = NULL;
    ui_LabelJogLevel = NULL;
    ui_LabelJogLevel = NULL;
    ui_Image3 = NULL;
    ui_BtnFiles = NULL;
    ui_BtnFiles = NULL;
    ui_LabelFiles = NULL;
    ui_LabelFiles = NULL;
    ui_Image9 = NULL;
    ui_Image10 = NULL;
    ui_Image13 = NULL;
    ui_Image14 = NULL;
    ui_Image15 = NULL;
    ui_Image20 = NULL;
    ui_BtnTemperature = NULL;
    ui_BtnTemperature = NULL;
    ui_LabelTemperature = NULL;
    ui_LabelTemperature = NULL;
    ui_Image22 = NULL;
    ui_Image24 = NULL;
    ui_BtnTMC = NULL;
    ui_BtnTMC = NULL;
    ui_BtnFilament = NULL;
    ui_BtnFilament = NULL;
    ui_BtnSettings = NULL;
    ui_BtnSettings = NULL;
    ui_LabelTMCDrivers = NULL;
    ui_LabelTMCDrivers = NULL;
    ui_Image25 = NULL;
    ui_LabelFilament = NULL;
    ui_LabelFilament = NULL;
    ui_Image26 = NULL;
    ui_LabelSettings = NULL;
    ui_LabelSettings = NULL;
    ui_Image28 = NULL;
    ui_BtnShutDown = NULL;
    ui_BtnShutDown = NULL;
    ui_LabelShutDown = NULL;
    ui_LabelShutDown = NULL;
    ui_Image18 = NULL;

}
