// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#ifndef UI_SCREENABOUT_H
#define UI_SCREENABOUT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenAbout
extern void ui_ScreenAbout_screen_init(void);
extern void ui_ScreenAbout_screen_destroy(void);
extern lv_obj_t * ui_ScreenAbout;
extern lv_obj_t * ui_Panel7;
extern void ui_event_BtnBack6(lv_event_t * e);
extern lv_obj_t * ui_BtnBack6;
extern void ui_event_LabelBack6(lv_event_t * e);
extern lv_obj_t * ui_LabelBack6;
extern lv_obj_t * ui_LabelTitle4;
extern lv_obj_t * ui_PanelSystem1;
extern lv_obj_t * ui_LabelSysTitle;
extern lv_obj_t * ui_LabelFirmware;
extern lv_obj_t * ui_LabelHMI;
extern lv_obj_t * ui_LabelBoard;
extern lv_obj_t * ui_PanelHardware;
extern lv_obj_t * ui_PanelSoftware;
extern lv_obj_t * ui_LabelHWTitle;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_LabelSWTitle;
extern lv_obj_t * ui_LabelVersion;
extern lv_obj_t * ui_LabelLVGL;
extern lv_obj_t * ui_LabelAuthor;
extern lv_obj_t * ui_LabelHotend1;
extern lv_obj_t * ui_LabelBuildDate;
extern lv_obj_t * ui_Image29;
extern void ui_event_BtnCheckUpdate(lv_event_t * e);
extern lv_obj_t * ui_BtnCheckUpdate;
extern lv_obj_t * ui_LabelBtnCheckUpdate;
extern void ui_event_BtnViewLogs(lv_event_t * e);
extern lv_obj_t * ui_BtnViewLogs;
extern lv_obj_t * ui_LabelBtnViewLogs;
extern void ui_event_BtnFactoryReset1(lv_event_t * e);
extern lv_obj_t * ui_BtnFactoryReset1;
extern lv_obj_t * ui_LabelFactoryReset1;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ScreenAbout;
extern lv_obj_t * ui_BtnBack6;
extern lv_obj_t * ui_LabelBack6;
extern lv_obj_t * ui_PanelSystem1;
extern lv_obj_t * ui_LabelSysTitle;
extern lv_obj_t * ui_LabelFirmware;
extern lv_obj_t * ui_LabelBoard;
extern lv_obj_t * ui_PanelHardware;
extern lv_obj_t * ui_PanelSoftware;
extern lv_obj_t * ui_LabelSWTitle;
extern lv_obj_t * ui_LabelVersion;
extern lv_obj_t * ui_LabelLVGL;
extern lv_obj_t * ui_LabelBuildDate;
extern lv_obj_t * ui_LabelHotend1;
extern lv_obj_t * ui_LabelBuildDate;
extern lv_obj_t * ui_BtnCheckUpdate;
extern lv_obj_t * ui_LabelBtnCheckUpdate;
extern lv_obj_t * ui_BtnViewLogs;
extern lv_obj_t * ui_BtnFactoryReset1;
extern lv_obj_t * ui_LabelFactoryReset1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

