// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#include "ui.h"

lv_obj_t * ui_LabelHomeX;
lv_obj_t * ui_LabeelHomeY;
lv_obj_t * ui_LabelHomeZ;
lv_obj_t * ui_BtnZHome;
lv_obj_t * ui_BtnYHome;
lv_obj_t * ui_BtnXHome;
lv_obj_t * ui_LabelSaveMesh;
lv_obj_t * ui_BtnSaveMesh;
lv_obj_t * ui_LabelLoadMesh;
lv_obj_t * ui_BtnLoadMesh;
lv_obj_t * ui_LabelAutoBedLevel;
lv_obj_t * ui_BtnAutoBedLevel;
lv_obj_t * ui_LabelAutoZAlign;
lv_obj_t * ui_BtnAutoZAlign;
lv_obj_t * ui_LabelPosZ;
lv_obj_t * ui_LabelPosY;
lv_obj_t * ui_LabelPosX;
lv_obj_t * ui_SliderBabyZ;
lv_obj_t * ui_LabelBabyZ;
lv_obj_t * ui_DropdownStep;
lv_obj_t * ui_LabelHOMEALL;
lv_obj_t * ui_BtnHomeAll;
lv_obj_t * ui_Image16;
lv_obj_t * ui_LabelZMinus;
lv_obj_t * ui_BtnZMinus;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Image6;
lv_obj_t * ui_LabelZPlus;
lv_obj_t * ui_BtnZPlus;
lv_obj_t * ui_XPus;
lv_obj_t * ui_BtnXPlus;
lv_obj_t * ui_LabelXMinus;
lv_obj_t * ui_BtnXMinus;
lv_obj_t * ui_LabelYMinus;
lv_obj_t * ui_BtnYMinus;
lv_obj_t * ui_YPlus;
lv_obj_t * ui_BtnYPlus;
lv_obj_t * ui_LabelBack1;
lv_obj_t * ui_BtnBack1;
lv_obj_t * ui_LabelScreenTitle;
lv_obj_t * ui_uiPanelTopNav;
lv_obj_t * ui_ScreenJog;
lv_obj_t * ui_ScreenJog = NULL;
lv_obj_t * ui_PanelTopNav3 = NULL;
lv_obj_t * ui_LabelScreenTitle = NULL;
lv_obj_t * ui_BtnBack1 = NULL;
lv_obj_t * ui_LabelBack1 = NULL;
lv_obj_t * ui_BtnYPlus = NULL;
lv_obj_t * ui_LabelYPlus = NULL;
lv_obj_t * ui_BtnYMinus = NULL;
lv_obj_t * ui_LabelYMinus = NULL;
lv_obj_t * ui_BtnXMinus = NULL;
lv_obj_t * ui_LabelXMinus = NULL;
lv_obj_t * ui_BtnXPlus = NULL;
lv_obj_t * ui_LabelXPus = NULL;
lv_obj_t * ui_BtnZPlus = NULL;
lv_obj_t * ui_LabelZPlus = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_BtnZMinus = NULL;
lv_obj_t * ui_LabelZMinus = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_BtnHomeAll = NULL;
lv_obj_t * ui_LabelHOMEALL = NULL;
lv_obj_t * ui_DropdownStep = NULL;
lv_obj_t * ui_LabelBabyZ = NULL;
lv_obj_t * ui_SliderBabyZ = NULL;
lv_obj_t * ui_LabelPosX = NULL;
lv_obj_t * ui_LabelPosY = NULL;
lv_obj_t * ui_LabelPosZ = NULL;
lv_obj_t * ui_BtnAutoZAlign = NULL;
lv_obj_t * ui_LabelAutoZAlign = NULL;
lv_obj_t * ui_BtnAutoBedLevel = NULL;
lv_obj_t * ui_LabelAutoBedLevel = NULL;
lv_obj_t * ui_BtnLoadMesh = NULL;
lv_obj_t * ui_LabelLoadMesh = NULL;
lv_obj_t * ui_BtnSaveMesh = NULL;
lv_obj_t * ui_LabelSaveMesh = NULL;
lv_obj_t * ui_BtnXHome = NULL;
lv_obj_t * ui_BtnYHome = NULL;
lv_obj_t * ui_BtnZHome = NULL;
lv_obj_t * ui_LabelHomeZ = NULL;
lv_obj_t * ui_LabeelHomeY = NULL;
lv_obj_t * ui_LabelHomeX = NULL;
// event funtions
void ui_event_BtnBack1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
    }
}

void ui_event_BtnYPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnYPlus(e);
    }
}

void ui_event_BtnYMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnYMinus(e);
    }
}

void ui_event_BtnXMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnXMinus(e);
    }
}

void ui_event_BtnXPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnXPlus(e);
    }
}

void ui_event_BtnZPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnZPlus(e);
    }
}

void ui_event_BtnZMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnZMinus(e);
    }
}

void ui_event_BtnHomeAll(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnHomeAll(e);
    }
}

void ui_event_DropdownStep(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventDropdownStep(e);
    }
}

void ui_event_SliderBabyZ(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventSliderBabyZ(e);
    }
}

void ui_event_BtnAutoZAlign(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnAutoZAlign(e);
    }
}

void ui_event_BtnAutoBedLevel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnAutoBedLevel(e);
    }
}

void ui_event_BtnLoadMesh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnLoadMesh(e);
    }
}

void ui_event_BtnSaveMesh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnSaveMesh(e);
    }
}

void ui_event_BtnXHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnXHome(e);
    }
}

void ui_event_BtnYHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnYHome(e);
    }
}

void ui_event_BtnZHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnZHome(e);
    }
}

// build funtions

void ui_ScreenJog_screen_init(void)
{
    ui_ScreenJog = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenJog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_ScreenJog, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenJog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ScreenJog, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTopNav3 = lv_obj_create(ui_ScreenJog);
    lv_obj_set_width(ui_PanelTopNav3, 800);
    lv_obj_set_height(ui_PanelTopNav3, 60);
    lv_obj_clear_flag(ui_PanelTopNav3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTopNav3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTopNav3, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTopNav3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScreenTitle = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelScreenTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScreenTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelScreenTitle, 20);
    lv_obj_set_y(ui_LabelScreenTitle, 15);
    lv_label_set_text(ui_LabelScreenTitle, "JOG & LEVELING");
    lv_obj_set_style_text_color(ui_LabelScreenTitle, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScreenTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelScreenTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelScreenTitle, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBack1 = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnBack1, 100);
    lv_obj_set_height(ui_BtnBack1, 40);
    lv_obj_set_x(ui_BtnBack1, 680);
    lv_obj_set_y(ui_BtnBack1, 10);
    lv_obj_add_flag(ui_BtnBack1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBack1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBack1 = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelBack1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBack1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBack1, 331);
    lv_obj_set_y(ui_LabelBack1, -211);
    lv_obj_set_align(ui_LabelBack1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBack1, "Back");
    lv_obj_set_style_text_color(ui_LabelBack1, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBack1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBack1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBack1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnYPlus = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnYPlus, 100);
    lv_obj_set_height(ui_BtnYPlus, 80);
    lv_obj_set_x(ui_BtnYPlus, 180);
    lv_obj_set_y(ui_BtnYPlus, 150);
    lv_obj_add_flag(ui_BtnYPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnYPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnYPlus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnYPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnYPlus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnYPlus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYPlus = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelYPlus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYPlus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelYPlus, 208);
    lv_obj_set_y(ui_LabelYPlus, 150);
    lv_label_set_text(ui_LabelYPlus, "Y+");
    lv_obj_set_style_text_color(ui_LabelYPlus, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelYPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelYPlus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelYPlus, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnYMinus = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnYMinus, 100);
    lv_obj_set_height(ui_BtnYMinus, 80);
    lv_obj_set_x(ui_BtnYMinus, 180);
    lv_obj_set_y(ui_BtnYMinus, 350);
    lv_obj_add_flag(ui_BtnYMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnYMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnYMinus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnYMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnYMinus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnYMinus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYMinus = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelYMinus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYMinus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelYMinus, 215);
    lv_obj_set_y(ui_LabelYMinus, 385);
    lv_label_set_text(ui_LabelYMinus, "Y-");
    lv_obj_set_style_text_color(ui_LabelYMinus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelYMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelYMinus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelYMinus, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnXMinus = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnXMinus, 100);
    lv_obj_set_height(ui_BtnXMinus, 80);
    lv_obj_set_x(ui_BtnXMinus, 50);
    lv_obj_set_y(ui_BtnXMinus, 250);
    lv_obj_add_flag(ui_BtnXMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnXMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnXMinus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnXMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnXMinus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnXMinus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelXMinus = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelXMinus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelXMinus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelXMinus, 63);
    lv_obj_set_y(ui_LabelXMinus, 265);
    lv_label_set_text(ui_LabelXMinus, "X-");
    lv_obj_set_style_text_color(ui_LabelXMinus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelXMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelXMinus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelXMinus, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnXPlus = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnXPlus, 100);
    lv_obj_set_height(ui_BtnXPlus, 80);
    lv_obj_set_x(ui_BtnXPlus, 310);
    lv_obj_set_y(ui_BtnXPlus, 250);
    lv_obj_add_flag(ui_BtnXPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnXPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnXPlus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnXPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnXPlus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnXPlus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelXPus = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelXPus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelXPus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelXPus, 356);
    lv_obj_set_y(ui_LabelXPus, 268);
    lv_label_set_text(ui_LabelXPus, "X+");
    lv_obj_set_style_text_color(ui_LabelXPus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelXPus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelXPus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelXPus, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnZPlus = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnZPlus, 100);
    lv_obj_set_height(ui_BtnZPlus, 80);
    lv_obj_set_x(ui_BtnZPlus, 483);
    lv_obj_set_y(ui_BtnZPlus, 81);
    lv_obj_add_flag(ui_BtnZPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnZPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnZPlus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnZPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnZPlus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnZPlus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnZPlus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelZPlus = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelZPlus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelZPlus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelZPlus, 119);
    lv_obj_set_y(ui_LabelZPlus, -119);
    lv_obj_set_align(ui_LabelZPlus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelZPlus, "Z+");
    lv_obj_set_style_text_color(ui_LabelZPlus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelZPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelZPlus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelZPlus, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_ScreenJog);
    lv_img_set_src(ui_Image6, &ui_img_2098359223);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image6, 165);
    lv_obj_set_y(ui_Image6, -115);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_ScreenJog);
    lv_img_set_src(ui_Image7, &ui_img_2098359223);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image7, -169);
    lv_obj_set_y(ui_Image7, -33);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_ScreenJog);
    lv_img_set_src(ui_Image8, &ui_img_1302380444);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image8, -170);
    lv_obj_set_y(ui_Image8, 131);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_ScreenJog);
    lv_img_set_src(ui_Image11, &ui_img_858268281);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image11, -273);
    lv_obj_set_y(ui_Image11, 50);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_img_create(ui_ScreenJog);
    lv_img_set_src(ui_Image12, &ui_img_1272866020);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image12, -69);
    lv_obj_set_y(ui_Image12, 50);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnZMinus = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnZMinus, 100);
    lv_obj_set_height(ui_BtnZMinus, 80);
    lv_obj_set_x(ui_BtnZMinus, 341);
    lv_obj_set_y(ui_BtnZMinus, 81);
    lv_obj_add_flag(ui_BtnZMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnZMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnZMinus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnZMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnZMinus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnZMinus, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelZMinus = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelZMinus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelZMinus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelZMinus, -27);
    lv_obj_set_y(ui_LabelZMinus, -117);
    lv_obj_set_align(ui_LabelZMinus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelZMinus, "Z-");
    lv_obj_set_style_text_color(ui_LabelZMinus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelZMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelZMinus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelZMinus, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image16 = lv_img_create(ui_ScreenJog);
    lv_img_set_src(ui_Image16, &ui_img_1302380444);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image16, 19);
    lv_obj_set_y(ui_Image16, -115);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnHomeAll = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnHomeAll, 120);
    lv_obj_set_height(ui_BtnHomeAll, 90);
    lv_obj_set_x(ui_BtnHomeAll, 169);
    lv_obj_set_y(ui_BtnHomeAll, 242);
    lv_obj_add_flag(ui_BtnHomeAll, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnHomeAll, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnHomeAll, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnHomeAll, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHOMEALL = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelHOMEALL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHOMEALL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHOMEALL, -173);
    lv_obj_set_y(ui_LabelHOMEALL, 48);
    lv_obj_set_align(ui_LabelHOMEALL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHOMEALL, "HOME ALL");
    lv_obj_set_style_text_color(ui_LabelHOMEALL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHOMEALL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHOMEALL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHOMEALL, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownStep = lv_dropdown_create(ui_ScreenJog);
    lv_dropdown_set_options(ui_DropdownStep, "0.1 mm\n1 mm\n5 mm\n10 mm\n50 mm\n100 mm");
    lv_dropdown_set_text(ui_DropdownStep, "Step Size ");
    lv_obj_set_width(ui_DropdownStep, 140);
    lv_obj_set_height(ui_DropdownStep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownStep, 436);
    lv_obj_set_y(ui_DropdownStep, 279);
    lv_obj_add_flag(ui_DropdownStep, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_DropdownStep, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DropdownStep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DropdownStep, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DropdownStep, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBabyZ = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelBabyZ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBabyZ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBabyZ, 441);
    lv_obj_set_y(ui_LabelBabyZ, 236);
    lv_label_set_text(ui_LabelBabyZ, "Baby Z: 0.00");
    lv_obj_set_style_text_color(ui_LabelBabyZ, lv_color_hex(0xFCFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBabyZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBabyZ, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBabyZ, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderBabyZ = lv_slider_create(ui_ScreenJog);
    lv_slider_set_range(ui_SliderBabyZ, -200, 200);
    lv_slider_set_value(ui_SliderBabyZ, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBabyZ) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBabyZ, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBabyZ, 200);
    lv_obj_set_height(ui_SliderBabyZ, 25);
    lv_obj_set_x(ui_SliderBabyZ, 390);
    lv_obj_set_y(ui_SliderBabyZ, 189);
    lv_obj_set_style_shadow_color(ui_SliderBabyZ, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SliderBabyZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SliderBabyZ, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SliderBabyZ, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPosX = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelPosX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPosX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPosX, 50);
    lv_obj_set_y(ui_LabelPosX, 80);
    lv_label_set_text(ui_LabelPosX, "X: 123.45");
    lv_obj_set_style_text_color(ui_LabelPosX, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPosX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPosX, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPosX, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPosY = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelPosY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPosY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPosY, 50);
    lv_obj_set_y(ui_LabelPosY, 120);
    lv_label_set_text(ui_LabelPosY, "Y: 234.56");
    lv_obj_set_style_text_color(ui_LabelPosY, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPosY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPosY, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPosY, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPosZ = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelPosZ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPosZ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPosZ, 50);
    lv_obj_set_y(ui_LabelPosZ, 160);
    lv_label_set_text(ui_LabelPosZ, "Z: 12.34");
    lv_obj_set_style_text_color(ui_LabelPosZ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPosZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPosZ, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPosZ, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnAutoZAlign = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnAutoZAlign, 160);
    lv_obj_set_height(ui_BtnAutoZAlign, 60);
    lv_obj_set_x(ui_BtnAutoZAlign, 620);
    lv_obj_set_y(ui_BtnAutoZAlign, 105);
    lv_obj_add_flag(ui_BtnAutoZAlign, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnAutoZAlign, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelAutoZAlign = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelAutoZAlign, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAutoZAlign, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAutoZAlign, 632);
    lv_obj_set_y(ui_LabelAutoZAlign, 122);
    lv_label_set_text(ui_LabelAutoZAlign, "Auto Z Align\n");
    lv_obj_set_style_text_color(ui_LabelAutoZAlign, lv_color_hex(0xFCFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAutoZAlign, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelAutoZAlign, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAutoZAlign, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnAutoBedLevel = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnAutoBedLevel, 160);
    lv_obj_set_height(ui_BtnAutoBedLevel, 60);
    lv_obj_set_x(ui_BtnAutoBedLevel, 620);
    lv_obj_set_y(ui_BtnAutoBedLevel, 190);
    lv_obj_add_flag(ui_BtnAutoBedLevel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnAutoBedLevel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelAutoBedLevel = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelAutoBedLevel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAutoBedLevel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAutoBedLevel, 624);
    lv_obj_set_y(ui_LabelAutoBedLevel, 206);
    lv_label_set_text(ui_LabelAutoBedLevel, "Auto Bed Level");
    lv_obj_set_style_text_color(ui_LabelAutoBedLevel, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAutoBedLevel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelAutoBedLevel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAutoBedLevel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnLoadMesh = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnLoadMesh, 160);
    lv_obj_set_height(ui_BtnLoadMesh, 60);
    lv_obj_set_x(ui_BtnLoadMesh, 620);
    lv_obj_set_y(ui_BtnLoadMesh, 275);
    lv_obj_add_flag(ui_BtnLoadMesh, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnLoadMesh, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_BtnLoadMesh, lv_color_hex(0xFDF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnLoadMesh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnLoadMesh, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLoadMesh = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelLoadMesh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLoadMesh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLoadMesh, 300);
    lv_obj_set_y(ui_LabelLoadMesh, 63);
    lv_obj_set_align(ui_LabelLoadMesh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLoadMesh, "Load Mesh");
    lv_obj_set_style_text_color(ui_LabelLoadMesh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLoadMesh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelLoadMesh, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLoadMesh, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSaveMesh = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnSaveMesh, 160);
    lv_obj_set_height(ui_BtnSaveMesh, 60);
    lv_obj_set_x(ui_BtnSaveMesh, 620);
    lv_obj_set_y(ui_BtnSaveMesh, 360);
    lv_obj_add_flag(ui_BtnSaveMesh, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSaveMesh, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSaveMesh = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelSaveMesh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSaveMesh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSaveMesh, 298);
    lv_obj_set_y(ui_LabelSaveMesh, 147);
    lv_obj_set_align(ui_LabelSaveMesh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSaveMesh, "Save Mesh");
    lv_obj_set_style_text_color(ui_LabelSaveMesh, lv_color_hex(0xFBFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSaveMesh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSaveMesh, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSaveMesh, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnXHome = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnXHome, 100);
    lv_obj_set_height(ui_BtnXHome, 50);
    lv_obj_set_x(ui_BtnXHome, -308);
    lv_obj_set_y(ui_BtnXHome, 150);
    lv_obj_set_align(ui_BtnXHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnXHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnXHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnXHome, lv_color_hex(0x29A141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnXHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnYHome = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnYHome, 100);
    lv_obj_set_height(ui_BtnYHome, 50);
    lv_obj_set_x(ui_BtnYHome, -41);
    lv_obj_set_y(ui_BtnYHome, 150);
    lv_obj_set_align(ui_BtnYHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnYHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnYHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnYHome, lv_color_hex(0x29A141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnYHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnZHome = lv_btn_create(ui_ScreenJog);
    lv_obj_set_width(ui_BtnZHome, 100);
    lv_obj_set_height(ui_BtnZHome, 50);
    lv_obj_set_x(ui_BtnZHome, -167);
    lv_obj_set_y(ui_BtnZHome, -146);
    lv_obj_set_align(ui_BtnZHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnZHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnZHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnZHome, lv_color_hex(0x29A141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnZHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHomeZ = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelHomeZ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHomeZ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHomeZ, -168);
    lv_obj_set_y(ui_LabelHomeZ, -147);
    lv_obj_set_align(ui_LabelHomeZ, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHomeZ, "Home Z");
    lv_obj_set_style_text_color(ui_LabelHomeZ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHomeZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHomeZ, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHomeZ, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeelHomeY = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabeelHomeY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeelHomeY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeelHomeY, -42);
    lv_obj_set_y(ui_LabeelHomeY, 159);
    lv_obj_set_align(ui_LabeelHomeY, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabeelHomeY, "Home Y\n");
    lv_obj_set_style_text_color(ui_LabeelHomeY, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeelHomeY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabeelHomeY, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeelHomeY, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHomeX = lv_label_create(ui_ScreenJog);
    lv_obj_set_width(ui_LabelHomeX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHomeX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHomeX, -308);
    lv_obj_set_y(ui_LabelHomeX, 159);
    lv_obj_set_align(ui_LabelHomeX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHomeX, "Home X\n");
    lv_obj_set_style_text_color(ui_LabelHomeX, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHomeX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHomeX, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHomeX, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnBack1, ui_event_BtnBack1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnYPlus, ui_event_BtnYPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnYMinus, ui_event_BtnYMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnXMinus, ui_event_BtnXMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnXPlus, ui_event_BtnXPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnZPlus, ui_event_BtnZPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnZMinus, ui_event_BtnZMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnHomeAll, ui_event_BtnHomeAll, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropdownStep, ui_event_DropdownStep, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBabyZ, ui_event_SliderBabyZ, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnAutoZAlign, ui_event_BtnAutoZAlign, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnAutoBedLevel, ui_event_BtnAutoBedLevel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnLoadMesh, ui_event_BtnLoadMesh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSaveMesh, ui_event_BtnSaveMesh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnXHome, ui_event_BtnXHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnYHome, ui_event_BtnYHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnZHome, ui_event_BtnZHome, LV_EVENT_ALL, NULL);
    ui_ScreenJog = ui_ScreenJog;
    ui_uiPanelTopNav = ui_PanelTopNav3;
    ui_LabelScreenTitle = ui_LabelScreenTitle;
    ui_BtnBack1 = ui_BtnBack1;
    ui_LabelBack1 = ui_LabelBack1;
    ui_BtnYPlus = ui_BtnYPlus;
    ui_YPlus = ui_LabelYPlus;
    ui_BtnYMinus = ui_BtnYMinus;
    ui_LabelYMinus = ui_LabelYMinus;
    ui_BtnXMinus = ui_BtnXMinus;
    ui_LabelXMinus = ui_LabelXMinus;
    ui_BtnXPlus = ui_BtnXPlus;
    ui_XPus = ui_LabelXPus;
    ui_BtnZPlus = ui_BtnZPlus;
    ui_LabelZPlus = ui_LabelZPlus;
    ui_Image6 = ui_Image6;
    ui_Image7 = ui_Image7;
    ui_Image8 = ui_Image8;
    ui_Image11 = ui_Image11;
    ui_Image12 = ui_Image12;
    ui_BtnZMinus = ui_BtnZMinus;
    ui_LabelZMinus = ui_LabelZMinus;
    ui_Image16 = ui_Image16;
    ui_BtnHomeAll = ui_BtnHomeAll;
    ui_LabelHOMEALL = ui_LabelHOMEALL;
    ui_DropdownStep = ui_DropdownStep;
    ui_LabelBabyZ = ui_LabelBabyZ;
    ui_SliderBabyZ = ui_SliderBabyZ;
    ui_LabelPosX = ui_LabelPosX;
    ui_LabelPosY = ui_LabelPosY;
    ui_LabelPosZ = ui_LabelPosZ;
    ui_BtnAutoZAlign = ui_BtnAutoZAlign;
    ui_LabelAutoZAlign = ui_LabelAutoZAlign;
    ui_BtnAutoBedLevel = ui_BtnAutoBedLevel;
    ui_LabelAutoBedLevel = ui_LabelAutoBedLevel;
    ui_BtnLoadMesh = ui_BtnLoadMesh;
    ui_LabelLoadMesh = ui_LabelLoadMesh;
    ui_BtnSaveMesh = ui_BtnSaveMesh;
    ui_LabelSaveMesh = ui_LabelSaveMesh;
    ui_BtnXHome = ui_BtnXHome;
    ui_BtnYHome = ui_BtnYHome;
    ui_BtnZHome = ui_BtnZHome;
    ui_LabelHomeZ = ui_LabelHomeZ;
    ui_LabeelHomeY = ui_LabeelHomeY;
    ui_LabelHomeX = ui_LabelHomeX;

}

void ui_ScreenJog_screen_destroy(void)
{
    if(ui_ScreenJog) lv_obj_del(ui_ScreenJog);

    // NULL screen variables
    ui_ScreenJog = NULL;
    ui_ScreenJog = NULL;
    ui_uiPanelTopNav = NULL;
    ui_PanelTopNav3 = NULL;
    ui_LabelScreenTitle = NULL;
    ui_LabelScreenTitle = NULL;
    ui_BtnBack1 = NULL;
    ui_BtnBack1 = NULL;
    ui_LabelBack1 = NULL;
    ui_LabelBack1 = NULL;
    ui_BtnYPlus = NULL;
    ui_BtnYPlus = NULL;
    ui_YPlus = NULL;
    ui_LabelYPlus = NULL;
    ui_BtnYMinus = NULL;
    ui_BtnYMinus = NULL;
    ui_LabelYMinus = NULL;
    ui_LabelYMinus = NULL;
    ui_BtnXMinus = NULL;
    ui_BtnXMinus = NULL;
    ui_LabelXMinus = NULL;
    ui_LabelXMinus = NULL;
    ui_BtnXPlus = NULL;
    ui_BtnXPlus = NULL;
    ui_XPus = NULL;
    ui_LabelXPus = NULL;
    ui_BtnZPlus = NULL;
    ui_BtnZPlus = NULL;
    ui_LabelZPlus = NULL;
    ui_LabelZPlus = NULL;
    ui_Image6 = NULL;
    ui_Image6 = NULL;
    ui_Image7 = NULL;
    ui_Image7 = NULL;
    ui_Image8 = NULL;
    ui_Image8 = NULL;
    ui_Image11 = NULL;
    ui_Image11 = NULL;
    ui_Image12 = NULL;
    ui_Image12 = NULL;
    ui_BtnZMinus = NULL;
    ui_BtnZMinus = NULL;
    ui_LabelZMinus = NULL;
    ui_LabelZMinus = NULL;
    ui_Image16 = NULL;
    ui_Image16 = NULL;
    ui_BtnHomeAll = NULL;
    ui_BtnHomeAll = NULL;
    ui_LabelHOMEALL = NULL;
    ui_LabelHOMEALL = NULL;
    ui_DropdownStep = NULL;
    ui_DropdownStep = NULL;
    ui_LabelBabyZ = NULL;
    ui_LabelBabyZ = NULL;
    ui_SliderBabyZ = NULL;
    ui_SliderBabyZ = NULL;
    ui_LabelPosX = NULL;
    ui_LabelPosX = NULL;
    ui_LabelPosY = NULL;
    ui_LabelPosY = NULL;
    ui_LabelPosZ = NULL;
    ui_LabelPosZ = NULL;
    ui_BtnAutoZAlign = NULL;
    ui_BtnAutoZAlign = NULL;
    ui_LabelAutoZAlign = NULL;
    ui_LabelAutoZAlign = NULL;
    ui_BtnAutoBedLevel = NULL;
    ui_BtnAutoBedLevel = NULL;
    ui_LabelAutoBedLevel = NULL;
    ui_LabelAutoBedLevel = NULL;
    ui_BtnLoadMesh = NULL;
    ui_BtnLoadMesh = NULL;
    ui_LabelLoadMesh = NULL;
    ui_LabelLoadMesh = NULL;
    ui_BtnSaveMesh = NULL;
    ui_BtnSaveMesh = NULL;
    ui_LabelSaveMesh = NULL;
    ui_LabelSaveMesh = NULL;
    ui_BtnXHome = NULL;
    ui_BtnXHome = NULL;
    ui_BtnYHome = NULL;
    ui_BtnYHome = NULL;
    ui_BtnZHome = NULL;
    ui_BtnZHome = NULL;
    ui_LabelHomeZ = NULL;
    ui_LabelHomeZ = NULL;
    ui_LabeelHomeY = NULL;
    ui_LabeelHomeY = NULL;
    ui_LabelHomeX = NULL;
    ui_LabelHomeX = NULL;

}
