// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#include "ui.h"

lv_obj_t * ui_LabelCurrevtFolder;
lv_obj_t * ui_LabelDown;
lv_obj_t * ui_BtnUpFolderDown;
lv_obj_t * ui_LabelSort;
lv_obj_t * ui_LabelUP;
lv_obj_t * ui_BtnSort;
lv_obj_t * ui_BtnUpFolderUP;
lv_obj_t * ui_LabelDelete;
lv_obj_t * ui_BtnDeleteFile;
lv_obj_t * ui_LabelPrintSelected;
lv_obj_t * ui_BtnPrintSelected;
lv_obj_t * ui_LabelLayerCount;
lv_obj_t * ui_LabelFileSize;
lv_obj_t * ui_LabelSelectedFile;
lv_obj_t * ui_LabelFileItem;
lv_obj_t * ui_BtnFileItem;
lv_obj_t * ui_PanelFileList;
lv_obj_t * ui_LabelFreeSpace;
lv_obj_t * ui_BtnRefresh;
lv_obj_t * ui_LabelTitle1;
lv_obj_t * ui_LabelBack4;
lv_obj_t * ui_BtnBack4;
lv_obj_t * ui_ScreenFiles;
lv_obj_t * ui_ScreenFiles = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_BtnBack4 = NULL;
lv_obj_t * ui_LabelBack4 = NULL;
lv_obj_t * ui_LabelTitle1 = NULL;
lv_obj_t * ui_BtnRefresh = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_LabelFreeSpace = NULL;
lv_obj_t * ui_PanelFileList = NULL;
lv_obj_t * ui_BtnFileItem = NULL;
lv_obj_t * ui_LabelFileItem = NULL;
lv_obj_t * ui_LabelSelectedFile = NULL;
lv_obj_t * ui_LabelFileSize = NULL;
lv_obj_t * ui_LabelLayerCount = NULL;
lv_obj_t * ui_BtnPrintSelected = NULL;
lv_obj_t * ui_LabelPrintSelected = NULL;
lv_obj_t * ui_BtnDeleteFile = NULL;
lv_obj_t * ui_LabelDelete = NULL;
lv_obj_t * ui_BtnUpFolderUP = NULL;
lv_obj_t * ui_BtnSort = NULL;
lv_obj_t * ui_LabelUP = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_LabelSort = NULL;
lv_obj_t * ui_BtnUpFolderDown = NULL;
lv_obj_t * ui_LabelDown = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_LabelCurrevtFolder = NULL;
lv_obj_t * ui_Label20 = NULL;
// event funtions
void ui_event_BtnBack4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
    }
}

void ui_event_BtnRefresh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnRefresh(e);
    }
}

void ui_event_BtnFileItem(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventFileItemClicked(e);
    }
}

void ui_event_BtnPrintSelected(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnPrintSelected(e);
    }
}

void ui_event_BtnDeleteFile(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnDeleteFile(e);
    }
}

void ui_event_BtnUpFolderUP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnUpFolderUP(e);
    }
}

void ui_event_BtnSort(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnSort(e);
    }
}

void ui_event_BtnUpFolderDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnUpFolderDown(e);
    }
}

// build funtions

void ui_ScreenFiles_screen_init(void)
{
    ui_ScreenFiles = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenFiles, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_ScreenFiles);
    lv_obj_set_width(ui_Panel4, 800);
    lv_obj_set_height(ui_Panel4, 70);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBack4 = lv_btn_create(ui_ScreenFiles);
    lv_obj_set_width(ui_BtnBack4, 100);
    lv_obj_set_height(ui_BtnBack4, 40);
    lv_obj_set_x(ui_BtnBack4, 680);
    lv_obj_set_y(ui_BtnBack4, 15);
    lv_obj_add_flag(ui_BtnBack4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBack4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBack4 = lv_label_create(ui_ScreenFiles);
    lv_obj_set_width(ui_LabelBack4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBack4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBack4, 699);
    lv_obj_set_y(ui_LabelBack4, 21);
    lv_label_set_text(ui_LabelBack4, "Back\n");
    lv_obj_set_style_text_color(ui_LabelBack4, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBack4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBack4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBack4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitle1 = lv_label_create(ui_ScreenFiles);
    lv_obj_set_width(ui_LabelTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle1, 20);
    lv_obj_set_y(ui_LabelTitle1, 18);
    lv_label_set_text(ui_LabelTitle1, "SD Card Files");
    lv_obj_set_style_text_color(ui_LabelTitle1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTitle1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTitle1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnRefresh = lv_btn_create(ui_ScreenFiles);
    lv_obj_set_width(ui_BtnRefresh, 100);
    lv_obj_set_height(ui_BtnRefresh, 40);
    lv_obj_set_x(ui_BtnRefresh, 538);
    lv_obj_set_y(ui_BtnRefresh, 15);
    lv_obj_add_flag(ui_BtnRefresh, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnRefresh, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_ScreenFiles);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 544);
    lv_obj_set_y(ui_Label7, 21);
    lv_label_set_text(ui_Label7, "Refresh\n");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFBF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFreeSpace = lv_label_create(ui_ScreenFiles);
    lv_obj_set_width(ui_LabelFreeSpace, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFreeSpace, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFreeSpace, 380);
    lv_obj_set_y(ui_LabelFreeSpace, 20);
    lv_label_set_text(ui_LabelFreeSpace, "2.8 GB free");
    lv_obj_set_style_text_color(ui_LabelFreeSpace, lv_color_hex(0xFFFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFreeSpace, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelFreeSpace, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFreeSpace, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelFileList = lv_obj_create(ui_ScreenFiles);
    lv_obj_set_width(ui_PanelFileList, 520);
    lv_obj_set_height(ui_PanelFileList, 320);
    lv_obj_set_x(ui_PanelFileList, 40);
    lv_obj_set_y(ui_PanelFileList, 90);
    lv_obj_set_flex_flow(ui_PanelFileList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelFileList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scroll_dir(ui_PanelFileList, LV_DIR_VER);
    lv_obj_set_style_radius(ui_PanelFileList, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelFileList, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelFileList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnFileItem = lv_btn_create(ui_ScreenFiles);
    lv_obj_set_width(ui_BtnFileItem, 262);
    lv_obj_set_height(ui_BtnFileItem, 50);
    lv_obj_set_x(ui_BtnFileItem, -212);
    lv_obj_set_y(ui_BtnFileItem, -91);
    lv_obj_set_align(ui_BtnFileItem, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnFileItem, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnFileItem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelFileItem = lv_label_create(ui_BtnFileItem);
    lv_obj_set_width(ui_LabelFileItem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFileItem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFileItem, -1);
    lv_obj_set_y(ui_LabelFileItem, -1);
    lv_obj_set_align(ui_LabelFileItem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFileItem, "example.gcode");
    lv_obj_set_style_text_color(ui_LabelFileItem, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFileItem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelFileItem, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFileItem, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSelectedFile = lv_label_create(ui_ScreenFiles);
    lv_obj_set_width(ui_LabelSelectedFile, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSelectedFile, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSelectedFile, 590);
    lv_obj_set_y(ui_LabelSelectedFile, 100);
    lv_label_set_text(ui_LabelSelectedFile, "Selected: -");
    lv_obj_set_style_text_color(ui_LabelSelectedFile, lv_color_hex(0xFBFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSelectedFile, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSelectedFile, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSelectedFile, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFileSize = lv_label_create(ui_ScreenFiles);
    lv_obj_set_width(ui_LabelFileSize, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFileSize, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFileSize, 590);
    lv_obj_set_y(ui_LabelFileSize, 190);
    lv_label_set_text(ui_LabelFileSize, "Size: -");
    lv_obj_set_style_text_color(ui_LabelFileSize, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFileSize, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelFileSize, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFileSize, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLayerCount = lv_label_create(ui_ScreenFiles);
    lv_obj_set_width(ui_LabelLayerCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLayerCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLayerCount, 590);
    lv_obj_set_y(ui_LabelLayerCount, 230);
    lv_label_set_text(ui_LabelLayerCount, "Layers: -");
    lv_obj_set_style_text_color(ui_LabelLayerCount, lv_color_hex(0xFCFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLayerCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelLayerCount, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLayerCount, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPrintSelected = lv_btn_create(ui_ScreenFiles);
    lv_obj_set_width(ui_BtnPrintSelected, 190);
    lv_obj_set_height(ui_BtnPrintSelected, 65);
    lv_obj_set_x(ui_BtnPrintSelected, 590);
    lv_obj_set_y(ui_BtnPrintSelected, 290);
    lv_obj_add_flag(ui_BtnPrintSelected, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPrintSelected, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnPrintSelected, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPrintSelected, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPrintSelected = lv_label_create(ui_ScreenFiles);
    lv_obj_set_width(ui_LabelPrintSelected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPrintSelected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPrintSelected, 284);
    lv_obj_set_y(ui_LabelPrintSelected, 83);
    lv_obj_set_align(ui_LabelPrintSelected, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPrintSelected, "PRINT FILE");
    lv_obj_set_style_text_color(ui_LabelPrintSelected, lv_color_hex(0xF69020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPrintSelected, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPrintSelected, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnDeleteFile = lv_btn_create(ui_ScreenFiles);
    lv_obj_set_width(ui_BtnDeleteFile, 190);
    lv_obj_set_height(ui_BtnDeleteFile, 55);
    lv_obj_set_x(ui_BtnDeleteFile, 590);
    lv_obj_set_y(ui_BtnDeleteFile, 370);
    lv_obj_add_flag(ui_BtnDeleteFile, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnDeleteFile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnDeleteFile, lv_color_hex(0xFD0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnDeleteFile, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDelete = lv_label_create(ui_ScreenFiles);
    lv_obj_set_width(ui_LabelDelete, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDelete, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDelete, 278);
    lv_obj_set_y(ui_LabelDelete, 153);
    lv_obj_set_align(ui_LabelDelete, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDelete, "Delete");
    lv_obj_set_style_text_color(ui_LabelDelete, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDelete, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelDelete, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDelete, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnUpFolderUP = lv_btn_create(ui_ScreenFiles);
    lv_obj_set_width(ui_BtnUpFolderUP, 120);
    lv_obj_set_height(ui_BtnUpFolderUP, 45);
    lv_obj_set_x(ui_BtnUpFolderUP, 40);
    lv_obj_set_y(ui_BtnUpFolderUP, 425);
    lv_obj_add_flag(ui_BtnUpFolderUP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnUpFolderUP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnSort = lv_btn_create(ui_ScreenFiles);
    lv_obj_set_width(ui_BtnSort, 100);
    lv_obj_set_height(ui_BtnSort, 45);
    lv_obj_set_x(ui_BtnSort, 183);
    lv_obj_set_y(ui_BtnSort, 425);
    lv_obj_add_flag(ui_BtnSort, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSort, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelUP = lv_label_create(ui_ScreenFiles);
    lv_obj_set_width(ui_LabelUP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUP, -329);
    lv_obj_set_y(ui_LabelUP, 206);
    lv_obj_set_align(ui_LabelUP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUP, "UP");
    lv_obj_set_style_text_color(ui_LabelUP, lv_color_hex(0xFAF8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelUP, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUP, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_ScreenFiles);
    lv_img_set_src(ui_Image1, &ui_img_2098359223);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image1, -286);
    lv_obj_set_y(ui_Image1, 206);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSort = lv_label_create(ui_ScreenFiles);
    lv_obj_set_width(ui_LabelSort, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSort, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSort, -166);
    lv_obj_set_y(ui_LabelSort, 206);
    lv_obj_set_align(ui_LabelSort, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSort, "SORT");
    lv_obj_set_style_text_color(ui_LabelSort, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSort, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSort, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSort, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnUpFolderDown = lv_btn_create(ui_ScreenFiles);
    lv_obj_set_width(ui_BtnUpFolderDown, 120);
    lv_obj_set_height(ui_BtnUpFolderDown, 45);
    lv_obj_set_x(ui_BtnUpFolderDown, 307);
    lv_obj_set_y(ui_BtnUpFolderDown, 425);
    lv_obj_add_flag(ui_BtnUpFolderDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnUpFolderDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDown = lv_label_create(ui_ScreenFiles);
    lv_obj_set_width(ui_LabelDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDown, -52);
    lv_obj_set_y(ui_LabelDown, 217);
    lv_obj_set_align(ui_LabelDown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDown, "DOWN\n");
    lv_obj_set_style_text_color(ui_LabelDown, lv_color_hex(0xFBF8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelDown, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDown, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_ScreenFiles);
    lv_img_set_src(ui_Image2, &ui_img_1302380444);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image2, 6);
    lv_obj_set_y(ui_Image2, 207);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCurrevtFolder = lv_label_create(ui_ScreenFiles);
    lv_obj_set_width(ui_LabelCurrevtFolder, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCurrevtFolder, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCurrevtFolder, 448);
    lv_obj_set_y(ui_LabelCurrevtFolder, 439);
    lv_label_set_text(ui_LabelCurrevtFolder, "/ (current folder)");
    lv_obj_set_style_text_color(ui_LabelCurrevtFolder, lv_color_hex(0xDEA302), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCurrevtFolder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelCurrevtFolder, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCurrevtFolder, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_ScreenFiles);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 657);
    lv_obj_set_y(ui_Label20, -217);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_BtnBack4, ui_event_BtnBack4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnRefresh, ui_event_BtnRefresh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnFileItem, ui_event_BtnFileItem, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPrintSelected, ui_event_BtnPrintSelected, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnDeleteFile, ui_event_BtnDeleteFile, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnUpFolderUP, ui_event_BtnUpFolderUP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSort, ui_event_BtnSort, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnUpFolderDown, ui_event_BtnUpFolderDown, LV_EVENT_ALL, NULL);
    ui_ScreenFiles = ui_ScreenFiles;
    ui_BtnBack4 = ui_BtnBack4;
    ui_LabelBack4 = ui_LabelBack4;
    ui_LabelTitle1 = ui_LabelTitle1;
    ui_BtnRefresh = ui_BtnRefresh;
    ui_LabelFreeSpace = ui_LabelFreeSpace;
    ui_PanelFileList = ui_PanelFileList;
    ui_BtnFileItem = ui_BtnFileItem;
    ui_LabelFileItem = ui_LabelFileItem;
    ui_LabelSelectedFile = ui_LabelSelectedFile;
    ui_LabelFileSize = ui_LabelFileSize;
    ui_LabelLayerCount = ui_LabelLayerCount;
    ui_BtnPrintSelected = ui_BtnPrintSelected;
    ui_LabelPrintSelected = ui_LabelPrintSelected;
    ui_BtnDeleteFile = ui_BtnDeleteFile;
    ui_LabelDelete = ui_LabelDelete;
    ui_BtnUpFolderUP = ui_BtnUpFolderUP;
    ui_BtnSort = ui_BtnSort;
    ui_LabelUP = ui_LabelUP;
    ui_LabelSort = ui_LabelSort;
    ui_BtnUpFolderDown = ui_BtnUpFolderDown;
    ui_LabelDown = ui_LabelDown;
    ui_LabelCurrevtFolder = ui_LabelCurrevtFolder;

}

void ui_ScreenFiles_screen_destroy(void)
{
    if(ui_ScreenFiles) lv_obj_del(ui_ScreenFiles);

    // NULL screen variables
    ui_ScreenFiles = NULL;
    ui_ScreenFiles = NULL;
    ui_Panel4 = NULL;
    ui_BtnBack4 = NULL;
    ui_BtnBack4 = NULL;
    ui_LabelBack4 = NULL;
    ui_LabelBack4 = NULL;
    ui_LabelTitle1 = NULL;
    ui_LabelTitle1 = NULL;
    ui_BtnRefresh = NULL;
    ui_BtnRefresh = NULL;
    ui_Label7 = NULL;
    ui_LabelFreeSpace = NULL;
    ui_LabelFreeSpace = NULL;
    ui_PanelFileList = NULL;
    ui_PanelFileList = NULL;
    ui_BtnFileItem = NULL;
    ui_BtnFileItem = NULL;
    ui_LabelFileItem = NULL;
    ui_LabelFileItem = NULL;
    ui_LabelSelectedFile = NULL;
    ui_LabelSelectedFile = NULL;
    ui_LabelFileSize = NULL;
    ui_LabelFileSize = NULL;
    ui_LabelLayerCount = NULL;
    ui_LabelLayerCount = NULL;
    ui_BtnPrintSelected = NULL;
    ui_BtnPrintSelected = NULL;
    ui_LabelPrintSelected = NULL;
    ui_LabelPrintSelected = NULL;
    ui_BtnDeleteFile = NULL;
    ui_BtnDeleteFile = NULL;
    ui_LabelDelete = NULL;
    ui_LabelDelete = NULL;
    ui_BtnUpFolderUP = NULL;
    ui_BtnUpFolderUP = NULL;
    ui_BtnSort = NULL;
    ui_BtnSort = NULL;
    ui_LabelUP = NULL;
    ui_LabelUP = NULL;
    ui_Image1 = NULL;
    ui_LabelSort = NULL;
    ui_LabelSort = NULL;
    ui_BtnUpFolderDown = NULL;
    ui_BtnUpFolderDown = NULL;
    ui_LabelDown = NULL;
    ui_LabelDown = NULL;
    ui_Image2 = NULL;
    ui_LabelCurrevtFolder = NULL;
    ui_LabelCurrevtFolder = NULL;
    ui_Label20 = NULL;

}
