// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#include "ui.h"

lv_obj_t * ui_LabelNumCancel;
lv_obj_t * ui_BtnNumCancel;
lv_obj_t * ui_LabelNumClear;
lv_obj_t * ui_BtnNumClear;
lv_obj_t * ui_LabelNumBackspace;
lv_obj_t * ui_BtnNumBackspace;
lv_obj_t * ui_LabelNumEnter;
lv_obj_t * ui_BtnNumENTER;
lv_obj_t * ui_LabelNumDecimal;
lv_obj_t * ui_BtnNumDecimal;
lv_obj_t * ui_BtnNum0;
lv_obj_t * ui_LabelNum3;
lv_obj_t * ui_BtnNum3;
lv_obj_t * ui_LabelNum2;
lv_obj_t * ui_BtnNum2;
lv_obj_t * ui_LabelNum1;
lv_obj_t * ui_BtnNum1;
lv_obj_t * ui_LabelNum6;
lv_obj_t * ui_BtnNum6;
lv_obj_t * ui_LabelNum5;
lv_obj_t * ui_BtnNum5;
lv_obj_t * ui_LabelNum4;
lv_obj_t * ui_BtnNum4;
lv_obj_t * ui_BtnNum9;
lv_obj_t * ui_BtnNum8;
lv_obj_t * ui_LabelNum7;
lv_obj_t * ui_BtnNum7;
lv_obj_t * ui_TxtNumPadInput;
lv_obj_t * ui_LabelNumPadTitle;
lv_obj_t * ui_PanelNumPad;
lv_obj_t * ui_LabelReboot;
lv_obj_t * ui_BtnReboot;
lv_obj_t * ui_LabelFactoryReset;
lv_obj_t * ui_BtnSaveAll;
lv_obj_t * ui_PanelSystem;
lv_obj_t * ui_TxtPassword;
lv_obj_t * ui_TxtSSID;
lv_obj_t * ui_LabelSwitchWiFi;
lv_obj_t * ui_SwitchWiFi;
lv_obj_t * ui_PanelNetwork;
lv_obj_t * ui_LabelScreenTimeout;
lv_obj_t * ui_LabelSwitchSound;
lv_obj_t * ui_SwitchScreenTimeout;
lv_obj_t * ui_SwitchSound;
lv_obj_t * ui_LabelBrightness;
lv_obj_t * ui_LabelBrightnessValue;
lv_obj_t * ui_SliderBrightness;
lv_obj_t * ui_PanelDisplay;
lv_obj_t * ui_LabelFlowValue;
lv_obj_t * ui_SliderFlow;
lv_obj_t * ui_TxtFilDia;
lv_obj_t * ui_LabelFilDia;
lv_obj_t * ui_PanelFilament;
lv_obj_t * ui_LabelApplySteps;
lv_obj_t * ui_BtnApplySteps;
lv_obj_t * ui_LabelE0Steps;
lv_obj_t * ui_LabelZSteps;
lv_obj_t * ui_LabelYSteps;
lv_obj_t * ui_LabelXSteps;
lv_obj_t * ui_TxtE0Steps;
lv_obj_t * ui_TxtZSteps;
lv_obj_t * ui_TxtYSteps;
lv_obj_t * ui_TxtXSteps;
lv_obj_t * ui_LabelStepsTitle;
lv_obj_t * ui_PanelSteps;
lv_obj_t * ui_LabelBack5;
lv_obj_t * ui_BtnBack5;
lv_obj_t * ui_LabelAbout;
lv_obj_t * ui_BtnAbout;
lv_obj_t * ui_LabelTitleSettings;
lv_obj_t * ui_ScreenSettings;
lv_obj_t * ui_ScreenSettings = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_LabelTitleSettings = NULL;
lv_obj_t * ui_BtnAbout = NULL;
lv_obj_t * ui_LabelAbout = NULL;
lv_obj_t * ui_BtnBack5 = NULL;
lv_obj_t * ui_LabelBack5 = NULL;
lv_obj_t * ui_PanelSteps = NULL;
lv_obj_t * ui_LabelStepsTitle = NULL;
lv_obj_t * ui_TxtXSteps = NULL;
lv_obj_t * ui_TxtYSteps = NULL;
lv_obj_t * ui_TxtZSteps = NULL;
lv_obj_t * ui_TxtE0Steps = NULL;
lv_obj_t * ui_LabelXSteps = NULL;
lv_obj_t * ui_LabelYSteps = NULL;
lv_obj_t * ui_LabelZSteps = NULL;
lv_obj_t * ui_LabelE0Steps = NULL;
lv_obj_t * ui_BtnApplySteps = NULL;
lv_obj_t * ui_LabelApplySteps = NULL;
lv_obj_t * ui_PanelFilament = NULL;
lv_obj_t * ui_LabelFilDia = NULL;
lv_obj_t * ui_LabelFlow = NULL;
lv_obj_t * ui_TxtFilDia = NULL;
lv_obj_t * ui_SliderFlow = NULL;
lv_obj_t * ui_LabelFlowValue = NULL;
lv_obj_t * ui_PanelDisplay = NULL;
lv_obj_t * ui_SliderBrightness = NULL;
lv_obj_t * ui_LabelBrightnessValue = NULL;
lv_obj_t * ui_LabelBrightness = NULL;
lv_obj_t * ui_SwitchSound = NULL;
lv_obj_t * ui_SwitchScreenTimeout = NULL;
lv_obj_t * ui_LabelSwitchSound = NULL;
lv_obj_t * ui_LabelScreenTimeout = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Image19 = NULL;
lv_obj_t * ui_Image21 = NULL;
lv_obj_t * ui_PanelNetwork = NULL;
lv_obj_t * ui_SwitchWiFi = NULL;
lv_obj_t * ui_LabelSwitchWiFi = NULL;
lv_obj_t * ui_TxtSSID = NULL;
lv_obj_t * ui_TxtPassword = NULL;
lv_obj_t * ui_PanelSystem = NULL;
lv_obj_t * ui_BtnSaveAll = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_BtnFactoryReset = NULL;
lv_obj_t * ui_LabelFactoryReset = NULL;
lv_obj_t * ui_BtnReboot = NULL;
lv_obj_t * ui_LabelReboot = NULL;
lv_obj_t * ui_PanelNumPad = NULL;
lv_obj_t * ui_LabelNumPadTitle = NULL;
lv_obj_t * ui_TxtNumPadInput = NULL;
lv_obj_t * ui_BtnNum7 = NULL;
lv_obj_t * ui_LabelNum7 = NULL;
lv_obj_t * ui_BtnNum8 = NULL;
lv_obj_t * ui_LabelNum8 = NULL;
lv_obj_t * ui_BtnNum9 = NULL;
lv_obj_t * ui_LabelNum9 = NULL;
lv_obj_t * ui_BtnNum4 = NULL;
lv_obj_t * ui_LabelNum4 = NULL;
lv_obj_t * ui_BtnNum5 = NULL;
lv_obj_t * ui_LabelNum5 = NULL;
lv_obj_t * ui_BtnNum6 = NULL;
lv_obj_t * ui_LabelNum6 = NULL;
lv_obj_t * ui_BtnNum1 = NULL;
lv_obj_t * ui_LabelNum1 = NULL;
lv_obj_t * ui_BtnNum2 = NULL;
lv_obj_t * ui_LabelNum2 = NULL;
lv_obj_t * ui_BtnNum3 = NULL;
lv_obj_t * ui_LabelNum3 = NULL;
lv_obj_t * ui_BtnNum0 = NULL;
lv_obj_t * ui_LabelNum0 = NULL;
lv_obj_t * ui_BtnNumDecimal = NULL;
lv_obj_t * ui_LabelNumDecimal = NULL;
lv_obj_t * ui_BtnNumENTER = NULL;
lv_obj_t * ui_LabelNumEnter = NULL;
lv_obj_t * ui_BtnNumBackspace = NULL;
lv_obj_t * ui_LabelNumBackspace = NULL;
lv_obj_t * ui_BtnNumClear = NULL;
lv_obj_t * ui_LabelNumClear = NULL;
lv_obj_t * ui_BtnNumCancel = NULL;
lv_obj_t * ui_LabelNumCancel = NULL;
// event funtions
void ui_event_BtnAbout(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenAbout, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenAbout_screen_init);
    }
}

void ui_event_BtnBack5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
    }
}

void ui_event_TxtXSteps(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventTxtXStepsClicked(e);
    }
}

void ui_event_TxtYSteps(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventTxtYStepsClicked(e);
    }
}

void ui_event_TxtZSteps(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventTxtZStepsClicked(e);
    }
}

void ui_event_TxtE0Steps(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventTxtE0StepsClicked(e);
    }
}

void ui_event_BtnApplySteps(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnApplySteps(e);
    }
}

void ui_event_TxtFilDia(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventTxtFilDiaClicked(e);
    }
}

void ui_event_SliderFlow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventSliderFlow(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelFlowValue, target, "", "");
    }
}

void ui_event_SliderBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventSliderBrightness(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelBrightnessValue, target, "", "");
    }
}

void ui_event_SwitchSound(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventSwitchSound(e);
    }
}

void ui_event_SwitchScreenTimeout(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventSwitchScreenTimeout(e);
    }
}

void ui_event_SwitchWiFi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventSwitchWiFi(e);
    }
}

void ui_event_TxtSSID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventTxtSSIDClicked(e);
    }
}

void ui_event_TxtPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventTxtPasswordClicked(e);
    }
}

void ui_event_BtnSaveAll(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnSaveAll(e);
    }
}

void ui_event_BtnFactoryReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnReboot(e);
    }
}

void ui_event_BtnNum7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventNumPadDigit(e);
    }
}

void ui_event_BtnNum8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventNumPadDigit(e);
    }
}

void ui_event_BtnNum9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventNumPadDigit(e);
    }
}

void ui_event_BtnNum4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventNumPadDigit(e);
    }
}

void ui_event_BtnNum5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventNumPadDigit(e);
    }
}

void ui_event_BtnNum6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventNumPadDigit(e);
    }
}

void ui_event_BtnNum1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventNumPadDigit(e);
    }
}

void ui_event_BtnNum2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventNumPadDigit(e);
    }
}

void ui_event_BtnNum3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventNumPadDigit(e);
    }
}

void ui_event_BtnNum0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventNumPadDigit(e);
    }
}

void ui_event_BtnNumDecimal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventNumPadDigit(e);
    }
}

void ui_event_BtnNumENTER(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventNumPadEnter(e);
    }
}

void ui_event_BtnNumBackspace(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventNumPadBackspace(e);
    }
}

void ui_event_BtnNumClear(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventNumPadClear(e);
    }
}

void ui_event_BtnNumCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventNumPadCancel(e);
    }
}

// build funtions

void ui_ScreenSettings_screen_init(void)
{
    ui_ScreenSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_Panel5, 800);
    lv_obj_set_height(ui_Panel5, 60);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitleSettings = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_LabelTitleSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitleSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitleSettings, 321);
    lv_obj_set_y(ui_LabelTitleSettings, -8);
    lv_label_set_text(ui_LabelTitleSettings, "Settings");
    lv_obj_set_style_text_color(ui_LabelTitleSettings, lv_color_hex(0xFDFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitleSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTitleSettings, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTitleSettings, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnAbout = lv_btn_create(ui_Panel5);
    lv_obj_set_width(ui_BtnAbout, 135);
    lv_obj_set_height(ui_BtnAbout, 40);
    lv_obj_set_x(ui_BtnAbout, 505);
    lv_obj_set_y(ui_BtnAbout, -12);
    lv_obj_add_flag(ui_BtnAbout, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnAbout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_BtnAbout, lv_color_hex(0xFCF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnAbout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnAbout, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnAbout, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAbout = lv_label_create(ui_BtnAbout);
    lv_obj_set_width(ui_LabelAbout, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAbout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAbout, -6);
    lv_obj_set_y(ui_LabelAbout, -3);
    lv_label_set_text(ui_LabelAbout, "About Info");

    ui_BtnBack5 = lv_btn_create(ui_ScreenSettings);
    lv_obj_set_width(ui_BtnBack5, 100);
    lv_obj_set_height(ui_BtnBack5, 40);
    lv_obj_set_x(ui_BtnBack5, 680);
    lv_obj_set_y(ui_BtnBack5, 10);
    lv_obj_add_flag(ui_BtnBack5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBack5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_BtnBack5, lv_color_hex(0xFCF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnBack5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnBack5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnBack5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBack5 = lv_label_create(ui_BtnBack5);
    lv_obj_set_width(ui_LabelBack5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBack5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBack5, 3);
    lv_obj_set_y(ui_LabelBack5, -3);
    lv_label_set_text(ui_LabelBack5, "Back\n");

    ui_PanelSteps = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_PanelSteps, 271);
    lv_obj_set_height(ui_PanelSteps, 258);
    lv_obj_set_x(ui_PanelSteps, 13);
    lv_obj_set_y(ui_PanelSteps, 63);
    lv_obj_clear_flag(ui_PanelSteps, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSteps, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSteps, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSteps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStepsTitle = lv_label_create(ui_PanelSteps);
    lv_obj_set_width(ui_LabelStepsTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStepsTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStepsTitle, 28);
    lv_obj_set_y(ui_LabelStepsTitle, -19);
    lv_label_set_text(ui_LabelStepsTitle, "Steps per mm");
    lv_obj_set_style_text_color(ui_LabelStepsTitle, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStepsTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelStepsTitle, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStepsTitle, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtXSteps = lv_textarea_create(ui_PanelSteps);
    lv_obj_set_width(ui_TxtXSteps, 150);
    lv_obj_set_height(ui_TxtXSteps, 50);
    lv_obj_set_x(ui_TxtXSteps, 30);
    lv_obj_set_y(ui_TxtXSteps, 11);
    lv_textarea_set_text(ui_TxtXSteps, "80.00");
    lv_textarea_set_placeholder_text(ui_TxtXSteps, "Placeholder...");
    lv_obj_set_style_text_color(ui_TxtXSteps, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TxtXSteps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TxtXSteps, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TxtXSteps, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtYSteps = lv_textarea_create(ui_PanelSteps);
    lv_obj_set_width(ui_TxtYSteps, 150);
    lv_obj_set_height(ui_TxtYSteps, 50);
    lv_obj_set_x(ui_TxtYSteps, 30);
    lv_obj_set_y(ui_TxtYSteps, 66);
    lv_textarea_set_text(ui_TxtYSteps, "80.00");
    lv_textarea_set_placeholder_text(ui_TxtYSteps, "Placeholder...");
    lv_obj_set_style_text_color(ui_TxtYSteps, lv_color_hex(0xFCFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TxtYSteps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TxtYSteps, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TxtYSteps, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtZSteps = lv_textarea_create(ui_PanelSteps);
    lv_obj_set_width(ui_TxtZSteps, 150);
    lv_obj_set_height(ui_TxtZSteps, 50);
    lv_obj_set_x(ui_TxtZSteps, 30);
    lv_obj_set_y(ui_TxtZSteps, 122);
    lv_textarea_set_text(ui_TxtZSteps, "1512.00");
    lv_textarea_set_placeholder_text(ui_TxtZSteps, "Placeholder...");
    lv_obj_set_style_text_color(ui_TxtZSteps, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TxtZSteps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TxtZSteps, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TxtZSteps, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtE0Steps = lv_textarea_create(ui_PanelSteps);
    lv_obj_set_width(ui_TxtE0Steps, 150);
    lv_obj_set_height(ui_TxtE0Steps, 50);
    lv_obj_set_x(ui_TxtE0Steps, 30);
    lv_obj_set_y(ui_TxtE0Steps, 179);
    lv_textarea_set_text(ui_TxtE0Steps, "668.00");
    lv_textarea_set_placeholder_text(ui_TxtE0Steps, "Placeholder...");
    lv_obj_set_style_text_color(ui_TxtE0Steps, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TxtE0Steps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TxtE0Steps, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TxtE0Steps, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelXSteps = lv_label_create(ui_PanelSteps);
    lv_obj_set_width(ui_LabelXSteps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelXSteps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelXSteps, -3);
    lv_obj_set_y(ui_LabelXSteps, 24);
    lv_label_set_text(ui_LabelXSteps, "X");
    lv_obj_set_style_text_color(ui_LabelXSteps, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelXSteps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelXSteps, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelXSteps, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYSteps = lv_label_create(ui_PanelSteps);
    lv_obj_set_width(ui_LabelYSteps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYSteps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelYSteps, -2);
    lv_obj_set_y(ui_LabelYSteps, 80);
    lv_label_set_text(ui_LabelYSteps, "Y");
    lv_obj_set_style_text_color(ui_LabelYSteps, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelYSteps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelYSteps, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelYSteps, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelZSteps = lv_label_create(ui_PanelSteps);
    lv_obj_set_width(ui_LabelZSteps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelZSteps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelZSteps, -3);
    lv_obj_set_y(ui_LabelZSteps, 134);
    lv_label_set_text(ui_LabelZSteps, "Z");
    lv_obj_set_style_text_color(ui_LabelZSteps, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelZSteps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelZSteps, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelZSteps, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelE0Steps = lv_label_create(ui_PanelSteps);
    lv_obj_set_width(ui_LabelE0Steps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelE0Steps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelE0Steps, -10);
    lv_obj_set_y(ui_LabelE0Steps, 190);
    lv_label_set_text(ui_LabelE0Steps, "E0");
    lv_obj_set_style_text_color(ui_LabelE0Steps, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelE0Steps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelE0Steps, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelE0Steps, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnApplySteps = lv_btn_create(ui_ScreenSettings);
    lv_obj_set_width(ui_BtnApplySteps, 150);
    lv_obj_set_height(ui_BtnApplySteps, 40);
    lv_obj_set_x(ui_BtnApplySteps, 65);
    lv_obj_set_y(ui_BtnApplySteps, 10);
    lv_obj_add_flag(ui_BtnApplySteps, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnApplySteps, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_BtnApplySteps, lv_color_hex(0xFBF8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnApplySteps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnApplySteps, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnApplySteps, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelApplySteps = lv_label_create(ui_BtnApplySteps);
    lv_obj_set_width(ui_LabelApplySteps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelApplySteps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelApplySteps, -3);
    lv_obj_set_y(ui_LabelApplySteps, -1);
    lv_obj_set_align(ui_LabelApplySteps, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelApplySteps, "Appy Steps");

    ui_PanelFilament = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_PanelFilament, 271);
    lv_obj_set_height(ui_PanelFilament, 150);
    lv_obj_set_x(ui_PanelFilament, 15);
    lv_obj_set_y(ui_PanelFilament, 323);
    lv_obj_clear_flag(ui_PanelFilament, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelFilament, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelFilament, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelFilament, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFilDia = lv_label_create(ui_PanelFilament);
    lv_obj_set_width(ui_LabelFilDia, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFilDia, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFilDia, 1);
    lv_obj_set_y(ui_LabelFilDia, -60);
    lv_obj_set_align(ui_LabelFilDia, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFilDia, "Filament Diameter (mm)");
    lv_obj_set_style_text_color(ui_LabelFilDia, lv_color_hex(0xFCFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFilDia, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelFilDia, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFilDia, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFlow = lv_label_create(ui_PanelFilament);
    lv_obj_set_width(ui_LabelFlow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFlow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFlow, -55);
    lv_obj_set_y(ui_LabelFlow, 18);
    lv_obj_set_align(ui_LabelFlow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFlow, "Filament Flow");
    lv_obj_set_style_text_color(ui_LabelFlow, lv_color_hex(0xFBF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFlow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelFlow, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFlow, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtFilDia = lv_textarea_create(ui_PanelFilament);
    lv_obj_set_width(ui_TxtFilDia, 150);
    lv_obj_set_height(ui_TxtFilDia, 50);
    lv_obj_set_x(ui_TxtFilDia, -9);
    lv_obj_set_y(ui_TxtFilDia, -22);
    lv_obj_set_align(ui_TxtFilDia, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TxtFilDia, "1.75");
    lv_textarea_set_placeholder_text(ui_TxtFilDia, "Placeholder...");
    lv_obj_set_style_text_color(ui_TxtFilDia, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TxtFilDia, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TxtFilDia, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TxtFilDia, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderFlow = lv_slider_create(ui_PanelFilament);
    lv_slider_set_range(ui_SliderFlow, 50, 200);
    lv_slider_set_value(ui_SliderFlow, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderFlow) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderFlow, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderFlow, 230);
    lv_obj_set_height(ui_SliderFlow, 20);
    lv_obj_set_x(ui_SliderFlow, 4);
    lv_obj_set_y(ui_SliderFlow, 51);
    lv_obj_set_align(ui_SliderFlow, LV_ALIGN_CENTER);

    ui_LabelFlowValue = lv_label_create(ui_PanelFilament);
    lv_obj_set_width(ui_LabelFlowValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFlowValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFlowValue, 79);
    lv_obj_set_y(ui_LabelFlowValue, 21);
    lv_obj_set_align(ui_LabelFlowValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFlowValue, "100%");
    lv_obj_set_style_text_color(ui_LabelFlowValue, lv_color_hex(0xFC0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFlowValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFlowValue, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDisplay = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_PanelDisplay, 496);
    lv_obj_set_height(ui_PanelDisplay, 167);
    lv_obj_set_x(ui_PanelDisplay, 294);
    lv_obj_set_y(ui_PanelDisplay, 66);
    lv_obj_clear_flag(ui_PanelDisplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelDisplay, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDisplay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderBrightness = lv_slider_create(ui_PanelDisplay);
    lv_slider_set_range(ui_SliderBrightness, 10, 255);
    lv_slider_set_value(ui_SliderBrightness, 200, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBrightness, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBrightness, 245);
    lv_obj_set_height(ui_SliderBrightness, 31);
    lv_obj_set_x(ui_SliderBrightness, 72);
    lv_obj_set_y(ui_SliderBrightness, 28);

    ui_LabelBrightnessValue = lv_label_create(ui_PanelDisplay);
    lv_obj_set_width(ui_LabelBrightnessValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBrightnessValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBrightnessValue, 359);
    lv_obj_set_y(ui_LabelBrightnessValue, 14);
    lv_label_set_text(ui_LabelBrightnessValue, "200");
    lv_obj_set_style_text_color(ui_LabelBrightnessValue, lv_color_hex(0xFE0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBrightnessValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBrightnessValue, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBrightnessValue, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBrightness = lv_label_create(ui_PanelDisplay);
    lv_obj_set_width(ui_LabelBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBrightness, 112);
    lv_obj_set_y(ui_LabelBrightness, -18);
    lv_label_set_text(ui_LabelBrightness, "Display Brightness");
    lv_obj_set_style_text_color(ui_LabelBrightness, lv_color_hex(0xF2FB01), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBrightness, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBrightness, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchSound = lv_switch_create(ui_PanelDisplay);
    lv_obj_set_width(ui_SwitchSound, 85);
    lv_obj_set_height(ui_SwitchSound, 39);
    lv_obj_set_x(ui_SwitchSound, -57);
    lv_obj_set_y(ui_SwitchSound, 33);
    lv_obj_set_align(ui_SwitchSound, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchSound, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchSound, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchScreenTimeout = lv_switch_create(ui_PanelDisplay);
    lv_obj_set_width(ui_SwitchScreenTimeout, 85);
    lv_obj_set_height(ui_SwitchScreenTimeout, 39);
    lv_obj_set_x(ui_SwitchScreenTimeout, 149);
    lv_obj_set_y(ui_SwitchScreenTimeout, 27);
    lv_obj_set_align(ui_SwitchScreenTimeout, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchScreenTimeout, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchScreenTimeout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSwitchSound = lv_label_create(ui_PanelDisplay);
    lv_obj_set_width(ui_LabelSwitchSound, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSwitchSound, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSwitchSound, -144);
    lv_obj_set_y(ui_LabelSwitchSound, 34);
    lv_obj_set_align(ui_LabelSwitchSound, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitchSound, "Sound");
    lv_obj_set_style_text_color(ui_LabelSwitchSound, lv_color_hex(0xFCFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitchSound, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSwitchSound, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSwitchSound, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScreenTimeout = lv_label_create(ui_PanelDisplay);
    lv_obj_set_width(ui_LabelScreenTimeout, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScreenTimeout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelScreenTimeout, 48);
    lv_obj_set_y(ui_LabelScreenTimeout, 29);
    lv_obj_set_align(ui_LabelScreenTimeout, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScreenTimeout, "Screen \nTime Out");
    lv_obj_set_style_text_color(ui_LabelScreenTimeout, lv_color_hex(0xE7FB03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScreenTimeout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelScreenTimeout, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image17 = lv_img_create(ui_PanelDisplay);
    lv_img_set_src(ui_Image17, &ui_img_565287032);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_Image17, -184);
    lv_obj_set_y(ui_Image17, -14);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image19 = lv_img_create(ui_PanelDisplay);
    lv_img_set_src(ui_Image19, &ui_img_681280759);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image19, -208);
    lv_obj_set_y(ui_Image19, 34);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image21 = lv_img_create(ui_PanelDisplay);
    lv_img_set_src(ui_Image21, &ui_img_461506120);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Image21, 216);
    lv_obj_set_y(ui_Image21, 26);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelNetwork = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_PanelNetwork, 496);
    lv_obj_set_height(ui_PanelNetwork, 62);
    lv_obj_set_x(ui_PanelNetwork, 294);
    lv_obj_set_y(ui_PanelNetwork, 241);
    lv_obj_clear_flag(ui_PanelNetwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNetwork, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNetwork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchWiFi = lv_switch_create(ui_PanelNetwork);
    lv_obj_set_width(ui_SwitchWiFi, 85);
    lv_obj_set_height(ui_SwitchWiFi, 39);
    lv_obj_set_x(ui_SwitchWiFi, -119);
    lv_obj_set_y(ui_SwitchWiFi, -1);
    lv_obj_set_align(ui_SwitchWiFi, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SwitchWiFi, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSwitchWiFi = lv_label_create(ui_PanelNetwork);
    lv_obj_set_width(ui_LabelSwitchWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSwitchWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSwitchWiFi, -198);
    lv_obj_set_y(ui_LabelSwitchWiFi, 2);
    lv_obj_set_align(ui_LabelSwitchWiFi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSwitchWiFi, "WiFi  ");
    lv_obj_set_style_text_color(ui_LabelSwitchWiFi, lv_color_hex(0xFCFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSwitchWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSwitchWiFi, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSwitchWiFi, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtSSID = lv_textarea_create(ui_PanelNetwork);
    lv_obj_set_width(ui_TxtSSID, 150);
    lv_obj_set_height(ui_TxtSSID, 51);
    lv_obj_set_x(ui_TxtSSID, 155);
    lv_obj_set_y(ui_TxtSSID, -1);
    lv_obj_set_align(ui_TxtSSID, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TxtSSID, "SSID");
    lv_textarea_set_placeholder_text(ui_TxtSSID, "Placeholder...");
    lv_obj_set_style_text_color(ui_TxtSSID, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TxtSSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TxtSSID, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TxtSSID, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtPassword = lv_textarea_create(ui_PanelNetwork);
    lv_obj_set_width(ui_TxtPassword, 138);
    lv_obj_set_height(ui_TxtPassword, 52);
    lv_obj_set_x(ui_TxtPassword, 1);
    lv_obj_set_y(ui_TxtPassword, -1);
    lv_obj_set_align(ui_TxtPassword, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TxtPassword, "Password");
    lv_textarea_set_placeholder_text(ui_TxtPassword, "Placeholder...");
    lv_obj_set_style_text_color(ui_TxtPassword, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TxtPassword, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TxtPassword, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TxtPassword, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSystem = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_PanelSystem, 496);
    lv_obj_set_height(ui_PanelSystem, 160);
    lv_obj_set_x(ui_PanelSystem, 294);
    lv_obj_set_y(ui_PanelSystem, 311);
    lv_obj_clear_flag(ui_PanelSystem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelSystem, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSystem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSaveAll = lv_btn_create(ui_PanelSystem);
    lv_obj_set_width(ui_BtnSaveAll, 135);
    lv_obj_set_height(ui_BtnSaveAll, 78);
    lv_obj_set_x(ui_BtnSaveAll, -164);
    lv_obj_set_y(ui_BtnSaveAll, 0);
    lv_obj_set_align(ui_BtnSaveAll, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSaveAll, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSaveAll, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSaveAll, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSaveAll, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnSaveAll, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnSaveAll, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnSaveAll, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnSaveAll, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BtnSaveAll, lv_color_hex(0xFD0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnSaveAll, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnSaveAll, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnSaveAll, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_BtnSaveAll);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 0);
    lv_obj_set_y(ui_Label33, 1);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "Save All");

    ui_BtnFactoryReset = lv_btn_create(ui_PanelSystem);
    lv_obj_set_width(ui_BtnFactoryReset, 135);
    lv_obj_set_height(ui_BtnFactoryReset, 78);
    lv_obj_set_x(ui_BtnFactoryReset, 165);
    lv_obj_set_y(ui_BtnFactoryReset, 0);
    lv_obj_set_align(ui_BtnFactoryReset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnFactoryReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnFactoryReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnFactoryReset, lv_color_hex(0xFB0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnFactoryReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnFactoryReset, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnFactoryReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnFactoryReset, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnFactoryReset, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BtnFactoryReset, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnFactoryReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnFactoryReset, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnFactoryReset, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFactoryReset = lv_label_create(ui_BtnFactoryReset);
    lv_obj_set_width(ui_LabelFactoryReset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFactoryReset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFactoryReset, -1);
    lv_obj_set_y(ui_LabelFactoryReset, 15);
    lv_obj_set_align(ui_LabelFactoryReset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFactoryReset, "Reset\n");
    lv_obj_set_style_text_color(ui_LabelFactoryReset, lv_color_hex(0xFCFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFactoryReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnReboot = lv_btn_create(ui_PanelSystem);
    lv_obj_set_width(ui_BtnReboot, 135);
    lv_obj_set_height(ui_BtnReboot, 78);
    lv_obj_set_x(ui_BtnReboot, 2);
    lv_obj_set_y(ui_BtnReboot, 0);
    lv_obj_set_align(ui_BtnReboot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnReboot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnReboot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnReboot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnReboot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnReboot, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnReboot, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BtnReboot, lv_color_hex(0xFD0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnReboot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnReboot, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnReboot, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelReboot = lv_label_create(ui_BtnReboot);
    lv_obj_set_width(ui_LabelReboot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelReboot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelReboot, -1);
    lv_obj_set_y(ui_LabelReboot, 0);
    lv_obj_set_align(ui_LabelReboot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelReboot, "Reboot");

    ui_PanelNumPad = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_PanelNumPad, 400);
    lv_obj_set_height(ui_PanelNumPad, 450);
    lv_obj_set_x(ui_PanelNumPad, 200);
    lv_obj_set_y(ui_PanelNumPad, 4);
    lv_obj_add_flag(ui_PanelNumPad, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelNumPad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelNumPad, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelNumPad, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNumPad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelNumPad, lv_color_hex(0x00AAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelNumPad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelNumPad, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNumPadTitle = lv_label_create(ui_PanelNumPad);
    lv_obj_set_width(ui_LabelNumPadTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNumPadTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNumPadTitle, 0);
    lv_obj_set_y(ui_LabelNumPadTitle, -16);
    lv_label_set_text(ui_LabelNumPadTitle, "Enter New Value");
    lv_obj_set_style_text_color(ui_LabelNumPadTitle, lv_color_hex(0xFBF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNumPadTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelNumPadTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNumPadTitle, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_width(ui_LabelNumPadTitle, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_LabelNumPadTitle, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(ui_LabelNumPadTitle, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_LabelNumPadTitle, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtNumPadInput = lv_textarea_create(ui_PanelNumPad);
    lv_obj_set_width(ui_TxtNumPadInput, 360);
    lv_obj_set_height(ui_TxtNumPadInput, 60);
    lv_obj_set_x(ui_TxtNumPadInput, -1);
    lv_obj_set_y(ui_TxtNumPadInput, 10);
    lv_textarea_set_placeholder_text(ui_TxtNumPadInput, "Placeholder...");
    lv_obj_set_style_text_align(ui_TxtNumPadInput, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TxtNumPadInput, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNum7 = lv_btn_create(ui_PanelNumPad);
    lv_obj_set_width(ui_BtnNum7, 75);
    lv_obj_set_height(ui_BtnNum7, 65);
    lv_obj_set_x(ui_BtnNum7, -145);
    lv_obj_set_y(ui_BtnNum7, 80);
    lv_obj_set_align(ui_BtnNum7, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnNum7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNum7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNum7, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNum7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNum7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNum7, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNum7, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNum7 = lv_label_create(ui_BtnNum7);
    lv_obj_set_width(ui_LabelNum7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNum7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNum7, 0);
    lv_obj_set_y(ui_LabelNum7, 2);
    lv_obj_set_align(ui_LabelNum7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNum7, "7");
    lv_obj_set_style_text_align(ui_LabelNum7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNum7, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNum8 = lv_btn_create(ui_PanelNumPad);
    lv_obj_set_width(ui_BtnNum8, 75);
    lv_obj_set_height(ui_BtnNum8, 65);
    lv_obj_set_x(ui_BtnNum8, -48);
    lv_obj_set_y(ui_BtnNum8, 80);
    lv_obj_set_align(ui_BtnNum8, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnNum8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNum8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNum8, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNum8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNum8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNum8, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNum8, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNum8 = lv_label_create(ui_BtnNum8);
    lv_obj_set_width(ui_LabelNum8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNum8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNum8, 0);
    lv_obj_set_y(ui_LabelNum8, 1);
    lv_obj_set_align(ui_LabelNum8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNum8, "8");
    lv_obj_set_style_text_align(ui_LabelNum8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNum8, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNum9 = lv_btn_create(ui_PanelNumPad);
    lv_obj_set_width(ui_BtnNum9, 75);
    lv_obj_set_height(ui_BtnNum9, 65);
    lv_obj_set_x(ui_BtnNum9, 51);
    lv_obj_set_y(ui_BtnNum9, 80);
    lv_obj_set_align(ui_BtnNum9, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnNum9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNum9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNum9, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNum9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNum9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNum9, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNum9, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNum9 = lv_label_create(ui_BtnNum9);
    lv_obj_set_width(ui_LabelNum9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNum9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNum9, 0);
    lv_obj_set_y(ui_LabelNum9, 2);
    lv_obj_set_align(ui_LabelNum9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNum9, "9");
    lv_obj_set_style_text_align(ui_LabelNum9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNum9, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNum4 = lv_btn_create(ui_PanelNumPad);
    lv_obj_set_width(ui_BtnNum4, 75);
    lv_obj_set_height(ui_BtnNum4, 65);
    lv_obj_set_x(ui_BtnNum4, -145);
    lv_obj_set_y(ui_BtnNum4, 170);
    lv_obj_set_align(ui_BtnNum4, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnNum4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNum4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNum4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNum4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNum4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNum4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNum4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNum4 = lv_label_create(ui_BtnNum4);
    lv_obj_set_width(ui_LabelNum4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNum4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNum4, 0);
    lv_obj_set_y(ui_LabelNum4, 2);
    lv_obj_set_align(ui_LabelNum4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNum4, "4");
    lv_obj_set_style_text_align(ui_LabelNum4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNum4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNum5 = lv_btn_create(ui_PanelNumPad);
    lv_obj_set_width(ui_BtnNum5, 75);
    lv_obj_set_height(ui_BtnNum5, 65);
    lv_obj_set_x(ui_BtnNum5, -48);
    lv_obj_set_y(ui_BtnNum5, 170);
    lv_obj_set_align(ui_BtnNum5, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnNum5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNum5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNum5, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNum5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNum5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNum5, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNum5, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNum5 = lv_label_create(ui_BtnNum5);
    lv_obj_set_width(ui_LabelNum5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNum5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNum5, 0);
    lv_obj_set_y(ui_LabelNum5, 2);
    lv_obj_set_align(ui_LabelNum5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNum5, "5");
    lv_obj_set_style_text_align(ui_LabelNum5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNum5, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNum6 = lv_btn_create(ui_PanelNumPad);
    lv_obj_set_width(ui_BtnNum6, 75);
    lv_obj_set_height(ui_BtnNum6, 65);
    lv_obj_set_x(ui_BtnNum6, 51);
    lv_obj_set_y(ui_BtnNum6, 170);
    lv_obj_set_align(ui_BtnNum6, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnNum6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNum6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNum6, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNum6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNum6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNum6, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNum6, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNum6 = lv_label_create(ui_BtnNum6);
    lv_obj_set_width(ui_LabelNum6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNum6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNum6, 0);
    lv_obj_set_y(ui_LabelNum6, 2);
    lv_obj_set_align(ui_LabelNum6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNum6, "6");
    lv_obj_set_style_text_align(ui_LabelNum6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNum6, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNum1 = lv_btn_create(ui_PanelNumPad);
    lv_obj_set_width(ui_BtnNum1, 75);
    lv_obj_set_height(ui_BtnNum1, 65);
    lv_obj_set_x(ui_BtnNum1, -145);
    lv_obj_set_y(ui_BtnNum1, 260);
    lv_obj_set_align(ui_BtnNum1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnNum1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNum1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNum1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNum1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNum1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNum1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNum1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNum1 = lv_label_create(ui_BtnNum1);
    lv_obj_set_width(ui_LabelNum1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNum1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNum1, 0);
    lv_obj_set_y(ui_LabelNum1, 2);
    lv_obj_set_align(ui_LabelNum1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNum1, "1");
    lv_obj_set_style_text_align(ui_LabelNum1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNum1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNum2 = lv_btn_create(ui_PanelNumPad);
    lv_obj_set_width(ui_BtnNum2, 75);
    lv_obj_set_height(ui_BtnNum2, 65);
    lv_obj_set_x(ui_BtnNum2, -48);
    lv_obj_set_y(ui_BtnNum2, 260);
    lv_obj_set_align(ui_BtnNum2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnNum2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNum2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNum2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNum2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNum2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNum2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNum2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNum2 = lv_label_create(ui_BtnNum2);
    lv_obj_set_width(ui_LabelNum2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNum2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNum2, 0);
    lv_obj_set_y(ui_LabelNum2, 2);
    lv_obj_set_align(ui_LabelNum2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNum2, "2");
    lv_obj_set_style_text_align(ui_LabelNum2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNum2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNum3 = lv_btn_create(ui_PanelNumPad);
    lv_obj_set_width(ui_BtnNum3, 75);
    lv_obj_set_height(ui_BtnNum3, 65);
    lv_obj_set_x(ui_BtnNum3, 51);
    lv_obj_set_y(ui_BtnNum3, 260);
    lv_obj_set_align(ui_BtnNum3, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnNum3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNum3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNum3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNum3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNum3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNum3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNum3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNum3 = lv_label_create(ui_BtnNum3);
    lv_obj_set_width(ui_LabelNum3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNum3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNum3, 0);
    lv_obj_set_y(ui_LabelNum3, 2);
    lv_obj_set_align(ui_LabelNum3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNum3, "3");
    lv_obj_set_style_text_align(ui_LabelNum3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNum3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNum0 = lv_btn_create(ui_PanelNumPad);
    lv_obj_set_width(ui_BtnNum0, 75);
    lv_obj_set_height(ui_BtnNum0, 65);
    lv_obj_set_x(ui_BtnNum0, -145);
    lv_obj_set_y(ui_BtnNum0, 350);
    lv_obj_set_align(ui_BtnNum0, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnNum0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNum0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNum0, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNum0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNum0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNum0, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNum0, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNum0 = lv_label_create(ui_BtnNum0);
    lv_obj_set_width(ui_LabelNum0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNum0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNum0, 0);
    lv_obj_set_y(ui_LabelNum0, 2);
    lv_obj_set_align(ui_LabelNum0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNum0, "0");
    lv_obj_set_style_text_align(ui_LabelNum0, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNum0, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNumDecimal = lv_btn_create(ui_PanelNumPad);
    lv_obj_set_width(ui_BtnNumDecimal, 75);
    lv_obj_set_height(ui_BtnNumDecimal, 65);
    lv_obj_set_x(ui_BtnNumDecimal, -48);
    lv_obj_set_y(ui_BtnNumDecimal, 350);
    lv_obj_set_align(ui_BtnNumDecimal, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnNumDecimal, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNumDecimal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNumDecimal, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNumDecimal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNumDecimal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNumDecimal, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNumDecimal, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNumDecimal = lv_label_create(ui_BtnNumDecimal);
    lv_obj_set_width(ui_LabelNumDecimal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNumDecimal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNumDecimal, 1);
    lv_obj_set_y(ui_LabelNumDecimal, -13);
    lv_obj_set_align(ui_LabelNumDecimal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNumDecimal, ".");
    lv_obj_set_style_text_align(ui_LabelNumDecimal, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNumDecimal, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNumENTER = lv_btn_create(ui_PanelNumPad);
    lv_obj_set_width(ui_BtnNumENTER, 160);
    lv_obj_set_height(ui_BtnNumENTER, 63);
    lv_obj_set_x(ui_BtnNumENTER, 100);
    lv_obj_set_y(ui_BtnNumENTER, 350);
    lv_obj_set_align(ui_BtnNumENTER, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnNumENTER, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNumENTER, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNumENTER, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnNumENTER, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNumENTER, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNumENTER, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNumENTER, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNumENTER, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNumENTER, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNumEnter = lv_label_create(ui_BtnNumENTER);
    lv_obj_set_width(ui_LabelNumEnter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNumEnter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNumEnter, 0);
    lv_obj_set_y(ui_LabelNumEnter, 2);
    lv_obj_set_align(ui_LabelNumEnter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNumEnter, "ENTER");
    lv_obj_set_style_text_align(ui_LabelNumEnter, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNumEnter, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNumBackspace = lv_btn_create(ui_PanelNumPad);
    lv_obj_set_width(ui_BtnNumBackspace, 75);
    lv_obj_set_height(ui_BtnNumBackspace, 65);
    lv_obj_set_x(ui_BtnNumBackspace, 149);
    lv_obj_set_y(ui_BtnNumBackspace, 81);
    lv_obj_set_align(ui_BtnNumBackspace, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnNumBackspace, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNumBackspace, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNumBackspace, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNumBackspace, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNumBackspace, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNumBackspace, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNumBackspace, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNumBackspace = lv_label_create(ui_BtnNumBackspace);
    lv_obj_set_width(ui_LabelNumBackspace, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNumBackspace, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNumBackspace, 0);
    lv_obj_set_y(ui_LabelNumBackspace, 2);
    lv_obj_set_align(ui_LabelNumBackspace, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNumBackspace, "<");
    lv_obj_set_style_text_align(ui_LabelNumBackspace, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNumBackspace, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNumClear = lv_btn_create(ui_PanelNumPad);
    lv_obj_set_width(ui_BtnNumClear, 75);
    lv_obj_set_height(ui_BtnNumClear, 65);
    lv_obj_set_x(ui_BtnNumClear, 149);
    lv_obj_set_y(ui_BtnNumClear, 170);
    lv_obj_set_align(ui_BtnNumClear, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnNumClear, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNumClear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNumClear, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnNumClear, lv_color_hex(0x0603F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNumClear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNumClear, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNumClear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNumClear, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNumClear, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNumClear = lv_label_create(ui_BtnNumClear);
    lv_obj_set_width(ui_LabelNumClear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNumClear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNumClear, 0);
    lv_obj_set_y(ui_LabelNumClear, 2);
    lv_obj_set_align(ui_LabelNumClear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNumClear, "clear");
    lv_obj_set_style_text_align(ui_LabelNumClear, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNumClear, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNumCancel = lv_btn_create(ui_PanelNumPad);
    lv_obj_set_width(ui_BtnNumCancel, 75);
    lv_obj_set_height(ui_BtnNumCancel, 65);
    lv_obj_set_x(ui_BtnNumCancel, 149);
    lv_obj_set_y(ui_BtnNumCancel, 260);
    lv_obj_set_align(ui_BtnNumCancel, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnNumCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNumCancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNumCancel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnNumCancel, lv_color_hex(0xEF1010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNumCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNumCancel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNumCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNumCancel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNumCancel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNumCancel = lv_label_create(ui_BtnNumCancel);
    lv_obj_set_width(ui_LabelNumCancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNumCancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNumCancel, 0);
    lv_obj_set_y(ui_LabelNumCancel, 2);
    lv_obj_set_align(ui_LabelNumCancel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNumCancel, "cancel");
    lv_obj_set_style_text_align(ui_LabelNumCancel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNumCancel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnAbout, ui_event_BtnAbout, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnBack5, ui_event_BtnBack5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TxtXSteps, ui_event_TxtXSteps, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TxtYSteps, ui_event_TxtYSteps, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TxtZSteps, ui_event_TxtZSteps, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TxtE0Steps, ui_event_TxtE0Steps, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnApplySteps, ui_event_BtnApplySteps, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TxtFilDia, ui_event_TxtFilDia, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderFlow, ui_event_SliderFlow, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBrightness, ui_event_SliderBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchSound, ui_event_SwitchSound, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchScreenTimeout, ui_event_SwitchScreenTimeout, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchWiFi, ui_event_SwitchWiFi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TxtSSID, ui_event_TxtSSID, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TxtPassword, ui_event_TxtPassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSaveAll, ui_event_BtnSaveAll, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnFactoryReset, ui_event_BtnFactoryReset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNum7, ui_event_BtnNum7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNum8, ui_event_BtnNum8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNum9, ui_event_BtnNum9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNum4, ui_event_BtnNum4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNum5, ui_event_BtnNum5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNum6, ui_event_BtnNum6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNum1, ui_event_BtnNum1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNum2, ui_event_BtnNum2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNum3, ui_event_BtnNum3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNum0, ui_event_BtnNum0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNumDecimal, ui_event_BtnNumDecimal, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNumENTER, ui_event_BtnNumENTER, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNumBackspace, ui_event_BtnNumBackspace, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNumClear, ui_event_BtnNumClear, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNumCancel, ui_event_BtnNumCancel, LV_EVENT_ALL, NULL);
    ui_ScreenSettings = ui_ScreenSettings;
    ui_LabelTitleSettings = ui_LabelTitleSettings;
    ui_BtnAbout = ui_BtnAbout;
    ui_LabelAbout = ui_LabelAbout;
    ui_BtnBack5 = ui_BtnBack5;
    ui_LabelBack5 = ui_LabelBack5;
    ui_PanelSteps = ui_PanelSteps;
    ui_LabelStepsTitle = ui_LabelStepsTitle;
    ui_TxtXSteps = ui_TxtXSteps;
    ui_TxtYSteps = ui_TxtYSteps;
    ui_TxtZSteps = ui_TxtZSteps;
    ui_TxtE0Steps = ui_TxtE0Steps;
    ui_LabelXSteps = ui_LabelXSteps;
    ui_LabelYSteps = ui_LabelYSteps;
    ui_LabelZSteps = ui_LabelZSteps;
    ui_LabelE0Steps = ui_LabelE0Steps;
    ui_BtnApplySteps = ui_BtnApplySteps;
    ui_LabelApplySteps = ui_LabelApplySteps;
    ui_PanelFilament = ui_PanelFilament;
    ui_LabelFilDia = ui_LabelFilDia;
    ui_TxtFilDia = ui_TxtFilDia;
    ui_SliderFlow = ui_SliderFlow;
    ui_LabelFlowValue = ui_LabelFlowValue;
    ui_PanelDisplay = ui_PanelDisplay;
    ui_SliderBrightness = ui_SliderBrightness;
    ui_LabelBrightnessValue = ui_LabelBrightnessValue;
    ui_LabelBrightness = ui_LabelBrightness;
    ui_SwitchSound = ui_SwitchSound;
    ui_SwitchScreenTimeout = ui_SwitchScreenTimeout;
    ui_LabelSwitchSound = ui_LabelSwitchSound;
    ui_LabelScreenTimeout = ui_LabelScreenTimeout;
    ui_PanelNetwork = ui_PanelNetwork;
    ui_SwitchWiFi = ui_SwitchWiFi;
    ui_LabelSwitchWiFi = ui_LabelSwitchWiFi;
    ui_TxtSSID = ui_TxtSSID;
    ui_TxtPassword = ui_TxtPassword;
    ui_PanelSystem = ui_PanelSystem;
    ui_BtnSaveAll = ui_BtnSaveAll;
    ui_LabelFactoryReset = ui_LabelFactoryReset;
    ui_BtnReboot = ui_BtnReboot;
    ui_LabelReboot = ui_LabelReboot;
    ui_PanelNumPad = ui_PanelNumPad;
    ui_LabelNumPadTitle = ui_LabelNumPadTitle;
    ui_TxtNumPadInput = ui_TxtNumPadInput;
    ui_BtnNum7 = ui_BtnNum7;
    ui_LabelNum7 = ui_LabelNum7;
    ui_BtnNum8 = ui_BtnNum8;
    ui_BtnNum9 = ui_BtnNum9;
    ui_BtnNum4 = ui_BtnNum4;
    ui_LabelNum4 = ui_LabelNum4;
    ui_BtnNum5 = ui_BtnNum5;
    ui_LabelNum5 = ui_LabelNum5;
    ui_BtnNum6 = ui_BtnNum6;
    ui_LabelNum6 = ui_LabelNum6;
    ui_BtnNum1 = ui_BtnNum1;
    ui_LabelNum1 = ui_LabelNum1;
    ui_BtnNum2 = ui_BtnNum2;
    ui_LabelNum2 = ui_LabelNum2;
    ui_BtnNum3 = ui_BtnNum3;
    ui_LabelNum3 = ui_LabelNum3;
    ui_BtnNum0 = ui_BtnNum0;
    ui_BtnNumDecimal = ui_BtnNumDecimal;
    ui_LabelNumDecimal = ui_LabelNumDecimal;
    ui_BtnNumENTER = ui_BtnNumENTER;
    ui_LabelNumEnter = ui_LabelNumEnter;
    ui_BtnNumBackspace = ui_BtnNumBackspace;
    ui_LabelNumBackspace = ui_LabelNumBackspace;
    ui_BtnNumClear = ui_BtnNumClear;
    ui_LabelNumClear = ui_LabelNumClear;
    ui_BtnNumCancel = ui_BtnNumCancel;
    ui_LabelNumCancel = ui_LabelNumCancel;

}

void ui_ScreenSettings_screen_destroy(void)
{
    if(ui_ScreenSettings) lv_obj_del(ui_ScreenSettings);

    // NULL screen variables
    ui_ScreenSettings = NULL;
    ui_ScreenSettings = NULL;
    ui_Panel5 = NULL;
    ui_LabelTitleSettings = NULL;
    ui_LabelTitleSettings = NULL;
    ui_BtnAbout = NULL;
    ui_BtnAbout = NULL;
    ui_LabelAbout = NULL;
    ui_LabelAbout = NULL;
    ui_BtnBack5 = NULL;
    ui_BtnBack5 = NULL;
    ui_LabelBack5 = NULL;
    ui_LabelBack5 = NULL;
    ui_PanelSteps = NULL;
    ui_PanelSteps = NULL;
    ui_LabelStepsTitle = NULL;
    ui_LabelStepsTitle = NULL;
    ui_TxtXSteps = NULL;
    ui_TxtXSteps = NULL;
    ui_TxtYSteps = NULL;
    ui_TxtYSteps = NULL;
    ui_TxtZSteps = NULL;
    ui_TxtZSteps = NULL;
    ui_TxtE0Steps = NULL;
    ui_TxtE0Steps = NULL;
    ui_LabelXSteps = NULL;
    ui_LabelXSteps = NULL;
    ui_LabelYSteps = NULL;
    ui_LabelYSteps = NULL;
    ui_LabelZSteps = NULL;
    ui_LabelZSteps = NULL;
    ui_LabelE0Steps = NULL;
    ui_LabelE0Steps = NULL;
    ui_BtnApplySteps = NULL;
    ui_BtnApplySteps = NULL;
    ui_LabelApplySteps = NULL;
    ui_LabelApplySteps = NULL;
    ui_PanelFilament = NULL;
    ui_PanelFilament = NULL;
    ui_LabelFilDia = NULL;
    ui_LabelFilDia = NULL;
    ui_LabelFlow = NULL;
    ui_TxtFilDia = NULL;
    ui_TxtFilDia = NULL;
    ui_SliderFlow = NULL;
    ui_SliderFlow = NULL;
    ui_LabelFlowValue = NULL;
    ui_LabelFlowValue = NULL;
    ui_PanelDisplay = NULL;
    ui_PanelDisplay = NULL;
    ui_SliderBrightness = NULL;
    ui_SliderBrightness = NULL;
    ui_LabelBrightnessValue = NULL;
    ui_LabelBrightnessValue = NULL;
    ui_LabelBrightness = NULL;
    ui_LabelBrightness = NULL;
    ui_SwitchSound = NULL;
    ui_SwitchSound = NULL;
    ui_SwitchScreenTimeout = NULL;
    ui_SwitchScreenTimeout = NULL;
    ui_LabelSwitchSound = NULL;
    ui_LabelSwitchSound = NULL;
    ui_LabelScreenTimeout = NULL;
    ui_LabelScreenTimeout = NULL;
    ui_Image17 = NULL;
    ui_Image19 = NULL;
    ui_Image21 = NULL;
    ui_PanelNetwork = NULL;
    ui_PanelNetwork = NULL;
    ui_SwitchWiFi = NULL;
    ui_SwitchWiFi = NULL;
    ui_LabelSwitchWiFi = NULL;
    ui_LabelSwitchWiFi = NULL;
    ui_TxtSSID = NULL;
    ui_TxtSSID = NULL;
    ui_TxtPassword = NULL;
    ui_TxtPassword = NULL;
    ui_PanelSystem = NULL;
    ui_PanelSystem = NULL;
    ui_BtnSaveAll = NULL;
    ui_BtnSaveAll = NULL;
    ui_Label33 = NULL;
    ui_BtnFactoryReset = NULL;
    ui_LabelFactoryReset = NULL;
    ui_LabelFactoryReset = NULL;
    ui_BtnReboot = NULL;
    ui_BtnReboot = NULL;
    ui_LabelReboot = NULL;
    ui_LabelReboot = NULL;
    ui_PanelNumPad = NULL;
    ui_PanelNumPad = NULL;
    ui_LabelNumPadTitle = NULL;
    ui_LabelNumPadTitle = NULL;
    ui_TxtNumPadInput = NULL;
    ui_TxtNumPadInput = NULL;
    ui_BtnNum7 = NULL;
    ui_BtnNum7 = NULL;
    ui_LabelNum7 = NULL;
    ui_LabelNum7 = NULL;
    ui_BtnNum8 = NULL;
    ui_BtnNum8 = NULL;
    ui_LabelNum8 = NULL;
    ui_BtnNum9 = NULL;
    ui_BtnNum9 = NULL;
    ui_LabelNum9 = NULL;
    ui_BtnNum4 = NULL;
    ui_BtnNum4 = NULL;
    ui_LabelNum4 = NULL;
    ui_LabelNum4 = NULL;
    ui_BtnNum5 = NULL;
    ui_BtnNum5 = NULL;
    ui_LabelNum5 = NULL;
    ui_LabelNum5 = NULL;
    ui_BtnNum6 = NULL;
    ui_BtnNum6 = NULL;
    ui_LabelNum6 = NULL;
    ui_LabelNum6 = NULL;
    ui_BtnNum1 = NULL;
    ui_BtnNum1 = NULL;
    ui_LabelNum1 = NULL;
    ui_LabelNum1 = NULL;
    ui_BtnNum2 = NULL;
    ui_BtnNum2 = NULL;
    ui_LabelNum2 = NULL;
    ui_LabelNum2 = NULL;
    ui_BtnNum3 = NULL;
    ui_BtnNum3 = NULL;
    ui_LabelNum3 = NULL;
    ui_LabelNum3 = NULL;
    ui_BtnNum0 = NULL;
    ui_BtnNum0 = NULL;
    ui_LabelNum0 = NULL;
    ui_BtnNumDecimal = NULL;
    ui_BtnNumDecimal = NULL;
    ui_LabelNumDecimal = NULL;
    ui_LabelNumDecimal = NULL;
    ui_BtnNumENTER = NULL;
    ui_BtnNumENTER = NULL;
    ui_LabelNumEnter = NULL;
    ui_LabelNumEnter = NULL;
    ui_BtnNumBackspace = NULL;
    ui_BtnNumBackspace = NULL;
    ui_LabelNumBackspace = NULL;
    ui_LabelNumBackspace = NULL;
    ui_BtnNumClear = NULL;
    ui_BtnNumClear = NULL;
    ui_LabelNumClear = NULL;
    ui_LabelNumClear = NULL;
    ui_BtnNumCancel = NULL;
    ui_BtnNumCancel = NULL;
    ui_LabelNumCancel = NULL;
    ui_LabelNumCancel = NULL;

}
