// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#ifndef UI_SCREENMAIN_H
#define UI_SCREENMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMain
extern void ui_ScreenMain_screen_init(void);
extern void ui_ScreenMain_screen_destroy(void);
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_PanelTopNav;
extern lv_obj_t * ui_LabelPrinterName;
extern lv_obj_t * ui_LabelHotendSmall;
extern lv_obj_t * ui_LabelBedSmall;
extern lv_obj_t * ui_LabelFilamentMain;
extern void ui_event_BtnPrintStatus(lv_event_t * e);
extern lv_obj_t * ui_BtnPrintStatus;
extern lv_obj_t * ui_LabelPrintStatus;
extern void ui_event_BtnJog(lv_event_t * e);
extern lv_obj_t * ui_BtnJog;
extern lv_obj_t * ui_LabelJogLevel;
extern lv_obj_t * ui_Image3;
extern void ui_event_BtnFiles(lv_event_t * e);
extern lv_obj_t * ui_BtnFiles;
extern lv_obj_t * ui_LabelFiles;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image20;
extern void ui_event_BtnTemperature(lv_event_t * e);
extern lv_obj_t * ui_BtnTemperature;
extern lv_obj_t * ui_LabelTemperature;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Image24;
extern void ui_event_BtnTMC(lv_event_t * e);
extern lv_obj_t * ui_BtnTMC;
extern void ui_event_BtnFilament(lv_event_t * e);
extern lv_obj_t * ui_BtnFilament;
extern void ui_event_BtnSettings(lv_event_t * e);
extern lv_obj_t * ui_BtnSettings;
extern lv_obj_t * ui_LabelTMCDrivers;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_LabelFilament;
extern lv_obj_t * ui_Image26;
extern lv_obj_t * ui_LabelSettings;
extern lv_obj_t * ui_Image28;
extern void ui_event_BtnShutDown(lv_event_t * e);
extern lv_obj_t * ui_BtnShutDown;
extern lv_obj_t * ui_LabelShutDown;
extern lv_obj_t * ui_Image18;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_uiPanelTopBar;
extern lv_obj_t * ui_LabelPrinterName;
extern lv_obj_t * ui_LabelHotendSmall;
extern lv_obj_t * ui_LabelBedSmall;
extern lv_obj_t * ui_LabelFilamentMain;
extern lv_obj_t * ui_BtnPrintStatus;
extern lv_obj_t * ui_LabelPrintStatus;
extern lv_obj_t * ui_BtnJog;
extern lv_obj_t * ui_LabelJogLevel;
extern lv_obj_t * ui_BtnFiles;
extern lv_obj_t * ui_LabelFiles;
extern lv_obj_t * ui_BtnTemperature;
extern lv_obj_t * ui_LabelTemperature;
extern lv_obj_t * ui_BtnTMC;
extern lv_obj_t * ui_BtnFilament;
extern lv_obj_t * ui_BtnSettings;
extern lv_obj_t * ui_LabelTMCDrivers;
extern lv_obj_t * ui_LabelFilament;
extern lv_obj_t * ui_LabelSettings;
extern lv_obj_t * ui_BtnShutDown;
extern lv_obj_t * ui_LabelShutDown;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

