// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#include "ui.h"

lv_obj_t * ui_LabelPrintProgress;
lv_obj_t * ui_LabelBack;
lv_obj_t * ui_BtnBack;
lv_obj_t * ui_SpeedControl;
lv_obj_t * ui_LabelSpeedValue;
lv_obj_t * ui_SliderSpeed;
lv_obj_t * ui_Stop;
lv_obj_t * ui_BtnStop;
lv_obj_t * ui_Pause;
lv_obj_t * ui_BtnPauseResume;
lv_obj_t * ui_LabelSpeed;
lv_obj_t * ui_LabelRemaining;
lv_obj_t * ui_LabelElapsed;
lv_obj_t * ui_LabelZHeight;
lv_obj_t * ui_LabelLayer;
lv_obj_t * ui_BarBed;
lv_obj_t * ui_LabelBed;
lv_obj_t * ui_LabelBedTitle;
lv_obj_t * ui_BarHotend;
lv_obj_t * ui_LabelHotend;
lv_obj_t * ui_LabelHotendTitle;
lv_obj_t * ui_LabelBigPercent;
lv_obj_t * ui_ArcOverall;
lv_obj_t * ui_LabelProgressPercent;
lv_obj_t * ui_LabelState;
lv_obj_t * ui_LabelFilename;
lv_obj_t * ui_uiPanelTopBar1;
lv_obj_t * ui_ScreenPrintStatus;
lv_obj_t * ui_ScreenPrintStatus = NULL;
lv_obj_t * ui_PanelTopNav2 = NULL;
lv_obj_t * ui_LabelFilename = NULL;
lv_obj_t * ui_LabelState = NULL;
lv_obj_t * ui_LabelProgressPercent = NULL;
lv_obj_t * ui_ArcOverall = NULL;
lv_obj_t * ui_LabelBigPercent = NULL;
lv_obj_t * ui_LabelHotendTitle = NULL;
lv_obj_t * ui_LabelHotend = NULL;
lv_obj_t * ui_BarHotend = NULL;
lv_obj_t * ui_LabelBedTitle = NULL;
lv_obj_t * ui_LabelBed = NULL;
lv_obj_t * ui_BarBed = NULL;
lv_obj_t * ui_LabelLayer = NULL;
lv_obj_t * ui_LabelZHeight = NULL;
lv_obj_t * ui_LabelElapsed = NULL;
lv_obj_t * ui_LabelRemaining = NULL;
lv_obj_t * ui_LabelSpeed = NULL;
lv_obj_t * ui_BtnPauseResume = NULL;
lv_obj_t * ui_Pause = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_BtnStop = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Stop = NULL;
lv_obj_t * ui_SliderSpeed = NULL;
lv_obj_t * ui_LabelSpeedValue = NULL;
lv_obj_t * ui_SpeedControl = NULL;
lv_obj_t * ui_BtnBack = NULL;
lv_obj_t * ui_LabelBack = NULL;
lv_obj_t * ui_LabelPrintProgress = NULL;
// event funtions
void ui_event_ArcOverall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventArcOverall(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelBigPercent, target, "", "");
    }
}

void ui_event_BarHotend(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_event_BarHotend(e);
    }
}

void ui_event_BarBed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBarBed(e);
    }
}

void ui_event_BtnPauseResume(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnPauseResume(e);
    }
}

void ui_event_BtnStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnStop(e);
    }
}

void ui_event_SliderSpeed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventSliderSpeed(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelSpeedValue, target, "", "");
    }
}

void ui_event_BtnBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
    }
}

// build funtions

void ui_ScreenPrintStatus_screen_init(void)
{
    ui_ScreenPrintStatus = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPrintStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenPrintStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenPrintStatus, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPrintStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTopNav2 = lv_obj_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_PanelTopNav2, 800);
    lv_obj_set_height(ui_PanelTopNav2, 70);
    lv_obj_set_x(ui_PanelTopNav2, 0);
    lv_obj_set_y(ui_PanelTopNav2, -1);
    lv_obj_clear_flag(ui_PanelTopNav2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTopNav2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTopNav2, lv_color_hex(0x121212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTopNav2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFilename = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelFilename, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFilename, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFilename, 20);
    lv_obj_set_y(ui_LabelFilename, 15);
    lv_label_set_text(ui_LabelFilename, "filename.gcode");
    lv_obj_set_style_text_color(ui_LabelFilename, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFilename, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFilename, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelState = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelState, 321);
    lv_obj_set_y(ui_LabelState, 18);
    lv_label_set_text(ui_LabelState, "PRINTING");
    lv_obj_set_style_text_color(ui_LabelState, lv_color_hex(0x00FF88), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelState, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelProgressPercent = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelProgressPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelProgressPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelProgressPercent, 463);
    lv_obj_set_y(ui_LabelProgressPercent, 21);
    lv_label_set_text(ui_LabelProgressPercent, "68%");
    lv_obj_set_style_text_color(ui_LabelProgressPercent, lv_color_hex(0xFF8900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelProgressPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelProgressPercent, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcOverall = lv_arc_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_ArcOverall, 220);
    lv_obj_set_height(ui_ArcOverall, 220);
    lv_obj_set_x(ui_ArcOverall, 40);
    lv_obj_set_y(ui_ArcOverall, 100);
    lv_arc_set_value(ui_ArcOverall, 50);
    lv_arc_set_bg_angles(ui_ArcOverall, 135, 45);
    lv_obj_set_style_bg_color(ui_ArcOverall, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcOverall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_ArcOverall, lv_color_hex(0x00AAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcOverall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcOverall, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcOverall, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcOverall, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcOverall, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcOverall, lv_color_hex(0x4040FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcOverall, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ArcOverall, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelBigPercent = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelBigPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBigPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBigPercent, 110);
    lv_obj_set_y(ui_LabelBigPercent, 165);
    lv_label_set_text(ui_LabelBigPercent, "68%");
    lv_obj_set_style_text_color(ui_LabelBigPercent, lv_color_hex(0xFD0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBigPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBigPercent, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBigPercent, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHotendTitle = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelHotendTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHotendTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHotendTitle, 333);
    lv_obj_set_y(ui_LabelHotendTitle, 110);
    lv_label_set_text(ui_LabelHotendTitle, "HotEnd\n");
    lv_obj_set_style_text_color(ui_LabelHotendTitle, lv_color_hex(0xFF8800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHotendTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHotendTitle, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHotend = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelHotend, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHotend, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHotend, 350);
    lv_obj_set_y(ui_LabelHotend, 140);
    lv_label_set_text(ui_LabelHotend, "210°C");
    lv_obj_set_style_text_color(ui_LabelHotend, lv_color_hex(0xFC0404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHotend, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHotend, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarHotend = lv_bar_create(ui_ScreenPrintStatus);
    lv_bar_set_range(ui_BarHotend, 0, 260);
    lv_bar_set_value(ui_BarHotend, 210, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarHotend, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarHotend, 220);
    lv_obj_set_height(ui_BarHotend, 29);
    lv_obj_set_x(ui_BarHotend, 320);
    lv_obj_set_y(ui_BarHotend, 185);
    lv_obj_set_style_bg_color(ui_BarHotend, lv_color_hex(0xFF8800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarHotend, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BarHotend, lv_color_hex(0x4140FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarHotend, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelBedTitle = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelBedTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBedTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBedTitle, 340);
    lv_obj_set_y(ui_LabelBedTitle, 230);
    lv_label_set_text(ui_LabelBedTitle, "Bed");
    lv_obj_set_style_text_color(ui_LabelBedTitle, lv_color_hex(0x4488FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBedTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBedTitle, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBed = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelBed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBed, 350);
    lv_obj_set_y(ui_LabelBed, 260);
    lv_label_set_text(ui_LabelBed, "60°C");
    lv_obj_set_style_text_color(ui_LabelBed, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBed, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarBed = lv_bar_create(ui_ScreenPrintStatus);
    lv_bar_set_range(ui_BarBed, 0, 120);
    lv_bar_set_value(ui_BarBed, 60, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarBed, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BarBed, 220);
    lv_obj_set_height(ui_BarBed, 30);
    lv_obj_set_x(ui_BarBed, 320);
    lv_obj_set_y(ui_BarBed, 305);
    lv_obj_set_style_bg_color(ui_BarBed, lv_color_hex(0x4488FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BarBed, lv_color_hex(0x4140FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarBed, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LabelLayer = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelLayer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLayer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLayer, 580);
    lv_obj_set_y(ui_LabelLayer, 110);
    lv_label_set_text(ui_LabelLayer, "Layer 142 / 385");
    lv_obj_set_style_text_align(ui_LabelLayer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLayer, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelZHeight = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelZHeight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelZHeight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelZHeight, 580);
    lv_obj_set_y(ui_LabelZHeight, 155);
    lv_label_set_text(ui_LabelZHeight, "Z: 45.80 mm");
    lv_obj_set_style_text_align(ui_LabelZHeight, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelZHeight, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelElapsed = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelElapsed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelElapsed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelElapsed, 580);
    lv_obj_set_y(ui_LabelElapsed, 200);
    lv_label_set_text(ui_LabelElapsed, "Elapsed: 02h 45m");
    lv_obj_set_style_text_align(ui_LabelElapsed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelElapsed, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRemaining = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelRemaining, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRemaining, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRemaining, 580);
    lv_obj_set_y(ui_LabelRemaining, 245);
    lv_label_set_text(ui_LabelRemaining, "Remain: 03h 12m\n");
    lv_obj_set_style_text_align(ui_LabelRemaining, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRemaining, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSpeed = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeed, 580);
    lv_obj_set_y(ui_LabelSpeed, 290);
    lv_label_set_text(ui_LabelSpeed, "Speed: 100%");
    lv_obj_set_style_text_align(ui_LabelSpeed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeed, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPauseResume = lv_btn_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_BtnPauseResume, 160);
    lv_obj_set_height(ui_BtnPauseResume, 70);
    lv_obj_set_x(ui_BtnPauseResume, 40);
    lv_obj_set_y(ui_BtnPauseResume, 390);
    lv_obj_add_flag(ui_BtnPauseResume, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPauseResume, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnPauseResume, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnPauseResume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnPauseResume, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnPauseResume, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BtnPauseResume, lv_color_hex(0xFCF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnPauseResume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnPauseResume, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnPauseResume, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pause = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_Pause, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Pause, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Pause, 80);
    lv_obj_set_y(ui_Pause, 350);
    lv_label_set_text(ui_Pause, "PAUSE");
    lv_obj_set_style_text_color(ui_Pause, lv_color_hex(0xFFAA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Pause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Pause, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Pause, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_ScreenPrintStatus);
    lv_img_set_src(ui_Image4, &ui_img_1983858668);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image4, -282);
    lv_obj_set_y(ui_Image4, 185);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnStop = lv_btn_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_BtnStop, 160);
    lv_obj_set_height(ui_BtnStop, 70);
    lv_obj_set_x(ui_BtnStop, 225);
    lv_obj_set_y(ui_BtnStop, 390);
    lv_obj_add_flag(ui_BtnStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnStop, lv_color_hex(0xFF3333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnStop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnStop, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnStop, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_ScreenPrintStatus);
    lv_img_set_src(ui_Image5, &ui_img_931356233);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image5, -96);
    lv_obj_set_y(ui_Image5, 185);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Stop = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_Stop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Stop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Stop, 274);
    lv_obj_set_y(ui_Stop, 350);
    lv_label_set_text(ui_Stop, "STOP");
    lv_obj_set_style_text_color(ui_Stop, lv_color_hex(0xC50807), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Stop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Stop, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Stop, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSpeed = lv_slider_create(ui_ScreenPrintStatus);
    lv_slider_set_range(ui_SliderSpeed, 50, 200);
    lv_slider_set_value(ui_SliderSpeed, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSpeed) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSpeed, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSpeed, 180);
    lv_obj_set_height(ui_SliderSpeed, 30);
    lv_obj_set_x(ui_SliderSpeed, 430);
    lv_obj_set_y(ui_SliderSpeed, 410);
    lv_obj_set_style_bg_color(ui_SliderSpeed, lv_color_hex(0x00AAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSpeed, lv_color_hex(0x4140FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSpeed, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSpeedValue = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelSpeedValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeedValue, 650);
    lv_obj_set_y(ui_LabelSpeedValue, 400);
    lv_label_set_text(ui_LabelSpeedValue, "100%");
    lv_obj_set_style_text_color(ui_LabelSpeedValue, lv_color_hex(0x4140FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeedValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeedValue, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedControl = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_SpeedControl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedControl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedControl, 500);
    lv_obj_set_y(ui_SpeedControl, 350);
    lv_label_set_text(ui_SpeedControl, "Speed Control\n");
    lv_obj_set_style_text_color(ui_SpeedControl, lv_color_hex(0x4140FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedControl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SpeedControl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedControl, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBack = lv_btn_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_BtnBack, 100);
    lv_obj_set_height(ui_BtnBack, 40);
    lv_obj_set_x(ui_BtnBack, 330);
    lv_obj_set_y(ui_BtnBack, -206);
    lv_obj_set_align(ui_BtnBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBack = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBack, 329);
    lv_obj_set_y(ui_LabelBack, -196);
    lv_obj_set_align(ui_LabelBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBack, "Back\n");
    lv_obj_set_style_text_color(ui_LabelBack, lv_color_hex(0xFEFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBack, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPrintProgress = lv_label_create(ui_ScreenPrintStatus);
    lv_obj_set_width(ui_LabelPrintProgress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPrintProgress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPrintProgress, -252);
    lv_obj_set_y(ui_LabelPrintProgress, 44);
    lv_obj_set_align(ui_LabelPrintProgress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPrintProgress, "   Print\nProgress");
    lv_obj_set_style_text_color(ui_LabelPrintProgress, lv_color_hex(0xFDFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPrintProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPrintProgress, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPrintProgress, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ArcOverall, ui_event_ArcOverall, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BarHotend, ui_event_BarHotend, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BarBed, ui_event_BarBed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPauseResume, ui_event_BtnPauseResume, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnStop, ui_event_BtnStop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderSpeed, ui_event_SliderSpeed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnBack, ui_event_BtnBack, LV_EVENT_ALL, NULL);
    ui_ScreenPrintStatus = ui_ScreenPrintStatus;
    ui_uiPanelTopBar1 = ui_PanelTopNav2;
    ui_LabelFilename = ui_LabelFilename;
    ui_LabelState = ui_LabelState;
    ui_LabelProgressPercent = ui_LabelProgressPercent;
    ui_ArcOverall = ui_ArcOverall;
    ui_LabelBigPercent = ui_LabelBigPercent;
    ui_LabelHotendTitle = ui_LabelHotendTitle;
    ui_LabelHotend = ui_LabelHotend;
    ui_BarHotend = ui_BarHotend;
    ui_LabelBedTitle = ui_LabelBedTitle;
    ui_LabelBed = ui_LabelBed;
    ui_BarBed = ui_BarBed;
    ui_LabelLayer = ui_LabelLayer;
    ui_LabelZHeight = ui_LabelZHeight;
    ui_LabelElapsed = ui_LabelElapsed;
    ui_LabelRemaining = ui_LabelRemaining;
    ui_LabelSpeed = ui_LabelSpeed;
    ui_BtnPauseResume = ui_BtnPauseResume;
    ui_Pause = ui_Pause;
    ui_BtnStop = ui_BtnStop;
    ui_Stop = ui_Stop;
    ui_SliderSpeed = ui_SliderSpeed;
    ui_LabelSpeedValue = ui_LabelSpeedValue;
    ui_SpeedControl = ui_SpeedControl;
    ui_BtnBack = ui_BtnBack;
    ui_LabelBack = ui_LabelBack;
    ui_LabelPrintProgress = ui_LabelPrintProgress;

}

void ui_ScreenPrintStatus_screen_destroy(void)
{
    if(ui_ScreenPrintStatus) lv_obj_del(ui_ScreenPrintStatus);

    // NULL screen variables
    ui_ScreenPrintStatus = NULL;
    ui_ScreenPrintStatus = NULL;
    ui_uiPanelTopBar1 = NULL;
    ui_PanelTopNav2 = NULL;
    ui_LabelFilename = NULL;
    ui_LabelFilename = NULL;
    ui_LabelState = NULL;
    ui_LabelState = NULL;
    ui_LabelProgressPercent = NULL;
    ui_LabelProgressPercent = NULL;
    ui_ArcOverall = NULL;
    ui_ArcOverall = NULL;
    ui_LabelBigPercent = NULL;
    ui_LabelBigPercent = NULL;
    ui_LabelHotendTitle = NULL;
    ui_LabelHotendTitle = NULL;
    ui_LabelHotend = NULL;
    ui_LabelHotend = NULL;
    ui_BarHotend = NULL;
    ui_BarHotend = NULL;
    ui_LabelBedTitle = NULL;
    ui_LabelBedTitle = NULL;
    ui_LabelBed = NULL;
    ui_LabelBed = NULL;
    ui_BarBed = NULL;
    ui_BarBed = NULL;
    ui_LabelLayer = NULL;
    ui_LabelLayer = NULL;
    ui_LabelZHeight = NULL;
    ui_LabelZHeight = NULL;
    ui_LabelElapsed = NULL;
    ui_LabelElapsed = NULL;
    ui_LabelRemaining = NULL;
    ui_LabelRemaining = NULL;
    ui_LabelSpeed = NULL;
    ui_LabelSpeed = NULL;
    ui_BtnPauseResume = NULL;
    ui_BtnPauseResume = NULL;
    ui_Pause = NULL;
    ui_Pause = NULL;
    ui_Image4 = NULL;
    ui_BtnStop = NULL;
    ui_BtnStop = NULL;
    ui_Image5 = NULL;
    ui_Stop = NULL;
    ui_Stop = NULL;
    ui_SliderSpeed = NULL;
    ui_SliderSpeed = NULL;
    ui_LabelSpeedValue = NULL;
    ui_LabelSpeedValue = NULL;
    ui_SpeedControl = NULL;
    ui_SpeedControl = NULL;
    ui_BtnBack = NULL;
    ui_BtnBack = NULL;
    ui_LabelBack = NULL;
    ui_LabelBack = NULL;
    ui_LabelPrintProgress = NULL;
    ui_LabelPrintProgress = NULL;

}
