// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#include "ui.h"

lv_obj_t * ui_LabelSensitivityValue;
lv_obj_t * ui_LabelRefreshStatus;
lv_obj_t * ui_BtnRefreshStatus;
lv_obj_t * ui_LabelSaveToEEPROM;
lv_obj_t * ui_BtnSaveSensors;
lv_obj_t * ui_LabelApplySensors;
lv_obj_t * ui_BtnApplySensors;
lv_obj_t * ui_SliderJamSensitivity;
lv_obj_t * ui_LabelTestJamSensor;
lv_obj_t * ui_BtnJamTest;
lv_obj_t * ui_SwitchJam;
lv_obj_t * ui_LabelJamState;
lv_obj_t * ui_LabelJamTitle;
lv_obj_t * ui_LabelTestRunoutSensor;
lv_obj_t * ui_BtnRunoutTest;
lv_obj_t * ui_LabelRunoutStatus;
lv_obj_t * ui_LabelRunoutState;
lv_obj_t * ui_SwitchRunout;
lv_obj_t * ui_Filament_Sensors;
lv_obj_t * ui_BtnBack3;
lv_obj_t * ui_ScreenFilament;
lv_obj_t * ui_ScreenFilament = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_BtnBack3 = NULL;
lv_obj_t * ui_LabelBack3 = NULL;
lv_obj_t * ui_LabelTitle2 = NULL;
lv_obj_t * ui_LabelRunoutTitle = NULL;
lv_obj_t * ui_SwitchRunout = NULL;
lv_obj_t * ui_LabelRunoutState = NULL;
lv_obj_t * ui_LabelRunoutStatus = NULL;
lv_obj_t * ui_BtnRunoutTest = NULL;
lv_obj_t * ui_LabelTestRunoutSensor = NULL;
lv_obj_t * ui_LabelJamTitle = NULL;
lv_obj_t * ui_LabelJamState = NULL;
lv_obj_t * ui_SwitchJam = NULL;
lv_obj_t * ui_BtnJamTest = NULL;
lv_obj_t * ui_LabelTestJamSensor = NULL;
lv_obj_t * ui_LabelRunoutStatus2 = NULL;
lv_obj_t * ui_LabelJamSensitivity = NULL;
lv_obj_t * ui_SliderJamSensitivity = NULL;
lv_obj_t * ui_BtnApplySensors = NULL;
lv_obj_t * ui_LabelApplySensors = NULL;
lv_obj_t * ui_BtnSaveSensors = NULL;
lv_obj_t * ui_LabelSaveToEEPROM = NULL;
lv_obj_t * ui_BtnRefreshStatus = NULL;
lv_obj_t * ui_LabelRefreshStatus = NULL;
lv_obj_t * ui_LabelSensitivityValue = NULL;
// event funtions
void ui_event_BtnBack3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
    }
}

void ui_event_SwitchRunout(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventSwitchRunout(e);
    }
}

void ui_event_BtnRunoutTest(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnRunoutTest(e);
    }
}

void ui_event_SwitchJam(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventSwitchJam(e);
    }
}

void ui_event_BtnJamTest(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnJamTest(e);
    }
}

void ui_event_SliderJamSensitivity(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventSliderJamSensitivity(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelSensitivityValue, target, "", "");
    }
}

void ui_event_BtnApplySensors(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnApplySensors(e);
    }
}

void ui_event_BtnSaveSensors(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnSaveSensors(e);
    }
}

void ui_event_BtnRefreshStatus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnRefreshSensors(e);
    }
}

// build funtions

void ui_ScreenFilament_screen_init(void)
{
    ui_ScreenFilament = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenFilament, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_shadow_color(ui_ScreenFilament, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ScreenFilament, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScreenFilament, 12, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScreenFilament, 12, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_ScreenFilament);
    lv_obj_set_width(ui_Panel3, 800);
    lv_obj_set_height(ui_Panel3, 60);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBack3 = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_BtnBack3, 100);
    lv_obj_set_height(ui_BtnBack3, 40);
    lv_obj_set_x(ui_BtnBack3, 650);
    lv_obj_set_y(ui_BtnBack3, -10);
    lv_obj_add_flag(ui_BtnBack3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBack3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBack3 = lv_label_create(ui_BtnBack3);
    lv_obj_set_width(ui_LabelBack3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBack3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBack3, 1);
    lv_obj_set_y(ui_LabelBack3, 10);
    lv_obj_set_align(ui_LabelBack3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBack3, "Back\n");
    lv_obj_set_style_text_color(ui_LabelBack3, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBack3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBack3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBack3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitle2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_LabelTitle2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle2, 14);
    lv_obj_set_y(ui_LabelTitle2, -3);
    lv_label_set_text(ui_LabelTitle2, "Filament Sensors");
    lv_obj_set_style_text_color(ui_LabelTitle2, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitle2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTitle2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTitle2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRunoutTitle = lv_label_create(ui_ScreenFilament);
    lv_obj_set_width(ui_LabelRunoutTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRunoutTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRunoutTitle, 59);
    lv_obj_set_y(ui_LabelRunoutTitle, 77);
    lv_label_set_text(ui_LabelRunoutTitle, "Filament Runout Sensor");
    lv_obj_set_style_text_color(ui_LabelRunoutTitle, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRunoutTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRunoutTitle, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchRunout = lv_switch_create(ui_ScreenFilament);
    lv_obj_set_width(ui_SwitchRunout, 103);
    lv_obj_set_height(ui_SwitchRunout, 38);
    lv_obj_set_x(ui_SwitchRunout, 234);
    lv_obj_set_y(ui_SwitchRunout, 122);
    lv_obj_add_state(ui_SwitchRunout, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_SwitchRunout, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchRunout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRunoutState = lv_label_create(ui_ScreenFilament);
    lv_obj_set_width(ui_LabelRunoutState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRunoutState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRunoutState, -284);
    lv_obj_set_y(ui_LabelRunoutState, -98);
    lv_obj_set_align(ui_LabelRunoutState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRunoutState, "ENABLED");
    lv_obj_set_style_text_color(ui_LabelRunoutState, lv_color_hex(0xFE0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRunoutState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelRunoutState, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRunoutState, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRunoutStatus = lv_label_create(ui_ScreenFilament);
    lv_obj_set_width(ui_LabelRunoutStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRunoutStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRunoutStatus, -195);
    lv_obj_set_y(ui_LabelRunoutStatus, -38);
    lv_obj_set_align(ui_LabelRunoutStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRunoutStatus, "Current Status: OK");
    lv_obj_set_style_text_color(ui_LabelRunoutStatus, lv_color_hex(0xFBF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRunoutStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelRunoutStatus, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRunoutStatus, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnRunoutTest = lv_btn_create(ui_ScreenFilament);
    lv_obj_set_width(ui_BtnRunoutTest, 250);
    lv_obj_set_height(ui_BtnRunoutTest, 50);
    lv_obj_set_x(ui_BtnRunoutTest, 90);
    lv_obj_set_y(ui_BtnRunoutTest, 237);
    lv_obj_add_flag(ui_BtnRunoutTest, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnRunoutTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnRunoutTest, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnRunoutTest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnRunoutTest, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnRunoutTest, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTestRunoutSensor = lv_label_create(ui_BtnRunoutTest);
    lv_obj_set_width(ui_LabelTestRunoutSensor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTestRunoutSensor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTestRunoutSensor, -1);
    lv_obj_set_y(ui_LabelTestRunoutSensor, -3);
    lv_obj_set_align(ui_LabelTestRunoutSensor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTestRunoutSensor, "Test Runout Sensor");
    lv_obj_set_style_text_color(ui_LabelTestRunoutSensor, lv_color_hex(0xFCFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTestRunoutSensor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTestRunoutSensor, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTestRunoutSensor, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelJamTitle = lv_label_create(ui_ScreenFilament);
    lv_obj_set_width(ui_LabelJamTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelJamTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelJamTitle, 224);
    lv_obj_set_y(ui_LabelJamTitle, -153);
    lv_obj_set_align(ui_LabelJamTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelJamTitle, "Filament Jam Sensor");
    lv_obj_set_style_text_color(ui_LabelJamTitle, lv_color_hex(0xFCB501), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelJamTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelJamTitle, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelJamTitle, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelJamState = lv_label_create(ui_ScreenFilament);
    lv_obj_set_width(ui_LabelJamState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelJamState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelJamState, 160);
    lv_obj_set_y(ui_LabelJamState, -88);
    lv_obj_set_align(ui_LabelJamState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelJamState, "ENABLED\n");
    lv_obj_set_style_text_color(ui_LabelJamState, lv_color_hex(0xFD0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelJamState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelJamState, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelJamState, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchJam = lv_switch_create(ui_ScreenFilament);
    lv_obj_set_width(ui_SwitchJam, 103);
    lv_obj_set_height(ui_SwitchJam, 38);
    lv_obj_set_x(ui_SwitchJam, 662);
    lv_obj_set_y(ui_SwitchJam, 122);
    lv_obj_add_state(ui_SwitchJam, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_SwitchJam, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchJam, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnJamTest = lv_btn_create(ui_ScreenFilament);
    lv_obj_set_width(ui_BtnJamTest, 250);
    lv_obj_set_height(ui_BtnJamTest, 50);
    lv_obj_set_x(ui_BtnJamTest, 512);
    lv_obj_set_y(ui_BtnJamTest, 242);
    lv_obj_add_flag(ui_BtnJamTest, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnJamTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_BtnJamTest, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnJamTest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnJamTest, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnJamTest, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTestJamSensor = lv_label_create(ui_BtnJamTest);
    lv_obj_set_width(ui_LabelTestJamSensor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTestJamSensor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTestJamSensor, -2);
    lv_obj_set_y(ui_LabelTestJamSensor, -4);
    lv_obj_set_align(ui_LabelTestJamSensor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTestJamSensor, "Test Jam Sensor");
    lv_obj_set_style_text_color(ui_LabelTestJamSensor, lv_color_hex(0xFCFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTestJamSensor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTestJamSensor, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTestJamSensor, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRunoutStatus2 = lv_label_create(ui_ScreenFilament);
    lv_obj_set_width(ui_LabelRunoutStatus2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRunoutStatus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRunoutStatus2, 227);
    lv_obj_set_y(ui_LabelRunoutStatus2, -43);
    lv_obj_set_align(ui_LabelRunoutStatus2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRunoutStatus2, "Current Status: OK");
    lv_obj_set_style_text_color(ui_LabelRunoutStatus2, lv_color_hex(0xFBF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRunoutStatus2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelRunoutStatus2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRunoutStatus2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelJamSensitivity = lv_label_create(ui_ScreenFilament);
    lv_obj_set_width(ui_LabelJamSensitivity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelJamSensitivity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelJamSensitivity, 512);
    lv_obj_set_y(ui_LabelJamSensitivity, 325);
    lv_label_set_text(ui_LabelJamSensitivity, "Sensitivity");
    lv_obj_set_style_text_color(ui_LabelJamSensitivity, lv_color_hex(0xBB8505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelJamSensitivity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelJamSensitivity, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelJamSensitivity, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderJamSensitivity = lv_slider_create(ui_ScreenFilament);
    lv_slider_set_range(ui_SliderJamSensitivity, 1, 100);
    lv_slider_set_value(ui_SliderJamSensitivity, 3, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderJamSensitivity) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderJamSensitivity, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderJamSensitivity, 242);
    lv_obj_set_height(ui_SliderJamSensitivity, 38);
    lv_obj_set_x(ui_SliderJamSensitivity, 251);
    lv_obj_set_y(ui_SliderJamSensitivity, 159);
    lv_obj_set_align(ui_SliderJamSensitivity, LV_ALIGN_CENTER);

    ui_BtnApplySensors = lv_btn_create(ui_ScreenFilament);
    lv_obj_set_width(ui_BtnApplySensors, 137);
    lv_obj_set_height(ui_BtnApplySensors, 83);
    lv_obj_set_x(ui_BtnApplySensors, -300);
    lv_obj_set_y(ui_BtnApplySensors, 152);
    lv_obj_set_align(ui_BtnApplySensors, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnApplySensors, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnApplySensors, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelApplySensors = lv_label_create(ui_BtnApplySensors);
    lv_obj_set_width(ui_LabelApplySensors, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelApplySensors, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelApplySensors, -3);
    lv_obj_set_y(ui_LabelApplySensors, -1);
    lv_obj_set_align(ui_LabelApplySensors, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelApplySensors, "Apply All");
    lv_obj_set_style_text_color(ui_LabelApplySensors, lv_color_hex(0xFCFDFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelApplySensors, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelApplySensors, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelApplySensors, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSaveSensors = lv_btn_create(ui_ScreenFilament);
    lv_obj_set_width(ui_BtnSaveSensors, 137);
    lv_obj_set_height(ui_BtnSaveSensors, 83);
    lv_obj_set_x(ui_BtnSaveSensors, -137);
    lv_obj_set_y(ui_BtnSaveSensors, 150);
    lv_obj_set_align(ui_BtnSaveSensors, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSaveSensors, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSaveSensors, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSaveSensors, lv_color_hex(0xE40A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSaveSensors, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSaveToEEPROM = lv_label_create(ui_BtnSaveSensors);
    lv_obj_set_width(ui_LabelSaveToEEPROM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSaveToEEPROM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSaveToEEPROM, -3);
    lv_obj_set_y(ui_LabelSaveToEEPROM, -1);
    lv_obj_set_align(ui_LabelSaveToEEPROM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSaveToEEPROM, "       Save\n To EEPROM");
    lv_obj_set_style_text_color(ui_LabelSaveToEEPROM, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSaveToEEPROM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSaveToEEPROM, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSaveToEEPROM, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnRefreshStatus = lv_btn_create(ui_ScreenFilament);
    lv_obj_set_width(ui_BtnRefreshStatus, 137);
    lv_obj_set_height(ui_BtnRefreshStatus, 83);
    lv_obj_set_x(ui_BtnRefreshStatus, 26);
    lv_obj_set_y(ui_BtnRefreshStatus, 150);
    lv_obj_set_align(ui_BtnRefreshStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnRefreshStatus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnRefreshStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelRefreshStatus = lv_label_create(ui_BtnRefreshStatus);
    lv_obj_set_width(ui_LabelRefreshStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRefreshStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRefreshStatus, -3);
    lv_obj_set_y(ui_LabelRefreshStatus, -1);
    lv_obj_set_align(ui_LabelRefreshStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRefreshStatus, " Refresh \n  Status");
    lv_obj_set_style_text_color(ui_LabelRefreshStatus, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRefreshStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelRefreshStatus, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRefreshStatus, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensitivityValue = lv_label_create(ui_ScreenFilament);
    lv_obj_set_width(ui_LabelSensitivityValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensitivityValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensitivityValue, 315);
    lv_obj_set_y(ui_LabelSensitivityValue, 101);
    lv_obj_set_align(ui_LabelSensitivityValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSensitivityValue, "3mm");
    lv_obj_set_style_text_color(ui_LabelSensitivityValue, lv_color_hex(0xFD0303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensitivityValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSensitivityValue, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensitivityValue, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnBack3, ui_event_BtnBack3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchRunout, ui_event_SwitchRunout, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnRunoutTest, ui_event_BtnRunoutTest, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchJam, ui_event_SwitchJam, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnJamTest, ui_event_BtnJamTest, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderJamSensitivity, ui_event_SliderJamSensitivity, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnApplySensors, ui_event_BtnApplySensors, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSaveSensors, ui_event_BtnSaveSensors, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnRefreshStatus, ui_event_BtnRefreshStatus, LV_EVENT_ALL, NULL);
    ui_ScreenFilament = ui_ScreenFilament;
    ui_BtnBack3 = ui_BtnBack3;
    ui_Filament_Sensors = ui_LabelTitle2;
    ui_SwitchRunout = ui_SwitchRunout;
    ui_LabelRunoutState = ui_LabelRunoutState;
    ui_LabelRunoutStatus = ui_LabelRunoutStatus;
    ui_BtnRunoutTest = ui_BtnRunoutTest;
    ui_LabelTestRunoutSensor = ui_LabelTestRunoutSensor;
    ui_LabelJamTitle = ui_LabelJamTitle;
    ui_LabelJamState = ui_LabelJamState;
    ui_SwitchJam = ui_SwitchJam;
    ui_BtnJamTest = ui_BtnJamTest;
    ui_LabelTestJamSensor = ui_LabelTestJamSensor;
    ui_SliderJamSensitivity = ui_SliderJamSensitivity;
    ui_BtnApplySensors = ui_BtnApplySensors;
    ui_LabelApplySensors = ui_LabelApplySensors;
    ui_BtnSaveSensors = ui_BtnSaveSensors;
    ui_LabelSaveToEEPROM = ui_LabelSaveToEEPROM;
    ui_BtnRefreshStatus = ui_BtnRefreshStatus;
    ui_LabelRefreshStatus = ui_LabelRefreshStatus;
    ui_LabelSensitivityValue = ui_LabelSensitivityValue;

}

void ui_ScreenFilament_screen_destroy(void)
{
    if(ui_ScreenFilament) lv_obj_del(ui_ScreenFilament);

    // NULL screen variables
    ui_ScreenFilament = NULL;
    ui_ScreenFilament = NULL;
    ui_Panel3 = NULL;
    ui_BtnBack3 = NULL;
    ui_BtnBack3 = NULL;
    ui_LabelBack3 = NULL;
    ui_Filament_Sensors = NULL;
    ui_LabelTitle2 = NULL;
    ui_LabelRunoutTitle = NULL;
    ui_SwitchRunout = NULL;
    ui_SwitchRunout = NULL;
    ui_LabelRunoutState = NULL;
    ui_LabelRunoutState = NULL;
    ui_LabelRunoutStatus = NULL;
    ui_LabelRunoutStatus = NULL;
    ui_BtnRunoutTest = NULL;
    ui_BtnRunoutTest = NULL;
    ui_LabelTestRunoutSensor = NULL;
    ui_LabelTestRunoutSensor = NULL;
    ui_LabelJamTitle = NULL;
    ui_LabelJamTitle = NULL;
    ui_LabelJamState = NULL;
    ui_LabelJamState = NULL;
    ui_SwitchJam = NULL;
    ui_SwitchJam = NULL;
    ui_BtnJamTest = NULL;
    ui_BtnJamTest = NULL;
    ui_LabelTestJamSensor = NULL;
    ui_LabelTestJamSensor = NULL;
    ui_LabelRunoutStatus2 = NULL;
    ui_LabelJamSensitivity = NULL;
    ui_SliderJamSensitivity = NULL;
    ui_SliderJamSensitivity = NULL;
    ui_BtnApplySensors = NULL;
    ui_BtnApplySensors = NULL;
    ui_LabelApplySensors = NULL;
    ui_LabelApplySensors = NULL;
    ui_BtnSaveSensors = NULL;
    ui_BtnSaveSensors = NULL;
    ui_LabelSaveToEEPROM = NULL;
    ui_LabelSaveToEEPROM = NULL;
    ui_BtnRefreshStatus = NULL;
    ui_BtnRefreshStatus = NULL;
    ui_LabelRefreshStatus = NULL;
    ui_LabelRefreshStatus = NULL;
    ui_LabelSensitivityValue = NULL;
    ui_LabelSensitivityValue = NULL;

}
