// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#include "ui.h"

lv_obj_t * ui_LabelPIDTitle;
lv_obj_t * ui_LabelSavePID;
lv_obj_t * ui_BtnSavePID;
lv_obj_t * ui_LabelPIDBed;
lv_obj_t * ui_BtnPIDBed;
lv_obj_t * ui_LabelPIDHotend;
lv_obj_t * ui_BtnPIDHotend;
lv_obj_t * ui_LabelPIDStatus;
lv_obj_t * ui_PanelPID;
lv_obj_t * ui_LabelCustom;
lv_obj_t * ui_BtnCustom;
lv_obj_t * ui_LabelABS;
lv_obj_t * ui_BtnABS;
lv_obj_t * ui_LabelPETG;
lv_obj_t * ui_BtnPETG;
lv_obj_t * ui_LabelPLA;
lv_obj_t * ui_BtnPLA;
lv_obj_t * ui_LabelBedValue;
lv_obj_t * ui_ArcBed;
lv_obj_t * ui_ArcHotend;
lv_obj_t * ui_LabelHotendValue;
lv_obj_t * ui_LabelScreenTitle1;
lv_obj_t * ui_LabelBack7;
lv_obj_t * ui_BtnBack7;
lv_obj_t * ui_PanelTopBar;
lv_obj_t * ui_ScreenTemperature;
lv_obj_t * ui_ScreenTemperature = NULL;
lv_obj_t * ui_PanelTopBar = NULL;
lv_obj_t * ui_BtnBack7 = NULL;
lv_obj_t * ui_LabelBack7 = NULL;
lv_obj_t * ui_LabelScreenTitle1 = NULL;
lv_obj_t * ui_LabelHotendTitle1 = NULL;
lv_obj_t * ui_LabelHotendValue = NULL;
lv_obj_t * ui_ArcHotend = NULL;
lv_obj_t * ui_Image23 = NULL;
lv_obj_t * ui_LabelBedTitle1 = NULL;
lv_obj_t * ui_ArcBed = NULL;
lv_obj_t * ui_LabelBedValue = NULL;
lv_obj_t * ui_Image27 = NULL;
lv_obj_t * ui_BtnPLA = NULL;
lv_obj_t * ui_LabelPLA = NULL;
lv_obj_t * ui_BtnPETG = NULL;
lv_obj_t * ui_LabelPETG = NULL;
lv_obj_t * ui_BtnABS = NULL;
lv_obj_t * ui_LabelABS = NULL;
lv_obj_t * ui_BtnCustom = NULL;
lv_obj_t * ui_LabelCustom = NULL;
lv_obj_t * ui_PanelPID = NULL;
lv_obj_t * ui_LabelPIDStatus = NULL;
lv_obj_t * ui_BtnPIDHotend = NULL;
lv_obj_t * ui_LabelPIDHotend = NULL;
lv_obj_t * ui_BtnPIDBed = NULL;
lv_obj_t * ui_LabelPIDBed = NULL;
lv_obj_t * ui_BtnSavePID = NULL;
lv_obj_t * ui_LabelSavePID = NULL;
lv_obj_t * ui_LabelPIDTitle = NULL;
// event funtions
void ui_event_BtnBack7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
    }
}

void ui_event_LabelHotendValue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelHotendValue, target, "", "");
    }
}

void ui_event_ArcHotend(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventArcHotend(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelHotendValue, target, "", "");
    }
}

void ui_event_ArcBed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_eventArcBed(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelBedValue, target, "", "");
    }
}

void ui_event_LabelBedValue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_LabelHotendValue, target, "", "");
    }
}

void ui_event_BtnPLA(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnPLA(e);
    }
}

void ui_event_BtnPETG(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnPETG(e);
    }
}

void ui_event_BtnABS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnABS(e);
    }
}

void ui_event_BtnCustom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnPLA(e);
    }
}

void ui_event_LabelCustom(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnCustom(e);
    }
}

void ui_event_BtnPIDHotend(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnPIDHotend(e);
    }
}

void ui_event_BtnSavePID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnSavePID(e);
    }
}

// build funtions

void ui_ScreenTemperature_screen_init(void)
{
    ui_ScreenTemperature = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenTemperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenTemperature, lv_color_hex(0x02374D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTopBar = lv_obj_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_PanelTopBar, 800);
    lv_obj_set_height(ui_PanelTopBar, 60);
    lv_obj_clear_flag(ui_PanelTopBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTopBar, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTopBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBack7 = lv_btn_create(ui_PanelTopBar);
    lv_obj_set_width(ui_BtnBack7, 100);
    lv_obj_set_height(ui_BtnBack7, 40);
    lv_obj_set_x(ui_BtnBack7, 649);
    lv_obj_set_y(ui_BtnBack7, -11);
    lv_obj_add_flag(ui_BtnBack7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBack7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBack7 = lv_label_create(ui_BtnBack7);
    lv_obj_set_width(ui_LabelBack7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBack7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBack7, 0);
    lv_obj_set_y(ui_LabelBack7, 11);
    lv_obj_set_align(ui_LabelBack7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBack7, "Back\n");
    lv_obj_set_style_text_color(ui_LabelBack7, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBack7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBack7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBack7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScreenTitle1 = lv_label_create(ui_PanelTopBar);
    lv_obj_set_width(ui_LabelScreenTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScreenTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelScreenTitle1, 7);
    lv_obj_set_y(ui_LabelScreenTitle1, -6);
    lv_label_set_text(ui_LabelScreenTitle1, "Temperature Control");
    lv_obj_set_style_text_color(ui_LabelScreenTitle1, lv_color_hex(0xFBF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScreenTitle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelScreenTitle1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelScreenTitle1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHotendTitle1 = lv_label_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_LabelHotendTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHotendTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHotendTitle1, 90);
    lv_obj_set_y(ui_LabelHotendTitle1, 56);
    lv_label_set_text(ui_LabelHotendTitle1, "Hotend\n");
    lv_obj_set_style_text_color(ui_LabelHotendTitle1, lv_color_hex(0xFF8800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHotendTitle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHotendTitle1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHotendValue = lv_label_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_LabelHotendValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHotendValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHotendValue, 105);
    lv_obj_set_y(ui_LabelHotendValue, 174);
    lv_label_set_text(ui_LabelHotendValue, "210°C");
    lv_obj_set_style_text_color(ui_LabelHotendValue, lv_color_hex(0xFD0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHotendValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHotendValue, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHotendValue, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcHotend = lv_arc_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_ArcHotend, 220);
    lv_obj_set_height(ui_ArcHotend, 220);
    lv_obj_set_x(ui_ArcHotend, 28);
    lv_obj_set_y(ui_ArcHotend, 94);
    lv_arc_set_range(ui_ArcHotend, 0, 300);
    lv_arc_set_value(ui_ArcHotend, 50);
    lv_obj_set_style_arc_color(ui_ArcHotend, lv_color_hex(0xE38008), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHotend, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image23 = lv_img_create(ui_ScreenTemperature);
    lv_img_set_src(ui_Image23, &ui_img_355628395);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image23, -264);
    lv_obj_set_y(ui_Image23, 21);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBedTitle1 = lv_label_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_LabelBedTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBedTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBedTitle1, 633);
    lv_obj_set_y(ui_LabelBedTitle1, 56);
    lv_label_set_text(ui_LabelBedTitle1, "Bed");
    lv_obj_set_style_text_color(ui_LabelBedTitle1, lv_color_hex(0x4488FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBedTitle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBedTitle1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBedTitle1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBed = lv_arc_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_ArcBed, 220);
    lv_obj_set_height(ui_ArcBed, 220);
    lv_obj_set_x(ui_ArcBed, 555);
    lv_obj_set_y(ui_ArcBed, 94);
    lv_arc_set_value(ui_ArcBed, 50);
    lv_obj_set_style_arc_color(ui_ArcBed, lv_color_hex(0x1405FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcBed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBedValue = lv_label_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_LabelBedValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBedValue, 622);
    lv_obj_set_y(ui_LabelBedValue, 174);
    lv_label_set_text(ui_LabelBedValue, " 60°C");
    lv_obj_set_style_text_color(ui_LabelBedValue, lv_color_hex(0xFD0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBedValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBedValue, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBedValue, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image27 = lv_img_create(ui_ScreenTemperature);
    lv_img_set_src(ui_Image27, &ui_img_426815153);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image27, 273);
    lv_obj_set_y(ui_Image27, 25);
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnPLA = lv_btn_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_BtnPLA, 120);
    lv_obj_set_height(ui_BtnPLA, 70);
    lv_obj_set_x(ui_BtnPLA, 267);
    lv_obj_set_y(ui_BtnPLA, 72);
    lv_obj_add_flag(ui_BtnPLA, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPLA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPLA = lv_label_create(ui_BtnPLA);
    lv_obj_set_width(ui_LabelPLA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPLA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPLA, -6);
    lv_obj_set_y(ui_LabelPLA, 2);
    lv_obj_set_align(ui_LabelPLA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPLA, "PLA");
    lv_obj_set_style_text_color(ui_LabelPLA, lv_color_hex(0xFD8B03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPLA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPLA, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPETG = lv_btn_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_BtnPETG, 120);
    lv_obj_set_height(ui_BtnPETG, 70);
    lv_obj_set_x(ui_BtnPETG, 412);
    lv_obj_set_y(ui_BtnPETG, 72);
    lv_obj_add_flag(ui_BtnPETG, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPETG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelPETG = lv_label_create(ui_BtnPETG);
    lv_obj_set_width(ui_LabelPETG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPETG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPETG, -6);
    lv_obj_set_y(ui_LabelPETG, 2);
    lv_obj_set_align(ui_LabelPETG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPETG, "PETG");
    lv_obj_set_style_text_color(ui_LabelPETG, lv_color_hex(0xFDFA03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPETG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPETG, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnABS = lv_btn_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_BtnABS, 120);
    lv_obj_set_height(ui_BtnABS, 70);
    lv_obj_set_x(ui_BtnABS, 267);
    lv_obj_set_y(ui_BtnABS, 165);
    lv_obj_add_flag(ui_BtnABS, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnABS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelABS = lv_label_create(ui_BtnABS);
    lv_obj_set_width(ui_LabelABS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelABS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelABS, -6);
    lv_obj_set_y(ui_LabelABS, -4);
    lv_obj_set_align(ui_LabelABS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelABS, "ABS");
    lv_obj_set_style_text_color(ui_LabelABS, lv_color_hex(0xFD0318), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelABS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelABS, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCustom = lv_btn_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_BtnCustom, 120);
    lv_obj_set_height(ui_BtnCustom, 70);
    lv_obj_set_x(ui_BtnCustom, 412);
    lv_obj_set_y(ui_BtnCustom, 165);
    lv_obj_add_flag(ui_BtnCustom, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCustom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCustom = lv_label_create(ui_BtnCustom);
    lv_obj_set_width(ui_LabelCustom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCustom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCustom, -1);
    lv_obj_set_y(ui_LabelCustom, 18);
    lv_obj_set_align(ui_LabelCustom, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCustom, "CUSTOM\n");
    lv_obj_set_style_text_color(ui_LabelCustom, lv_color_hex(0xFD8B03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCustom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCustom, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPID = lv_obj_create(ui_ScreenTemperature);
    lv_obj_set_width(ui_PanelPID, 450);
    lv_obj_set_height(ui_PanelPID, 180);
    lv_obj_set_x(ui_PanelPID, 181);
    lv_obj_set_y(ui_PanelPID, 299);
    lv_obj_clear_flag(ui_PanelPID, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelPID, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelPID, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPID, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelPID, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PanelPID, lv_color_hex(0xFCFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelPID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PanelPID, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelPID, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPIDStatus = lv_label_create(ui_PanelPID);
    lv_obj_set_width(ui_LabelPIDStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPIDStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPIDStatus, 1);
    lv_obj_set_y(ui_LabelPIDStatus, -17);
    lv_obj_set_align(ui_LabelPIDStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPIDStatus, "PID Status: Ready");
    lv_obj_set_style_text_color(ui_LabelPIDStatus, lv_color_hex(0xEC1111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPIDStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPIDStatus, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPIDStatus, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_width(ui_LabelPIDStatus, 435, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_LabelPIDStatus, 435, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(ui_LabelPIDStatus, 85, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_LabelPIDStatus, 85, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPIDHotend = lv_btn_create(ui_PanelPID);
    lv_obj_set_width(ui_BtnPIDHotend, 125);
    lv_obj_set_height(ui_BtnPIDHotend, 50);
    lv_obj_set_x(ui_BtnPIDHotend, -155);
    lv_obj_set_y(ui_BtnPIDHotend, 61);
    lv_obj_set_align(ui_BtnPIDHotend, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPIDHotend, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPIDHotend, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnPIDHotend, lv_color_hex(0xE68108), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPIDHotend, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPIDHotend = lv_label_create(ui_BtnPIDHotend);
    lv_obj_set_width(ui_LabelPIDHotend, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPIDHotend, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPIDHotend, -1);
    lv_obj_set_y(ui_LabelPIDHotend, 0);
    lv_obj_set_align(ui_LabelPIDHotend, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPIDHotend, "TUNE HOTEND");
    lv_obj_set_style_text_color(ui_LabelPIDHotend, lv_color_hex(0xFDFCFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPIDHotend, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPIDHotend, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPIDBed = lv_btn_create(ui_PanelPID);
    lv_obj_set_width(ui_BtnPIDBed, 125);
    lv_obj_set_height(ui_BtnPIDBed, 50);
    lv_obj_set_x(ui_BtnPIDBed, 155);
    lv_obj_set_y(ui_BtnPIDBed, 61);
    lv_obj_set_align(ui_BtnPIDBed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPIDBed, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPIDBed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnPIDBed, lv_color_hex(0x1004FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPIDBed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPIDBed = lv_label_create(ui_BtnPIDBed);
    lv_obj_set_width(ui_LabelPIDBed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPIDBed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPIDBed, 1);
    lv_obj_set_y(ui_LabelPIDBed, 1);
    lv_obj_set_align(ui_LabelPIDBed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPIDBed, "TUNE BED");
    lv_obj_set_style_text_color(ui_LabelPIDBed, lv_color_hex(0xFCFCFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPIDBed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPIDBed, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSavePID = lv_btn_create(ui_PanelPID);
    lv_obj_set_width(ui_BtnSavePID, 158);
    lv_obj_set_height(ui_BtnSavePID, 50);
    lv_obj_set_x(ui_BtnSavePID, 2);
    lv_obj_set_y(ui_BtnSavePID, 61);
    lv_obj_set_align(ui_BtnSavePID, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSavePID, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSavePID, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSavePID, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSavePID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSavePID = lv_label_create(ui_BtnSavePID);
    lv_obj_set_width(ui_LabelSavePID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSavePID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSavePID, 1);
    lv_obj_set_y(ui_LabelSavePID, 1);
    lv_obj_set_align(ui_LabelSavePID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSavePID, "SAVE TO EEPROM");
    lv_obj_set_style_text_color(ui_LabelSavePID, lv_color_hex(0xFDFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSavePID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSavePID, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSavePID, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPIDTitle = lv_label_create(ui_PanelPID);
    lv_obj_set_width(ui_LabelPIDTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPIDTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPIDTitle, -3);
    lv_obj_set_y(ui_LabelPIDTitle, -74);
    lv_obj_set_align(ui_LabelPIDTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPIDTitle, "PID TUNING");
    lv_obj_set_style_text_color(ui_LabelPIDTitle, lv_color_hex(0xFCFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPIDTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPIDTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPIDTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnBack7, ui_event_BtnBack7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelHotendValue, ui_event_LabelHotendValue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcHotend, ui_event_ArcHotend, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcBed, ui_event_ArcBed, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelBedValue, ui_event_LabelBedValue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPLA, ui_event_BtnPLA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPETG, ui_event_BtnPETG, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnABS, ui_event_BtnABS, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelCustom, ui_event_LabelCustom, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnCustom, ui_event_BtnCustom, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPIDHotend, ui_event_BtnPIDHotend, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSavePID, ui_event_BtnSavePID, LV_EVENT_ALL, NULL);
    ui_ScreenTemperature = ui_ScreenTemperature;
    ui_PanelTopBar = ui_PanelTopBar;
    ui_BtnBack7 = ui_BtnBack7;
    ui_LabelBack7 = ui_LabelBack7;
    ui_LabelScreenTitle1 = ui_LabelScreenTitle1;
    ui_LabelHotendValue = ui_LabelHotendValue;
    ui_ArcHotend = ui_ArcHotend;
    ui_ArcBed = ui_ArcBed;
    ui_LabelBedValue = ui_LabelBedValue;
    ui_BtnPLA = ui_BtnPLA;
    ui_LabelPLA = ui_LabelPLA;
    ui_BtnPETG = ui_BtnPETG;
    ui_LabelPETG = ui_LabelPETG;
    ui_BtnABS = ui_BtnABS;
    ui_LabelABS = ui_LabelABS;
    ui_BtnCustom = ui_BtnCustom;
    ui_LabelCustom = ui_LabelCustom;
    ui_PanelPID = ui_PanelPID;
    ui_LabelPIDStatus = ui_LabelPIDStatus;
    ui_BtnPIDHotend = ui_BtnPIDHotend;
    ui_LabelPIDHotend = ui_LabelPIDHotend;
    ui_BtnPIDBed = ui_BtnPIDBed;
    ui_LabelPIDBed = ui_LabelPIDBed;
    ui_BtnSavePID = ui_BtnSavePID;
    ui_LabelSavePID = ui_LabelSavePID;
    ui_LabelPIDTitle = ui_LabelPIDTitle;

}

void ui_ScreenTemperature_screen_destroy(void)
{
    if(ui_ScreenTemperature) lv_obj_del(ui_ScreenTemperature);

    // NULL screen variables
    ui_ScreenTemperature = NULL;
    ui_ScreenTemperature = NULL;
    ui_PanelTopBar = NULL;
    ui_PanelTopBar = NULL;
    ui_BtnBack7 = NULL;
    ui_BtnBack7 = NULL;
    ui_LabelBack7 = NULL;
    ui_LabelBack7 = NULL;
    ui_LabelScreenTitle1 = NULL;
    ui_LabelScreenTitle1 = NULL;
    ui_LabelHotendTitle1 = NULL;
    ui_LabelHotendValue = NULL;
    ui_LabelHotendValue = NULL;
    ui_ArcHotend = NULL;
    ui_ArcHotend = NULL;
    ui_Image23 = NULL;
    ui_LabelBedTitle1 = NULL;
    ui_ArcBed = NULL;
    ui_ArcBed = NULL;
    ui_LabelBedValue = NULL;
    ui_LabelBedValue = NULL;
    ui_Image27 = NULL;
    ui_BtnPLA = NULL;
    ui_BtnPLA = NULL;
    ui_LabelPLA = NULL;
    ui_LabelPLA = NULL;
    ui_BtnPETG = NULL;
    ui_BtnPETG = NULL;
    ui_LabelPETG = NULL;
    ui_LabelPETG = NULL;
    ui_BtnABS = NULL;
    ui_BtnABS = NULL;
    ui_LabelABS = NULL;
    ui_LabelABS = NULL;
    ui_BtnCustom = NULL;
    ui_BtnCustom = NULL;
    ui_LabelCustom = NULL;
    ui_LabelCustom = NULL;
    ui_PanelPID = NULL;
    ui_PanelPID = NULL;
    ui_LabelPIDStatus = NULL;
    ui_LabelPIDStatus = NULL;
    ui_BtnPIDHotend = NULL;
    ui_BtnPIDHotend = NULL;
    ui_LabelPIDHotend = NULL;
    ui_LabelPIDHotend = NULL;
    ui_BtnPIDBed = NULL;
    ui_BtnPIDBed = NULL;
    ui_LabelPIDBed = NULL;
    ui_LabelPIDBed = NULL;
    ui_BtnSavePID = NULL;
    ui_BtnSavePID = NULL;
    ui_LabelSavePID = NULL;
    ui_LabelSavePID = NULL;
    ui_LabelPIDTitle = NULL;
    ui_LabelPIDTitle = NULL;

}
