// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#ifndef UI_SCREENPRINTSTATUS_H
#define UI_SCREENPRINTSTATUS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenPrintStatus
extern void ui_ScreenPrintStatus_screen_init(void);
extern void ui_ScreenPrintStatus_screen_destroy(void);
extern lv_obj_t * ui_ScreenPrintStatus;
extern lv_obj_t * ui_PanelTopNav2;
extern lv_obj_t * ui_LabelFilename;
extern lv_obj_t * ui_LabelState;
extern lv_obj_t * ui_LabelProgressPercent;
extern void ui_event_ArcOverall(lv_event_t * e);
extern lv_obj_t * ui_ArcOverall;
extern lv_obj_t * ui_LabelBigPercent;
extern lv_obj_t * ui_LabelHotendTitle;
extern lv_obj_t * ui_LabelHotend;
extern void ui_event_BarHotend(lv_event_t * e);
extern lv_obj_t * ui_BarHotend;
extern lv_obj_t * ui_LabelBedTitle;
extern lv_obj_t * ui_LabelBed;
extern void ui_event_BarBed(lv_event_t * e);
extern lv_obj_t * ui_BarBed;
extern lv_obj_t * ui_LabelLayer;
extern lv_obj_t * ui_LabelZHeight;
extern lv_obj_t * ui_LabelElapsed;
extern lv_obj_t * ui_LabelRemaining;
extern lv_obj_t * ui_LabelSpeed;
extern void ui_event_BtnPauseResume(lv_event_t * e);
extern lv_obj_t * ui_BtnPauseResume;
extern lv_obj_t * ui_Pause;
extern lv_obj_t * ui_Image4;
extern void ui_event_BtnStop(lv_event_t * e);
extern lv_obj_t * ui_BtnStop;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Stop;
extern void ui_event_SliderSpeed(lv_event_t * e);
extern lv_obj_t * ui_SliderSpeed;
extern lv_obj_t * ui_LabelSpeedValue;
extern lv_obj_t * ui_SpeedControl;
extern void ui_event_BtnBack(lv_event_t * e);
extern lv_obj_t * ui_BtnBack;
extern lv_obj_t * ui_LabelBack;
extern lv_obj_t * ui_LabelPrintProgress;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ScreenPrintStatus;
extern lv_obj_t * ui_uiPanelTopBar1;
extern lv_obj_t * ui_LabelFilename;
extern lv_obj_t * ui_LabelState;
extern lv_obj_t * ui_LabelProgressPercent;
extern lv_obj_t * ui_ArcOverall;
extern lv_obj_t * ui_LabelBigPercent;
extern lv_obj_t * ui_LabelHotendTitle;
extern lv_obj_t * ui_LabelHotend;
extern lv_obj_t * ui_BarHotend;
extern lv_obj_t * ui_LabelBedTitle;
extern lv_obj_t * ui_LabelBed;
extern lv_obj_t * ui_BarBed;
extern lv_obj_t * ui_LabelLayer;
extern lv_obj_t * ui_LabelZHeight;
extern lv_obj_t * ui_LabelElapsed;
extern lv_obj_t * ui_LabelRemaining;
extern lv_obj_t * ui_LabelSpeed;
extern lv_obj_t * ui_BtnPauseResume;
extern lv_obj_t * ui_Pause;
extern lv_obj_t * ui_BtnStop;
extern lv_obj_t * ui_Stop;
extern lv_obj_t * ui_SliderSpeed;
extern lv_obj_t * ui_LabelSpeedValue;
extern lv_obj_t * ui_SpeedControl;
extern lv_obj_t * ui_BtnBack;
extern lv_obj_t * ui_LabelBack;
extern lv_obj_t * ui_LabelPrintProgress;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

