// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#ifndef UI_SCREENFILAMENT_H
#define UI_SCREENFILAMENT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenFilament
extern void ui_ScreenFilament_screen_init(void);
extern void ui_ScreenFilament_screen_destroy(void);
extern lv_obj_t * ui_ScreenFilament;
extern lv_obj_t * ui_Panel3;
extern void ui_event_BtnBack3(lv_event_t * e);
extern lv_obj_t * ui_BtnBack3;
extern lv_obj_t * ui_LabelBack3;
extern lv_obj_t * ui_LabelTitle2;
extern lv_obj_t * ui_LabelRunoutTitle;
extern void ui_event_SwitchRunout(lv_event_t * e);
extern lv_obj_t * ui_SwitchRunout;
extern lv_obj_t * ui_LabelRunoutState;
extern lv_obj_t * ui_LabelRunoutStatus;
extern void ui_event_BtnRunoutTest(lv_event_t * e);
extern lv_obj_t * ui_BtnRunoutTest;
extern lv_obj_t * ui_LabelTestRunoutSensor;
extern lv_obj_t * ui_LabelJamTitle;
extern lv_obj_t * ui_LabelJamState;
extern void ui_event_SwitchJam(lv_event_t * e);
extern lv_obj_t * ui_SwitchJam;
extern void ui_event_BtnJamTest(lv_event_t * e);
extern lv_obj_t * ui_BtnJamTest;
extern lv_obj_t * ui_LabelTestJamSensor;
extern lv_obj_t * ui_LabelRunoutStatus2;
extern lv_obj_t * ui_LabelJamSensitivity;
extern void ui_event_SliderJamSensitivity(lv_event_t * e);
extern lv_obj_t * ui_SliderJamSensitivity;
extern void ui_event_BtnApplySensors(lv_event_t * e);
extern lv_obj_t * ui_BtnApplySensors;
extern lv_obj_t * ui_LabelApplySensors;
extern void ui_event_BtnSaveSensors(lv_event_t * e);
extern lv_obj_t * ui_BtnSaveSensors;
extern lv_obj_t * ui_LabelSaveToEEPROM;
extern void ui_event_BtnRefreshStatus(lv_event_t * e);
extern lv_obj_t * ui_BtnRefreshStatus;
extern lv_obj_t * ui_LabelRefreshStatus;
extern lv_obj_t * ui_LabelSensitivityValue;
// CUSTOM VARIABLES
extern lv_obj_t * ui_ScreenFilament;
extern lv_obj_t * ui_BtnBack3;
extern lv_obj_t * ui_Filament_Sensors;
extern lv_obj_t * ui_SwitchRunout;
extern lv_obj_t * ui_LabelRunoutState;
extern lv_obj_t * ui_LabelRunoutStatus;
extern lv_obj_t * ui_BtnRunoutTest;
extern lv_obj_t * ui_LabelTestRunoutSensor;
extern lv_obj_t * ui_LabelJamTitle;
extern lv_obj_t * ui_LabelJamState;
extern lv_obj_t * ui_SwitchJam;
extern lv_obj_t * ui_BtnJamTest;
extern lv_obj_t * ui_LabelTestJamSensor;
extern lv_obj_t * ui_SliderJamSensitivity;
extern lv_obj_t * ui_BtnApplySensors;
extern lv_obj_t * ui_LabelApplySensors;
extern lv_obj_t * ui_BtnSaveSensors;
extern lv_obj_t * ui_LabelSaveToEEPROM;
extern lv_obj_t * ui_BtnRefreshStatus;
extern lv_obj_t * ui_LabelRefreshStatus;
extern lv_obj_t * ui_LabelSensitivityValue;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

