// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CrowPanel_Marlin_HMI

#include "ui.h"

lv_obj_t * ui_LabelFactoryReset1;
lv_obj_t * ui_BtnFactoryReset1;
lv_obj_t * ui_BtnViewLogs;
lv_obj_t * ui_LabelBtnCheckUpdate;
lv_obj_t * ui_BtnCheckUpdate;
lv_obj_t * ui_LabelBuildDate;
lv_obj_t * ui_LabelHotend1;
lv_obj_t * ui_LabelBuildDate;
lv_obj_t * ui_LabelLVGL;
lv_obj_t * ui_LabelVersion;
lv_obj_t * ui_LabelSWTitle;
lv_obj_t * ui_LabelProbe;
lv_obj_t * ui_LabelDrivers;
lv_obj_t * ui_LabelDisplay;
lv_obj_t * ui_PanelSoftware;
lv_obj_t * ui_PanelHardware;
lv_obj_t * ui_LabelBoard;
lv_obj_t * ui_LabelFirmware;
lv_obj_t * ui_LabelSysTitle;
lv_obj_t * ui_PanelSystem1;
lv_obj_t * ui_LabelBack6;
lv_obj_t * ui_BtnBack6;
lv_obj_t * ui_ScreenAbout;
lv_obj_t * ui_ScreenAbout = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_BtnBack6 = NULL;
lv_obj_t * ui_LabelBack6 = NULL;
lv_obj_t * ui_LabelTitle4 = NULL;
lv_obj_t * ui_PanelSystem1 = NULL;
lv_obj_t * ui_LabelSysTitle = NULL;
lv_obj_t * ui_LabelFirmware = NULL;
lv_obj_t * ui_LabelHMI = NULL;
lv_obj_t * ui_LabelBoard = NULL;
lv_obj_t * ui_PanelHardware = NULL;
lv_obj_t * ui_PanelSoftware = NULL;
lv_obj_t * ui_LabelHWTitle = NULL;
lv_obj_t * ui_LabelDisplay = NULL;
lv_obj_t * ui_LabelDrivers = NULL;
lv_obj_t * ui_LabelProbe = NULL;
lv_obj_t * ui_LabelSWTitle = NULL;
lv_obj_t * ui_LabelVersion = NULL;
lv_obj_t * ui_LabelLVGL = NULL;
lv_obj_t * ui_LabelAuthor = NULL;
lv_obj_t * ui_LabelHotend1 = NULL;
lv_obj_t * ui_LabelBuildDate = NULL;
lv_obj_t * ui_Image29 = NULL;
lv_obj_t * ui_BtnCheckUpdate = NULL;
lv_obj_t * ui_LabelBtnCheckUpdate = NULL;
lv_obj_t * ui_BtnViewLogs = NULL;
lv_obj_t * ui_LabelBtnViewLogs = NULL;
lv_obj_t * ui_BtnFactoryReset1 = NULL;
lv_obj_t * ui_LabelFactoryReset1 = NULL;
// event funtions
void ui_event_BtnBack6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenSettings_screen_init);
    }
}

void ui_event_LabelBack6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenSettings_screen_init);
    }
}

void ui_event_BtnCheckUpdate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnCheckUpdate(e);
    }
}

void ui_event_BtnViewLogs(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnShowLogs(e);
    }
}

void ui_event_BtnFactoryReset1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_eventBtnFactoryReset(e);
    }
}

// build funtions

void ui_ScreenAbout_screen_init(void)
{
    ui_ScreenAbout = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenAbout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel7 = lv_obj_create(ui_ScreenAbout);
    lv_obj_set_width(ui_Panel7, 800);
    lv_obj_set_height(ui_Panel7, 60);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBack6 = lv_btn_create(ui_Panel7);
    lv_obj_set_width(ui_BtnBack6, 100);
    lv_obj_set_height(ui_BtnBack6, 40);
    lv_obj_set_x(ui_BtnBack6, 647);
    lv_obj_set_y(ui_BtnBack6, -12);
    lv_obj_add_flag(ui_BtnBack6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBack6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBack6 = lv_label_create(ui_BtnBack6);
    lv_obj_set_width(ui_LabelBack6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBack6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBack6, -1);
    lv_obj_set_y(ui_LabelBack6, 10);
    lv_obj_set_align(ui_LabelBack6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBack6, "Back\n");
    lv_obj_set_style_text_color(ui_LabelBack6, lv_color_hex(0xFDFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBack6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBack6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBack6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitle4 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_LabelTitle4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle4, -273);
    lv_obj_set_y(ui_LabelTitle4, -1);
    lv_obj_set_align(ui_LabelTitle4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTitle4, "About This Printer");
    lv_obj_set_style_text_color(ui_LabelTitle4, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitle4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTitle4, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTitle4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSystem1 = lv_obj_create(ui_ScreenAbout);
    lv_obj_set_width(ui_PanelSystem1, 370);
    lv_obj_set_height(ui_PanelSystem1, 140);
    lv_obj_set_x(ui_PanelSystem1, 18);
    lv_obj_set_y(ui_PanelSystem1, 90);
    lv_obj_clear_flag(ui_PanelSystem1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelSystem1, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSystem1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSysTitle = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelSysTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSysTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSysTitle, -256);
    lv_obj_set_y(ui_LabelSysTitle, -140);
    lv_obj_set_align(ui_LabelSysTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSysTitle, "System");
    lv_obj_set_style_text_color(ui_LabelSysTitle, lv_color_hex(0x903D9F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSysTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSysTitle, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSysTitle, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFirmware = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelFirmware, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFirmware, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFirmware, 45);
    lv_obj_set_y(ui_LabelFirmware, 120);
    lv_label_set_text(ui_LabelFirmware, "Firmware: Marlin 2.1.x");
    lv_obj_set_style_text_color(ui_LabelFirmware, lv_color_hex(0xE4FD02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFirmware, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFirmware, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHMI = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelHMI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHMI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHMI, -198);
    lv_obj_set_y(ui_LabelHMI, -82);
    lv_obj_set_align(ui_LabelHMI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHMI, "HMI: LVGL 8.3.11 + CrowPanel 7\"");
    lv_obj_set_style_text_color(ui_LabelHMI, lv_color_hex(0xFD0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHMI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHMI, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHMI, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBoard = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelBoard, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBoard, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBoard, -218);
    lv_obj_set_y(ui_LabelBoard, -52);
    lv_obj_set_align(ui_LabelBoard, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBoard, "Controller: BTT Octopus 1.1");
    lv_obj_set_style_text_color(ui_LabelBoard, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBoard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBoard, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBoard, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHardware = lv_obj_create(ui_ScreenAbout);
    lv_obj_set_width(ui_PanelHardware, 370);
    lv_obj_set_height(ui_PanelHardware, 168);
    lv_obj_set_x(ui_PanelHardware, 18);
    lv_obj_set_y(ui_PanelHardware, 240);
    lv_obj_clear_flag(ui_PanelHardware, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelHardware, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHardware, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSoftware = lv_obj_create(ui_ScreenAbout);
    lv_obj_set_width(ui_PanelSoftware, 370);
    lv_obj_set_height(ui_PanelSoftware, 167);
    lv_obj_set_x(ui_PanelSoftware, 410);
    lv_obj_set_y(ui_PanelSoftware, 239);
    lv_obj_clear_flag(ui_PanelSoftware, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelSoftware, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSoftware, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHWTitle = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelHWTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHWTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHWTitle, -203);
    lv_obj_set_y(ui_LabelHWTitle, 21);
    lv_obj_set_align(ui_LabelHWTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHWTitle, "Hardware");
    lv_obj_set_style_text_color(ui_LabelHWTitle, lv_color_hex(0x86398E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHWTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHWTitle, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHWTitle, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDisplay = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelDisplay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDisplay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDisplay, -249);
    lv_obj_set_y(ui_LabelDisplay, 56);
    lv_obj_set_align(ui_LabelDisplay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDisplay, "Display: 7\" 800x480 IPS");
    lv_obj_set_style_text_color(ui_LabelDisplay, lv_color_hex(0xE5FF01), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDisplay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelDisplay, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDisplay, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDrivers = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelDrivers, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDrivers, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDrivers, -258);
    lv_obj_set_y(ui_LabelDrivers, 86);
    lv_obj_set_align(ui_LabelDrivers, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDrivers, "Drivers: TMC5160 (SPI)");
    lv_obj_set_style_text_color(ui_LabelDrivers, lv_color_hex(0xF00303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDrivers, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelDrivers, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDrivers, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelProbe = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelProbe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelProbe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelProbe, -197);
    lv_obj_set_y(ui_LabelProbe, 116);
    lv_obj_set_align(ui_LabelProbe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProbe, "Probe: BDSensor  V1.2c / Eddy Coil");
    lv_obj_set_style_text_color(ui_LabelProbe, lv_color_hex(0x29A040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelProbe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelProbe, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelProbe, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSWTitle = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelSWTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSWTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSWTitle, 192);
    lv_obj_set_y(ui_LabelSWTitle, 21);
    lv_obj_set_align(ui_LabelSWTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSWTitle, "Software");
    lv_obj_set_style_text_color(ui_LabelSWTitle, lv_color_hex(0x943C9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSWTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSWTitle, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSWTitle, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVersion = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVersion, 123);
    lv_obj_set_y(ui_LabelVersion, 56);
    lv_obj_set_align(ui_LabelVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVersion, "HMI Version: v3.0");
    lv_obj_set_style_text_color(ui_LabelVersion, lv_color_hex(0xE6FF02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelVersion, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVersion, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLVGL = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelLVGL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLVGL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLVGL, 91);
    lv_obj_set_y(ui_LabelLVGL, 86);
    lv_obj_set_align(ui_LabelLVGL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLVGL, "LVGL: 8.3.11");
    lv_obj_set_style_text_color(ui_LabelLVGL, lv_color_hex(0xEB0300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLVGL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelLVGL, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLVGL, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAuthor = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelAuthor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAuthor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAuthor, 134);
    lv_obj_set_y(ui_LabelAuthor, 116);
    lv_obj_set_align(ui_LabelAuthor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAuthor, "Made  on ESP32-S3");
    lv_obj_set_style_text_color(ui_LabelAuthor, lv_color_hex(0x29993F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAuthor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelAuthor, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAuthor, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHotend1 = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelHotend1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHotend1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHotend1, -229);
    lv_obj_set_y(ui_LabelHotend1, 145);
    lv_obj_set_align(ui_LabelHotend1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHotend1, "Hotend: 300°C , Bambo PS2");
    lv_obj_set_style_text_color(ui_LabelHotend1, lv_color_hex(0xFD7D01), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHotend1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelHotend1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHotend1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBuildDate = lv_label_create(ui_ScreenAbout);
    lv_obj_set_width(ui_LabelBuildDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBuildDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBuildDate, 147);
    lv_obj_set_y(ui_LabelBuildDate, 145);
    lv_obj_set_align(ui_LabelBuildDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBuildDate, "Build Date: May 2026");
    lv_obj_set_style_text_color(ui_LabelBuildDate, lv_color_hex(0xFD7D01), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBuildDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBuildDate, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBuildDate, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image29 = lv_img_create(ui_ScreenAbout);
    lv_img_set_src(ui_Image29, &ui_img_1099881434);
    lv_obj_set_width(ui_Image29, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image29, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image29, 190);
    lv_obj_set_y(ui_Image29, -95);
    lv_obj_set_align(ui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_Image29, lv_color_hex(0x1401FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Image29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Image29, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Image29, 13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnCheckUpdate = lv_btn_create(ui_ScreenAbout);
    lv_obj_set_width(ui_BtnCheckUpdate, 208);
    lv_obj_set_height(ui_BtnCheckUpdate, 50);
    lv_obj_set_x(ui_BtnCheckUpdate, -264);
    lv_obj_set_y(ui_BtnCheckUpdate, 205);
    lv_obj_set_align(ui_BtnCheckUpdate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnCheckUpdate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnCheckUpdate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnCheckUpdate, lv_color_hex(0x1000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnCheckUpdate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BtnCheckUpdate, lv_color_hex(0xF9F9FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnCheckUpdate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnCheckUpdate, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnCheckUpdate, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBtnCheckUpdate = lv_label_create(ui_BtnCheckUpdate);
    lv_obj_set_width(ui_LabelBtnCheckUpdate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnCheckUpdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBtnCheckUpdate, -2);
    lv_obj_set_y(ui_LabelBtnCheckUpdate, -1);
    lv_obj_set_align(ui_LabelBtnCheckUpdate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnCheckUpdate, "Check for Updates");
    lv_obj_set_style_text_align(ui_LabelBtnCheckUpdate, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBtnCheckUpdate, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnViewLogs = lv_btn_create(ui_ScreenAbout);
    lv_obj_set_width(ui_BtnViewLogs, 197);
    lv_obj_set_height(ui_BtnViewLogs, 50);
    lv_obj_set_x(ui_BtnViewLogs, 17);
    lv_obj_set_y(ui_BtnViewLogs, 204);
    lv_obj_set_align(ui_BtnViewLogs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnViewLogs, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnViewLogs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnViewLogs, lv_color_hex(0x298E37), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnViewLogs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBtnViewLogs = lv_label_create(ui_BtnViewLogs);
    lv_obj_set_width(ui_LabelBtnViewLogs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnViewLogs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBtnViewLogs, -2);
    lv_obj_set_y(ui_LabelBtnViewLogs, -1);
    lv_obj_set_align(ui_LabelBtnViewLogs, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnViewLogs, "View System Logs");
    lv_obj_set_style_text_color(ui_LabelBtnViewLogs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBtnViewLogs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelBtnViewLogs, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBtnViewLogs, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnFactoryReset1 = lv_btn_create(ui_ScreenAbout);
    lv_obj_set_width(ui_BtnFactoryReset1, 151);
    lv_obj_set_height(ui_BtnFactoryReset1, 50);
    lv_obj_set_x(ui_BtnFactoryReset1, 286);
    lv_obj_set_y(ui_BtnFactoryReset1, 203);
    lv_obj_set_align(ui_BtnFactoryReset1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnFactoryReset1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnFactoryReset1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelFactoryReset1 = lv_label_create(ui_BtnFactoryReset1);
    lv_obj_set_width(ui_LabelFactoryReset1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFactoryReset1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFactoryReset1, 1);
    lv_obj_set_y(ui_LabelFactoryReset1, 0);
    lv_obj_set_align(ui_LabelFactoryReset1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFactoryReset1, "Factory Reset");
    lv_obj_set_style_text_color(ui_LabelFactoryReset1, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFactoryReset1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelFactoryReset1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFactoryReset1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LabelBack6, ui_event_LabelBack6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnBack6, ui_event_BtnBack6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnCheckUpdate, ui_event_BtnCheckUpdate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnViewLogs, ui_event_BtnViewLogs, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnFactoryReset1, ui_event_BtnFactoryReset1, LV_EVENT_ALL, NULL);
    ui_ScreenAbout = ui_ScreenAbout;
    ui_BtnBack6 = ui_BtnBack6;
    ui_LabelBack6 = ui_LabelBack6;
    ui_PanelSystem1 = ui_PanelSystem1;
    ui_LabelSysTitle = ui_LabelSysTitle;
    ui_LabelFirmware = ui_LabelFirmware;
    ui_LabelBoard = ui_LabelBoard;
    ui_PanelHardware = ui_PanelHardware;
    ui_PanelSoftware = ui_PanelSoftware;
    ui_LabelDisplay = ui_LabelDisplay;
    ui_LabelDrivers = ui_LabelDrivers;
    ui_LabelProbe = ui_LabelProbe;
    ui_LabelSWTitle = ui_LabelSWTitle;
    ui_LabelVersion = ui_LabelVersion;
    ui_LabelLVGL = ui_LabelLVGL;
    ui_LabelBuildDate = ui_LabelAuthor;
    ui_LabelHotend1 = ui_LabelHotend1;
    ui_LabelBuildDate = ui_LabelBuildDate;
    ui_BtnCheckUpdate = ui_BtnCheckUpdate;
    ui_LabelBtnCheckUpdate = ui_LabelBtnCheckUpdate;
    ui_BtnViewLogs = ui_BtnViewLogs;
    ui_BtnFactoryReset1 = ui_BtnFactoryReset1;
    ui_LabelFactoryReset1 = ui_LabelFactoryReset1;

}

void ui_ScreenAbout_screen_destroy(void)
{
    if(ui_ScreenAbout) lv_obj_del(ui_ScreenAbout);

    // NULL screen variables
    ui_ScreenAbout = NULL;
    ui_ScreenAbout = NULL;
    ui_Panel7 = NULL;
    ui_BtnBack6 = NULL;
    ui_BtnBack6 = NULL;
    ui_LabelBack6 = NULL;
    ui_LabelBack6 = NULL;
    ui_LabelTitle4 = NULL;
    ui_PanelSystem1 = NULL;
    ui_PanelSystem1 = NULL;
    ui_LabelSysTitle = NULL;
    ui_LabelSysTitle = NULL;
    ui_LabelFirmware = NULL;
    ui_LabelFirmware = NULL;
    ui_LabelHMI = NULL;
    ui_LabelBoard = NULL;
    ui_LabelBoard = NULL;
    ui_PanelHardware = NULL;
    ui_PanelHardware = NULL;
    ui_PanelSoftware = NULL;
    ui_PanelSoftware = NULL;
    ui_LabelHWTitle = NULL;
    ui_LabelDisplay = NULL;
    ui_LabelDisplay = NULL;
    ui_LabelDrivers = NULL;
    ui_LabelDrivers = NULL;
    ui_LabelProbe = NULL;
    ui_LabelProbe = NULL;
    ui_LabelSWTitle = NULL;
    ui_LabelSWTitle = NULL;
    ui_LabelVersion = NULL;
    ui_LabelVersion = NULL;
    ui_LabelLVGL = NULL;
    ui_LabelLVGL = NULL;
    ui_LabelBuildDate = NULL;
    ui_LabelAuthor = NULL;
    ui_LabelHotend1 = NULL;
    ui_LabelHotend1 = NULL;
    ui_LabelBuildDate = NULL;
    ui_LabelBuildDate = NULL;
    ui_Image29 = NULL;
    ui_BtnCheckUpdate = NULL;
    ui_BtnCheckUpdate = NULL;
    ui_LabelBtnCheckUpdate = NULL;
    ui_LabelBtnCheckUpdate = NULL;
    ui_BtnViewLogs = NULL;
    ui_BtnViewLogs = NULL;
    ui_LabelBtnViewLogs = NULL;
    ui_BtnFactoryReset1 = NULL;
    ui_BtnFactoryReset1 = NULL;
    ui_LabelFactoryReset1 = NULL;
    ui_LabelFactoryReset1 = NULL;

}
